### ISSUE TITLE
Allow frameworks to log to the same instance

### ISSUE THREAD

**Issue by brentleyjones** [SwiftyBeaver/SwiftyBeaver#102]
It would be good to follow in CleanroomLogger's footsteps and allow the app to flip the switch on logging, setting destinations (such as cloud), etc. Then frameworks can use the logging API and all of the information will be pooled together.

https://rawgit.com/emaloney/CleanroomLogger/master/Documentation/API/Structs/Log.html

**Comment by skreutzberger** [comment]
Brentley, I don’t really understand your suggestion. Please join the [Slack channel](https://slack.swiftybeaver.com) for a more efficient discussion. Thanks!
