### ISSUE TITLE
iphone7

### ISSUE THREAD

**Issue by dimohamdy** [SwiftyBeaver/SwiftyBeaver#105]
detect the device is wrong i run in iphone6 and it show iphone7 there isn't iphone7 yet
![screen shot 2016-06-01 at 6 47 09 pm](https://cloud.githubusercontent.com/assets/1476754/15717948/788f98c6-2829-11e6-9e5e-f460522c6da3.png)

**Comment by davidrothera** [comment]
That is the model number - http://www.everyi.com/by-identifier/ipod-iphone-ipad-specs-by-model-identifier.html

**Comment by davidrothera** [comment]
`iPhone7,1` - iPhone 6 Plus
`iPhone7,2` - iPhone 6
`iPhone8,1` - iPhone 6s
`iPhone8,2` - iPhone 6s Plus
`iPhone8,3` - iPhone SE

**Comment by skreutzberger** [comment]
Oops, I seem to have forgotten to translate that model number into the iPhone name. It is fixed with the next release. Thanks David and great to have you back! Do you want to hang out more on Slack, things are going wild there in terms of roadmap and happy but demanding users :D
