### ISSUE TITLE
NSURL's URLByAppendingPathComponent returns an Optional in iOS 10

### ISSUE THREAD

**Issue by brianmichel** [SwiftyBeaver/SwiftyBeaver#110]
Using the new Xcode 8.0 beta in conjunction with iOS 10, there were changes to the `NSURL` API which marked certain functions as now returning an Optional where a non-Optional used to be returned. 

These three lines of code need to properly handle this change in order to ensure compilation with iOS 10, https://github.com/SwiftyBeaver/SwiftyBeaver/blob/master/sources/SBPlatformDestination.swift#L117-L119

**Comment by skreutzberger** [comment]
The mentioned changes were already implemented with 8033ce32600c23da1072775f35e9802aa1f19e4c and are available on the swift2.3 branch.
