### ISSUE TITLE
Xcode 8 beta 2 update

### ISSUE THREAD

**Issue by GSebastian** [SwiftyBeaver/SwiftyBeaver#112]
Are you considering updating to match the changes that came with Xcode 8 beta 2?

**Comment by skreutzberger** [comment]
Yes, it is ported as soon as my Xcode 8 Beta 2 finally installs. Currently struggling a bit with the XIB verification

**Comment by skreutzberger** [comment]
I tested and migrated the code to support Xcode 8 Beta 2.

The master branch was already working out-of-the-box with Xcode 8 Beta 2 and Swift 2.3 since there were no changes between Beta 1 and 2. 

SwiftyBeaver’s swift3 branch was ported to work with the latest Swift 3 from Xcode 8 Beta 2.
