### ISSUE TITLE
Does not seem to work with Xcode 7.3.1

### ISSUE THREAD

**Issue by pronebird** [SwiftyBeaver/SwiftyBeaver#113]
Hi,

I get obscure output in console like `[15:43:12.623] [fg150,178,193;VERBOSE[;: My name is üÄölèå`. Any ideas why XcodeColors does not work?

**Comment by skreutzberger** [comment]
The Xcode Colors plugin is missing, the `fg150,178,193` is color code. 

To fix it please read the bottom section of [http://docs.swiftybeaver.com/article/9-log-to-xcode-console](http://docs.swiftybeaver.com/article/9-log-to-xcode-console) where the installation of Xcode Colors is explained.

**Comment by pronebird** [comment]
Nope, it's installed and does not work.

```
➜  Plug-ins pwd
/Users/pronebird/Library/Application Support/Developer/Shared/Xcode/Plug-ins
➜  Plug-ins ls -la
total 24
drwxr-xr-x  12 pronebird  staff    408 Jul 15 15:50 .
drwxr-xr-x   4 pronebird  staff    136 Jul 15 15:38 ..
-rw-r--r--@  1 pronebird  staff  10244 Jul 15 15:49 .DS_Store
drwxr-xr-x   3 pronebird  staff    102 Jul 15 15:10 AdjustFontSize.xcplugin
drwxr-xr-x   3 pronebird  staff    102 Mar 26 16:01 Alcatraz.xcplugin
drwxr-xr-x   3 pronebird  staff    102 Jul 15 15:10 BBUDebuggerTuckAway.xcplugin
drwxr-xr-x   3 pronebird  staff    102 Sep 23  2015 KSImageNamed.xcplugin
drwxr-xr-x   3 pronebird  staff    102 Jul 15 15:10 SCXcodeEditorInset.xcplugin
drwxr-xr-x   3 pronebird  staff    102 Jul 15 15:10 VVDocumenter-Xcode.xcplugin
drwxr-xr-x   3 pronebird  staff    102 May  9 10:21 XCSnippetr.xcplugin
drwxr-xr-x@  3 pronebird  staff    102 Dec 10  2015 XcodeColors.xcplugin
drwxr-xr-x   3 pronebird  staff    102 May  9 10:21 XcodeExplorer.xcplugin
```

**Comment by davidrothera** [comment]
Even though the plugin is in the correct directory it could be that it is not enabled in XCode (which is why you are getting the colour codes)

Let me dig out a link now for re-enabling disabled plugins

**Comment by pronebird** [comment]
@davidrothera thanks. This is really weird because Xcode asked me if I wish to load the bundle and Alcatraz is generally activating plugins automatically. I installed the plugin manually from this repo though just to be sure...

**Comment by davidrothera** [comment]
First you will want to find the key to look into:

```
[drothera@drothera-mbp ~]$ defaults read com.apple.dt.Xcode | grep NonApple
    "DVTPlugInManagerNonApplePlugIns-Xcode-7.0" =     {
    "DVTPlugInManagerNonApplePlugIns-Xcode-7.0.1" =     {
    "DVTPlugInManagerNonApplePlugIns-Xcode-7.1" =     {
    "DVTPlugInManagerNonApplePlugIns-Xcode-7.1.1" =     {
    "DVTPlugInManagerNonApplePlugIns-Xcode-7.2" =     {
    "DVTPlugInManagerNonApplePlugIns-Xcode-7.2.1" =     {
    "DVTPlugInManagerNonApplePlugIns-Xcode-7.3" =     {
    "DVTPlugInManagerNonApplePlugIns-Xcode-7.3.1" =     {
```

Once you have that (7.3.1 for the current version):
```
[drothera@drothera-mbp ~]$ defaults read com.apple.dt.Xcode DVTPlugInManagerNonApplePlugIns-Xcode-7.3.1
{
    allowed =     {
        "com.deusty.XcodeColors" =         {
            version = 109;
        };
        "com.mneorr.Alcatraz" =         {
            version = 1;
        };
        "me.delisa.DerivedData-Exterminator" =         {
            version = 1;
        };
    };
    skipped =     {
    };
}
```

As you can see I have nothing in the skipped section, check yours though.

The easiest way to solve this is to delete the key:

```
defaults delete com.apple.dt.Xcode DVTPlugInManagerNonApplePlugIns-Xcode-7.3.1
```

**Comment by davidrothera** [comment]
@skreutzberger: You might want to put the above in a troubleshooting section in the docs as it seems to come up fairly often

Unfortunately Xcode plugins are a pain in the ass and even though Alcatraz helps it still feels like an uphill struggle at times.

**Comment by skreutzberger** [comment]
@davidrothera Very good idea! Unfortunately Xcode Colors is getting deprecated with Xcode 8 😢
I have on my list a small switch to set `.colored=false` if Swift 2.3 or 3 is detected.

**Comment by pronebird** [comment]
@davidrothera ugh thanks so much for this. Defo checking `defaults read com.apple.dt.Xcode DVTPlugInManagerNonApplePlugIns-Xcode-7.3.1` revealed that XcodeColors wasn't skipped, nor added to the list of other plug-ins even though I hit "Load bundle" upon first load. It's up and running now!!!
