### ISSUE TITLE
Coloring proposal

### ISSUE THREAD

**Issue by mojidabckuu** [SwiftyBeaver/SwiftyBeaver#126]
Library is awesome!
But what is about the feature to specify `attributedString` or whatever to make text colored. Let's say we have an SQL statement `SELECT * FROM users;` and we want to specify color for ranges or words to make `SELECT` and `FROM` colored.

**Comment by skreutzberger** [comment]
Interesting idea which maybe goes beyond what a logging library should do. But you could still use color (at least for file-based logging) as part of your string. Here are the file / terminal color codes: https://github.com/SwiftyBeaver/SwiftyBeaver/blob/master/sources/FileDestination.swift#L57
