### ISSUE TITLE
Override the log string format?

### ISSUE THREAD

**Issue by mark-anders** [SwiftyBeaver/SwiftyBeaver#132]
Is it possible to change the formatting of the log string?  Here's some background.  

The way I used to format my log messages was something like this:

    2016-09-01 19:14:04.186 [Sync.swift:697] NOTICE:<message>

The file name is Sync.swift and the line # is 697.  While I don't use the XCode plugin you reference - I wind up having too many issues with XCode plugins in general, I do use AppCode from JetBrains for much of my coding.  It allows me to just click on the links and go to the line of code.

The same log message from Swifty Beaver looks like:

    [2016-09-01 12:10:11.511] Sync.dumpSyncRequest():697 g253,202,78;WARNINGg253,202,78;WARNING

For these I don't get links.  I think there are a few reasons for this.  First, it's not filename:linenum.   However, it's not even class.method:linenum.  I don't have a class named Sync, because I do not always match 1-1 class name to file name.  So the Sync.swift file defines some enums, protocols and a few classes. 

It seems like either you're assuming that the class name is the same as the file name or you're mixing metaphors and having filename.methodname.

In any event, I would like to just be able to override how the log messages appear. 

Is there a way to do that?

**Comment by skreutzberger** [comment]
Firstly you can get rid of the weird `g253,202,78;` stuff (which are color codes but they anyway don’t work anymore in Xcode 8) by deactivating color in your destination. You can do that with `.colored=false`.

Secondly, there is currently no way of a custom formatter besides adjusting the output of the date and the general amount of details (`.detailOutput`) but any pull request is more than welcomed! 

Please check at the [console docs](http://docs.swiftybeaver.com/article/9-log-to-xcode-console) about what you can currently adjust.
