### ISSUE TITLE
Xcode 8 GM compatibility

### ISSUE THREAD

**Issue by skreutzberger** [SwiftyBeaver/SwiftyBeaver#138]
Check Swift 3 branch if Xcode 8 GM has new Swift 3 changes

**Comment by skreutzberger** [comment]
All tests are green, no need to change any line of source code. It seems Swift 3 is finally finished 🎉

**Comment by mudox** [comment]
How to switch to swift 3 branch using `pod`, I am trying to create a brand new project on Xcode 8 GM, but after `pod install`, Xcode kept prompting me to convert Swift 2 code to Swift 3?

**Comment by RemyDCF** [comment]
pod 'SwiftyBeaver', branch:'swift3'

**Comment by skreutzberger** [comment]
@RemyDCF Awesome, thanks! I will update the docs for the Swift3 branch about how to install under Cocoapods. Do you maybe also know how to use it for Carthage? 

The swift3 branch has a moving tag of 0.0.0, just in case you need to know that information 😬

**Comment by RemyDCF** [comment]
For Carthage, you need to add to your Cartfile this line :
github "SwiftyBeaver/SwiftyBeaver" "swift3"

**Comment by skreutzberger** [comment]
Wow, it was really so simple?! Thanks!

**Comment by RemyDCF** [comment]
You're welcome
