### ISSUE TITLE
Hiding internal files.

### ISSUE THREAD

**Issue by plasmLC** [SwiftyBeaver/SwiftyBeaver#139]
Guys, is this possible? My app provides advanced access to the /Dcouments application folder, and Realm, for example, allows to choose which file name should be used. SwiftyBeaver uses file names without leading dot, so it will be visible for app's users. 

What do you suggest to hide your files from user's eyes?

**Comment by skreutzberger** [comment]
What files do you mean and for what destination?

**Comment by plasmLC** [comment]
`/Documents/sbplatform_analytics.json`
`/Documents/sbplatform_entries_sending.json`

As I said before, my app provides access to the `/Documents` folder directly to users, so it very unlikely to show these files.

**Comment by skreutzberger** [comment]
Ah ok, I understand what you mean. You want to change the values of the 3 files at https://github.com/SwiftyBeaver/SwiftyBeaver/blob/master/sources/SBPlatformDestination.swift#L71

I will put it on the list for the next release to make these variables public / open (for Swift 3). In the meantime you can manually get access to these variables by making the public in the framework codebase.

**Comment by plasmLC** [comment]
@skreutzberger sorry, but I could not manage it to work properly.

I'm doing this:
<img width="847" alt="screen shot 2017-02-07 at 20 42 40" src="https://cloud.githubusercontent.com/assets/2793913/22703777/60edc93c-ed76-11e6-8a8c-fcaaaa1f81b6.png">

But one file - `sbplatform_analitycs.json` will be created in any case.
I suppose it will be there until behaviour of initialization will be changed: see from line [131](https://github.com/SwiftyBeaver/SwiftyBeaver/blob/master/sources/SBPlatformDestination.swift#L131) to line [147](https://github.com/SwiftyBeaver/SwiftyBeaver/blob/master/sources/SBPlatformDestination.swift#L147).

You're working with default names ANYWAY, so, please, do something with this. Either add leading dot before filenames or let user really change this urls and stop using default names before user changed it.

Guys, really need this fix — I could not allow my users see 'system' stuff among their documents.

**Comment by plasmLC** [comment]
@skreutzberger I suppose I need to fork the repo and do it on my own? Will you fix this?

**Comment by skreutzberger** [comment]
@plasmLC A solution could be to add the file names as additional parameters to `init()` but that may confuse users 🤔

**Comment by plasmLC** [comment]
@skreutzberger even if this `init()` will be `@convenience`?

**Comment by skreutzberger** [comment]
let me do a PR and then you can see if you like it :)

**Comment by skreutzberger** [comment]
@plasmLC please see here: https://github.com/SwiftyBeaver/SwiftyBeaver/pull/184 - would that solve your issue?

**Comment by plasmLC** [comment]
@skreutzberger yes, exactly what I need!

**Comment by skreutzberger** [comment]
@plasmLC Thanks! I will merge it into master and it will ship with the next version 1.1.3 later this week.
