### ISSUE TITLE
Which Next Custom Destination?

### ISSUE THREAD

**Issue by skreutzberger** [SwiftyBeaver/SwiftyBeaver#14]
Currently SwiftyBeaver supports Xcode Console & file as logging destinations.

What should be the next destination?

P.S.: Maybe the destinations should be renamed to beaver lodge - you know, where he brings the logs to :house:

**Comment by brendan09** [comment]
I created a simple destination that bridges logs to Crashlytics. I considered making a pull request, however it won't compile without Fabric / Crashlytics in your project. This would break a lot of people's setups if it was included in the pod.

Is this something you'd be interested in a pull request for? It's incredibly simple.

**Comment by davidrothera** [comment]
I would avoid including a requirement such as Fabric in such a small pod, perhaps there is a way to achieve this while allowing the basic one to be used with no requirements.

**Comment by davidrothera** [comment]
I think this could be achieved by adding another framework target that includes the fabric logger which could then be used if needed.

**Comment by skreutzberger** [comment]
That is a general issue of sending logs to 3rd parties I guess?

**Comment by skreutzberger** [comment]
Yes, we should avoid adding any unnecessary or maybe any dependency at all to the project. As far as I know, all crash reporting / logging services somehow tie directly into the client’s code by importing Frameworks.

**Comment by skreutzberger** [comment]
Oh and what other iOS-related log services are still relevant? I just know Loggly and Papertrail and of course Crashlytics. I know there are many more out there but what about logging to other channels like Slack? Is that common for iOS apps? 

P.S.: I have a background more in server-based apps than mobile apps so maybe there is something that I am missing?

**Comment by tosbaha** [comment]
I think Loggly could be an option. However there are lots of variables and scenarios to think of. 

- It should have maybe its own buffer in memory or file.
- Only send when the limit is reached.
- File must be uploaded by background transfer.

I think https://github.com/melke/SlimLogger/blob/master/SlimLogger/SlimLogglyDestination.swift can be used as starting point for ideas.

**Comment by skreutzberger** [comment]
I spoke with Crashlytics and discussed possible solutions more on that is coming soon. Loggly should be simpler but I need to think about it a bit longer to come up with a more elegant and flexible solution which works for most / every external logging service.

**Comment by tosbaha** [comment]
That makes two of us. I also emailed Crashlytics two days ago and they said they will come up with some logging solutions soon and asked me if I want to test it. I hope it comes soon. Because logging remotely is so important to access customer's device which you don't have direct access.

**Comment by skreutzberger** [comment]
But it would be better if they do not provide their own logging solution but better integrate with existing, more flexible ones.

**Comment by yonaskolb** [comment]
I think having a destination that just takes a block that is called each time something is logged would allow for a lot of these custom logging solutions to be integrated quite easily

**Comment by reesemclean** [comment]
I am personally interested in Slack/Email logging... But these would need some sort of server integration?

It would be pretty nice to be able to init something like a SlackDestination with an API key and a channel name and get logging directly into Slack.

**Comment by reesemclean** [comment]
I guess the Destination could use the Slack API directly... So you would need to set at the minimum the web hook url.

So all these destinations that involve an API request are gonna have quite a bit in common - a buffer file, a way to limit how often/when the buffer is sent, a mechanism to take items off the buffer, send them in the background, and then remove them on success.

**Comment by skreutzberger** [comment]
Yes, I also thought about Slack as destination but it would involve adding a web hook and in general relying on multiple external APIs with changing behavior under load or a bad network  connection. I am currently working on a more general solution which would work across multiple destinations and will close the issue until I have something ready for testing.
