### ISSUE TITLE
Lastest release Tag

### ISSUE THREAD

**Issue by FranciscoAmado** [SwiftyBeaver/SwiftyBeaver#145]
Hi,

I've noticed that your latest release version is tagged as `0.0.0` instead of maybe `0.7.1`

Thanks for building SwiftyBeaver!
Francisco

**Comment by skreutzberger** [comment]
The swift3 branch is tagged as 0.0.0 to make sure that Swift Package Manager can always access the latest development version. On the master branch the release version is 0.7.0

In the next few days all that will change and the swift 3 branch will move into master and will get the tag 1.0.0

**Comment by FranciscoAmado** [comment]
Ohh, didn't know it needed to be like that.

Sorry for the inconvenience!

**Comment by skreutzberger** [comment]
No worries, great catch & thanks for diving deeper into SwiftyBeaver 😊
