### ISSUE TITLE
General ideas / Icebox candidates

### ISSUE THREAD

**Issue by skreutzberger** [SwiftyBeaver/SwiftyBeaver#146]
Put here stuff in that just comes to your mind but was not discussed yet over Slack or Github just not to forget about it. Maybe see it as a pre-icebox 🗃🍦😊
- set ID or tag for destination to be able to adjust it later on
- connecting a SwiftyBeaver logger instance of the main app to SwiftyBeaver loggers inside dynamic frameworks through delegation
- change destination properties after assignment (evaluate if that is not already possible)
- send session ID to platform destination
- report back the current connectivity (3G, Wifi)
- avoid sending of too large log file to SBPlatform
- crash reporting (but is it still a thing with iOS 10 where crashes are automatically reported?)

**Comment by maxydon** [comment]
is/will the FileDestination encryptable?

**Comment by skreutzberger** [comment]
@maxydon Most users are using the file destination for local development only and are tailing the file in Terminal during development. For that use case encryption would not work and so the file destination will stay unencrypted.

For encrypted logging during release I recommend the platform destination instead.
