### ISSUE TITLE
Post-release cleanup

### ISSUE THREAD

**Issue by skreutzberger** [SwiftyBeaver/SwiftyBeaver#149]
With the release of 1.0.0 some things can be deleted or still need to be done:

- [ ] delete swift 3 branch
- [x] delete swift3 Github issues label
- [ ] push Cocoapods (still has an issue with Swift 3)

**Comment by davidrothera** [comment]
What issues are you seeing with Cocoapods and Swift3? I was able to push a Swift3 pod yesterday with some changes but nothing major.

**Comment by skreutzberger** [comment]
@davidrothera @jenjia  When I am running `pod trunk push SwiftyBeaver.podspec --verbose` under Cocoapods `1.1.0.rc.2` I am getting the attached error output. It seems it compiles using Swift 2.3 even if I did set in every target Swift 3.0.
[output.txt](https://github.com/SwiftyBeaver/SwiftyBeaver/files/476747/output.txt)

**Comment by davidrothera** [comment]
Add a `.swift-version` file to the root of the repo and put in `3` into it.

This is what Cocoapods have opted for to tell the compiler to use v3 rather than v2.3

**Comment by skreutzberger** [comment]
It worked 🎉 - thank you!

That definitely wins the 🏆 as smallest possible fix ever 😀
