### ISSUE TITLE
UTC Date

### ISSUE THREAD

**Issue by igor9silva** [SwiftyBeaver/SwiftyBeaver#152]
Hi,

I'd to log dates in UTC, since I have users from different timezones.

I've seen there is a commented line in `formatDate(_:)` setting the NSDateFormatter's date into UTC (`formatter.timeZone = NSTimeZone(abbreviation: "UTC")`), which leads me to think this used to be the default behavior.

My solution was to implement a flag (`logDatesAsUTC`). I've also thought about making it a String (`timezoneAbbreviation`) or even a NSTimeZone itself.

I haven't send a pull request because of the commented line.

What is your opinion on that? @skreutzberger

**Comment by skreutzberger** [comment]
Good point! I will extend the custom formatting with the new key `$Z` (closed by `$z`) which will return the formatted datetime in Zulu time / UTC.

**Comment by igor9silva** [comment]
Great solution @skreutzberger! 

Thanks for acting so fast.
