### ISSUE TITLE
Update Documentation for Colored Logging in XCode 8

### ISSUE THREAD

**Issue by byrneciaran** [SwiftyBeaver/SwiftyBeaver#153]
The documentation should be updated as the XCodeColors pluggin no longer works and it's not clear how to get the Emoji support in XCode 8 - which is a cool idea btw

Also the link: https://github.com/SwiftyBeaver/SwiftyBeaver/raw/master/Assets/XcodeColors.xcplugin.zip
is not valid

**Comment by skreutzberger** [comment]
Thanks for the comment, I updated the docs and removed all old Xcode 7 stuff. Long live Xcode 8 🤖

[New Console Docs](http://docs.swiftybeaver.com/article/9-log-to-xcode-console)

**Comment by byrneciaran** [comment]
That was quick :)

Just to clarify though - the emoji logging doesn't work in XCode 8 for me? I get the logs just with no emoji

**Comment by skreutzberger** [comment]
Are you using Swift 2.3 or 3? Because the emojis are just working for Swift 3.

**Comment by byrneciaran** [comment]
Ah ok, I'm using 2.3, that's the issue

**Comment by skreutzberger** [comment]
You can get the emojis in Swift 2.3 with this code:
https://gist.github.com/skreutzberger/7c396573796473ed1be2c6d15cafed34

**Comment by skreutzberger** [comment]
I also updated the README and added the Gist :)
