### ISSUE TITLE
Extra numbers are appearing in logging

### ISSUE THREAD

**Issue by dhamukrish** [SwiftyBeaver/SwiftyBeaver#155]
I can see extra numbers in some of the logged line in Xcode 8.0 Swift 3. I am not sure what those numbers are? Below are the sample logs

Please advise.

`20:06:17 \360\237\360\237\360\237\222💙 INFO AppDelegate.somefunction()():543 some message...`

`20:06:17 \360\237\222💙 INFO someswiftfile.somefunction()():122 some message`

**Comment by skreutzberger** [comment]
Are you using Xcode 8 Beta? What version of SwiftyBeaver are you using, what destination and what is your `.format` property in case you set it?

**Comment by dhamukrish** [comment]
Xcode Version: 8.0 (8A218a) GA
SwiftyBeaver Version: 1.0.3

**Propery Set**
```
let console = ConsoleDestination()
console.format = "$DHH:mm:ss$d $C$L$c $N.$F():$l $M"
console.asynchronously = true
console.minLevel = .debug
log.addDestination(console)
```

**Comment by skreutzberger** [comment]
ah, I found the issue. It is the `$C` and `$c` which does not work under Xcode Console. Please leave it out / remove it and it should work. Color is just possible at the file destination or as emoji in console.
