### ISSUE TITLE
Cannot get the file name on custom format

### ISSUE THREAD

**Issue by pableiros** [SwiftyBeaver/SwiftyBeaver#156]
How can I get the file name within a custom format?

The documentation says this:

    // log everything into a JSON string, including auto-escaped message
    format = "{\"date\": \"$Dyyyy-MM-dd HH:mm:ss.SSS$d\", \"level\": \"$L\", \"message\": \"$m\", \"thread\": \"$T\", \"file\": \"$F\", \"function\": \"$F\", \"line\": $l}"

    // log output:
    {"date":"2016-09-08 10:06:31.113", "level": "VERBOSE", "message": "Hello \"World\"", "thread": "main", "file": "MyViewController", "function": "myFunction()", "line": 123}

But the variable for the `function` and the `file` is the same: `$F`.

**Comment by skreutzberger** [comment]
You are right, it is a mistake in the documentation. It was fixed.

Please replace `\"file\": \"$F\"` with `\"file\": \"$N\"` since `$N`stands for the filename without suffix.
