### ISSUE TITLE
For testing purpose I have to verify the logs through automation

### ISSUE THREAD

**Issue by Prabat** [SwiftyBeaver/SwiftyBeaver#157]
1. I have already integrated the swiftybeaver & saved log to external file
2. using that external file, Verifying the text through regex filters in xcode ui testing.

Using swiftybeaver, Is there any API to get current log text value in xcode ui testing ?

**Comment by skreutzberger** [comment]
Currently SwiftyBeaver does not expose the current log text value. You would need to read the log file. But I generally think the idea is interesting to expose the last log message in a read-only string to the user and will put it on the todo list.

**Comment by skreutzberger** [comment]
added to
