### ISSUE TITLE
Remote logging doesn't seem to work on Linux

### ISSUE THREAD

**Issue by petrpavlik** [SwiftyBeaver/SwiftyBeaver#159]
I did have a quick look at the source code and it looks like you're using `URLSessionDataTask POST`, which is unfortunately broken in Swift foundation implementation  https://lists.swift.org/pipermail/swift-corelibs-dev/Week-of-Mon-20160905/000926.html - It assigns an empty request body. It'll be reportedly fixed in Swift 3.1.

I had experienced the exact same bug and ended up using Vapor's HTTP module for networking instead https://github.com/petrpavlik/PusherNotificationsSwift.

**Comment by skreutzberger** [comment]
Great catch! Can you fix it without imports from Vapor?

**Comment by petrpavlik** [comment]
Well, all these networking modules, including 'URLDataTask', are swifty wrapper around 'libcurl', so you can use it directly if you want zero dependencies.

**Comment by skreutzberger** [comment]
Any interest in contributing it?

**Comment by petrpavlik** [comment]
I with I had time for it. I might fork it and implement the request using Vapor's HTTP module down the road to make it work with my server app.

**Comment by petrpavlik** [comment]
Did you have a chance to try whether this is fixed when compiled with swift 3.0.1?

**Comment by skreutzberger** [comment]
I just released now a new version of SwiftyBeaver supporting Xcode 8.1 and Swift 3.0.1 - can you maybe test it since you seem to already have a test scenario? Thanks!

**Comment by petrpavlik** [comment]
Ok, I'll let you know when Vapor bumps their buildpack to Swift 3.0.1.

**Comment by maciejtrybilo** [comment]
I'm also having trouble on Linux. I've run with the debug flag and got the following: 

`SBPlatform: saving 'Debug!' to <CFURL 0xfb4d00 [0x7f1735bc7840]>{string = file:///var/cache/sbplatform_entries.json, encoding = 0, base = (null)}
SBPlatform: Error! Could not write to file <CFURL 0xfb4d00 [0x7f1735bc7840]>{string = file:///var/cache/sbplatform_entries.json, encoding = 0, base = (null)}.`

I only have a console and cloud destinations.

**Comment by skreutzberger** [comment]
Thanks for diving deeper into the issue. The platform destination needs to write to some buffer files which currently are located at `/var/cache/`. Maybe Swift can not access that folder?

The path is set [here](https://github.com/SwiftyBeaver/SwiftyBeaver/blob/master/sources/SBPlatformDestination.swift#L118) - maybe you can play a bit with it and find a better suited one? We could use maybe home or the current directory where the app maybe actually has write permissions?

**Comment by maciejtrybilo** [comment]
@skreutzberger Why not let the user pass the path in init? The parameter could have a nil default value. I'm using SB with Vapor which has a notion of a working directory, so the Vapor provider could use that? 

I'm happy to make the PRs.

**Comment by skreutzberger** [comment]
I just saw that you can already adjust them at lines [67 and following](https://github.com/SwiftyBeaver/SwiftyBeaver/blob/master/sources/SBPlatformDestination.swift#L67). But since they are already used in init, maybe we can have the `baseURL` as optional parameter of `init` and if it is not nil then it is taken instead of automatically assigned for each operating system? Makes sense?

**Comment by skreutzberger** [comment]
closing for now, will be further investigated with Swift 3.1
