### ISSUE TITLE
Xcode 8.1 warning Expression implicitly coerced from `NSError?` to Any

### ISSUE THREAD

**Issue by MaxHasADHD** [SwiftyBeaver/SwiftyBeaver#160]
Xcode 8.1 has the warning "Expression implicitly coerced from `NSError?` to Any"

**Comment by skreutzberger** [comment]
... checking it out. But firstly, downloading Xcode 8.1 😬

**Comment by skreutzberger** [comment]
I released the new version 1.1.1 just now which was successfully tested under Xcode 8.1
Can you please confirm if it is also working for you? Thanks!

**Comment by MaxHasADHD** [comment]
Nope. Still a ton of warnings for this. Doesn't like optionals anymore. I tried for a second having the functions take `Any?` but it prefaced everything with "optional()" in the log

**Comment by skreutzberger** [comment]
What Swift & SwiftyBeaver version are you using? I do not get any warnings with Xcode 8.1, Swift 3  and SwiftyBeaver 1.1.1
