### ISSUE TITLE
wrap swiftyBeaver behind an interface

### ISSUE THREAD

**Issue by Jackbt** [SwiftyBeaver/SwiftyBeaver#161]
I want to have an interface and wrap swiftyBeaver behind the implementation, but when logging the filename and function name used are the once in the implementation class rather than the service logging. How can i make swiftyBeaver log the filename and function name of the service doing the logging?

**Comment by skreutzberger** [comment]
Sorry for the late reply. 

Can you use the `log.custom()` function? It gives you more flexibility and your interface could add the magic things like `#line`, `#function` and `#file` into it as parameters.

**Comment by skreutzberger** [comment]
When ready, can you point me to your solution? Because I had several users who would like to have an interface-based approach and maybe we can add it into SwiftyBeaver itself.

**Comment by Jackbt** [comment]
Thanks for the reply.

The problem with adding these parameters on the interface is i can't put default parameters on the implementation, and i don't want to pass in these parameters every time i'm logging something. So i would want something like: 
`public func debug(message: String, file:String = #file, function: String = #function, line: Int = #line)`

With this i can just call my logger like: 
`loggingService. debug("Log message")`

and file, function and line are defaulted and are for the service that's logging.

What i ended up doing is remove these function from the interface and have log function
`func log(level: Level, message: String, file: String, function: String, line: Int)`
which then calls [log.custom](https://github.com/SwiftyBeaver/SwiftyBeaver/blob/master/sources/SwiftyBeaver.swift#L117).

Then i added an extension to my interface with debug, info, etc methods and these call log, and have default parameter.
`public func debug(message: String, file:String = #file, function: String = #function, line: Int = #line{
   log(.Debug, message: message, file: file, function: function, line: line)
}`

Because these are extensions to the interface, they are part of the interface even though they are not explicitly on the interface. This is not so great solution, because you can not override these extension methods in your implementation, but there are workarounds for this.

**Comment by skreutzberger** [comment]
what do you think about rewriting SwiftyBeaver’s main logging functions to become an interface?

**Comment by Jackbt** [comment]
I think that would be awesome.

**Comment by skreutzberger** [comment]
It would be awesome if you could contribute it :)  - sounds good? P.S.: you can also join our [Slack channel](slack.swiftybeaver.com/) which makes communication even easier.

**Comment by Jackbt** [comment]
Thats would be great.

**Comment by skreutzberger** [comment]
Perfect, then let's discuss the details on Slack. I can’t wait to have an interface-based SwiftyBeaver 👍

**Comment by Jackbt** [comment]
Im new to Slack channel, but it seems im supposed to be associated with a team, or you need to invite me

**Comment by skreutzberger** [comment]
To join our Slack channel please just enter your email at our [Slack Invite Form](https://slack.swiftybeaver.com). It will add you as free Slack user and send you an email with further details. Thanks & see you there.

**Comment by scottrhoyt** [comment]
FWIW, I too wanted to abstract SwiftyBeaver, but had issues with the interface approach because of the default values for file, line, etc. Instead I settled on just wrapping SwiftyBeaver in a `Logger` struct:

```swift
// This just encapsulates the SwiftyBeaver Logger
struct Logger {
  let cloud: SBPlatformDestination

  init() {
    let console = ConsoleDestination()
    let file = FileDestination()

    cloud = SBPlatformDestination(
      appID: "xxxxxx",
      appSecret: "xxxxxxxxxx",
      encryptionKey: "xxxxxxxxxxxx"
    )

    SwiftyBeaver.addDestination(console)
    SwiftyBeaver.addDestination(file)
    SwiftyBeaver.addDestination(cloud)
    SwiftyBeaver.info("Logging to file: \(file.logFileURL?.path ?? "")")
  }

  func set(username: String) {
    cloud.analyticsUserName = username
  }

  func verbose(
    _ message: @autoclosure () -> Any,
    _ file: String = #file,
    _ function: String = #function,
    _ line: Int = #line
    ) {
    SwiftyBeaver.verbose(message, file, function, line: line)
  }

  func debug(
    _ message: @autoclosure () -> Any,
    _ file: String = #file,
    _ function: String = #function,
    _ line: Int = #line
    ) {
    SwiftyBeaver.debug(message, file, function, line: line)
  }

  func info(
    _ message: @autoclosure () -> Any,
    _ file: String = #file,
    _ function: String = #function,
    _ line: Int = #line
    ) {
    SwiftyBeaver.info(message, file, function, line: line)
  }

  func warning(
    _ message: @autoclosure () -> Any,
    _ file: String = #file,
    _ function: String = #function,
    _ line: Int = #line
    ) {
    SwiftyBeaver.warning(message, file, function, line: line)
  }

  func error(
    _ message: @autoclosure () -> Any,
    _ file: String = #file,
    _ function: String = #function,
    _ line: Int = #line
    ) {
    SwiftyBeaver.error(message, file, function, line: line)
  }
}

let log = Logger()
```

Then in my code, I use it as such:

```swift
log.info("some info")
log.error("an error")
```

While perhaps not as elegant as creating an interface, this does serve my purposes of abstracting SwiftyBeaver.

**Comment by skreutzberger** [comment]
Closing for now until someone adds a PR which introduces an interface 😬

**Comment by Darwex** [comment]
The approach above by scottrhoyt, with the struct, also works with Protocol and Class when functions are static and so you do not need instance, it is a little bit cleaner I would say.

```
protocol LoggerServiceType {
    static func setUpLogger(isEmulator: Bool)
    static func verbose(_ message: Any, _ file: String, _ function: String, line: Int)
    static func debug(_ message: Any, _ file: String, _ function: String, line: Int)
    static func info(_ message: Any, _ file: String, _ function: String, line: Int)
    static func warning(_ message: Any, _ file: String, _ function: String, line: Int)
    static func error(_ message: Any, _ file: String, _ function: String, line: Int)
}

class LoggerService: LoggerServiceType {
    private static let loggerLibrary = SwiftyBeaver.self

    static func verbose(_ message: Any, _ file: String = #file, _ function: String = #function, line: Int = #line) {
        loggerLibrary.verbose(message, file, function, line: line)
    }

    static func debug(_ message: Any, _ file: String = #file, _ function: String = #function, line: Int = #line) {
        loggerLibrary.debug(message, file, function, line: line)
    }

    static func info(_ message: Any, _ file: String = #file, _ function: String = #function, line: Int = #line) {
        loggerLibrary.info(message, file, function, line: line)
    }

    static func warning(_ message: Any, _ file: String = #file, _ function: String = #function, line: Int = #line) {
        loggerLibrary.warning(message, file, function, line: line)
    }

    static func error(_ message: Any, _ file: String = #file, _ function: String = #function, line: Int = #line) {
        loggerLibrary.error(message, file, function, line: line)
    }
}
```
