### ISSUE TITLE
I want to know how can set to look like this?   please，thank you very match

### ISSUE THREAD

**Issue by baobao57** [SwiftyBeaver/SwiftyBeaver#166]
This is the style I have seen in other places, and indicate with swiftybehavior library.
<img width="637" alt="1464535569601_51" src="https://cloud.githubusercontent.com/assets/12264243/21211046/0ed168c4-c2bb-11e6-9191-b0396976f236.png">

**Comment by skreutzberger** [comment]
That style is the default look in Xcode.

**Comment by baobao57** [comment]
This would be to use XcodeColors plug-in, now is to have a better way to solve it?On the network **'update_xcode_plugins'** I've tried this method.Does not solve the problem,As a result, I need to download the Xcode again.
Whether apple is the key to the solution we can't better solve him?After all, he was not update time is not long.
Please forgive my English is not good, I am a Chinese and contact ios development soon
