### ISSUE TITLE
Filter the console breaks the lines

### ISSUE THREAD

**Issue by tunidev** [SwiftyBeaver/SwiftyBeaver#168]
I have other SDK integrated in my project they have also some debug messages printed to console, I want to just see the output of SwiftBeaver in the console when debugging my code so I tried to filter with 💚 but the result was that the lines are not respected like in the image:

<img width="1161" alt="screen shot 2016-12-27 at 01 32 35" src="https://cloud.githubusercontent.com/assets/4885143/21487827/47f14e1c-cbd5-11e6-9b88-a78a8eb74dfc.png">

**Comment by skreutzberger** [comment]
Xcode’s own console filtering seems to break lines. Maybe just use SwiftyBeaver :)

**Comment by tunidev** [comment]
> Maybe just use SwiftyBeaver 
Yes, I am using SwiftyBeaver, but in the console there other output from other SKD's that I am using. AT some point I am to see only SwiftyBeaver output any alternative to the Xcode console filtering ?
