### ISSUE TITLE
Xcode 8 colored text

### ISSUE THREAD

**Issue by Ekhoo** [SwiftyBeaver/SwiftyBeaver#170]
So if I understand, we cannot have colored text with XCode 8 console ? We can only have emoji ? :(

**Comment by skreutzberger** [comment]
unfortunately yes because Apple removed the support for external console-coloring libraries.

**Comment by sishenyihuba** [comment]
Please update the ReadMe on homePage. Many people do not know it and waste many time to find what is up!
