### ISSUE TITLE
Accessing logger from multiple classes

### ISSUE THREAD

**Issue by o15a3d4l11s2** [SwiftyBeaver/SwiftyBeaver#173]
Is there an easy way to create a single logger for the whole app and access it from any class?

The examples are all with the "log" instance, which comes from the AppDelegate.

**Comment by skreutzberger** [comment]
If you add the log variable on top of your AppDelegate then it is global and available throughout your whole app. In case if not then inject it into your class as property. But normally it should automatically work if you define the log variable globally.
