### ISSUE TITLE
File output format defaulting to JSON, not custom format string

### ISSUE THREAD

**Issue by aottenwess** [SwiftyBeaver/SwiftyBeaver#195]
I formatted my `console` and `file` to have the same format. The `console` output is rendering as expected, but the `file` output is in JSON format, even though I did not specify that . Here is my code:
```

let log = SwiftyBeaver.self
let console = ConsoleDestination()  // log to Xcode Console
let file = FileDestination() // log to default Swifty Beaver file
let defaultFormat = "$DHH:mm:ss$d $C$L$c $N.$F:$l -> $M"
        console.format = defaultFormat
        file.format = defaultFormat
        file.logFileURL = URL(fileURLWithPath: "/Documents/swiftybeaver.log")
        log.addDestination(self.console)
        log.addDestination(self.file)
log.verbose("testing for file")
```

and the file output looks like:
```
{"thread":"","fileName":"AppDelegate.swift","level":0,"timestamp":1489092082.609496,"message":"testing for file","function":"application()","line":34}
```

Using Swift 3, built on iOS 10

**Comment by skreutzberger** [comment]
I could not reproduce the behavior using your example. 

A note:
I actually had to replace `self.console` with `console` and `self.file` with `file` to make your example compile but maybe your lines 5-9 are in a method.
