### ISSUE TITLE
Huge log size

### ISSUE THREAD

**Issue by brycesteve** [SwiftyBeaver/SwiftyBeaver#196]
I use SwiftyBeaver for debugging and it works extremely well on the whole. I tried the cloud platform however, and that led to strange issues. I finally narrowed down the root of the weirdness. The file sbplatform_entries.json seemed to be ever expanding. After a few days of debugging and testing, the json file managed to grow to 2GB in size. I generally only use this for console debugging, so I removed the SBPlatformDestination from my code, and no more problem.  Just thought it might be worth looking into in case anyone else has this problem.

**Comment by skreutzberger** [comment]
Thanks for reporting!

The `sbplatform_entries.json` can get large if the device is not connected to the internet. It is recommended to log less / with a higher minimum log level to the cloud to avoid a constant sending of logs from a user’s device or a filling up of that buffer file if the user does not have an internet connection.

We already discussed some potential solutions on how to avoid that the file gets huge if sending does not work on the Slack channel and we may implement it in one of that next versions.

For now you can safely delete the 2 GB file `sbplatform_entries.json` on your test device.
