### ISSUE TITLE
Format for Cloud

### ISSUE THREAD

**Issue by o15a3d4l11s2** [SwiftyBeaver/SwiftyBeaver#197]
Is it possible to change the formatting of logs for the Cloud Platform?
I have set the same format for the Console and Cloud, but it is applied to the Console only.

**Comment by skreutzberger** [comment]
That is not possible. The cloud platform uses its own internal JSON structure for an easier processing by client apps like the SwiftyBeaver Mac App. 

Good to know:
The JSON logging object is actually very similar to the one you would get if you set the format to `"$J"`.
