### ISSUE TITLE
Support for Swift 3.1

### ISSUE THREAD

**Issue by Mackarous** [SwiftyBeaver/SwiftyBeaver#202]
Hey guys, wondering what your timeline is for Swift 3.1

**Comment by skreutzberger** [comment]
SwiftyBeaver is supporting Swift 3.1 already since the first Swift 3.1 beta. We are using SwiftyBeaver heavily on the server-side which (unfortunately?) always needs to use the latest Swift betas so you can be sure that SwiftyBeaver itself is always supporting the latest & greatest 😀
