### ISSUE TITLE
Unable to use inbuilt natural logarithm function in a Swift iOS Project if I import SwiftyBeaver in that project

### ISSUE THREAD

**Issue by nikhilpandey4** [SwiftyBeaver/SwiftyBeaver#211]
Hi,
There is a strange and an extremely odd error , which Swifty Beaver developer should have checked before. In any of my iOS Swift projects if I import SwiftyBeaver  I encounter an error when every time I try to use the inbuilt mathematical function to find natural logarithm of a number, i.e., logarithm to the base e . 

>Finally I found the reason , which is,  the inbuilt swift mathematical function to find natural logarithm is log which is in conflict with the SwiftyBeaver log function as both have the same name and Swift does not support namedspaces like C++.

The error which Xcode shows is **"Cannot invoke 'log' with an argument list of type '(Double)'".**  The moment I delete SwiftyBeaver library from the project the error disappears.  Developers of SwifyBeaver should change the name of log to something else like SBlog so as to avoid conflict with the inbuilt natural logarithm function.

**Comment by skreutzberger** [comment]
Yes, that is a known issue and is at 99% not an issue at all since most developers do not use the mathematical logarithm function in their projects. If  you are using the mathematical logarithm function then please name your SwiftyBeaver instance differently. Maybe `logger` or `sb` or so. That should fix the issue.

**Comment by nikhilpandey4** [comment]
Can you please provide an example how to use the logger function or just as you have told I should change the following line declared in Appdelegate .swift file 
`let log = SwiftyBeaver.self`

to 
`**let logger = SwiftyBeaver.self**`

**Comment by skreutzberger** [comment]
yes, I meant your line :)

**Comment by nikhilpandey4** [comment]
Its hard to say that  most developers do not use the mathematical logarithm function in their projects as almost all algorithm from image search to filtering to anything will use natural logarithm and the developer may have used 3rd party library, where the conflict will arise.

**Comment by skreutzberger** [comment]
You are right. My statement was based on user feedback and generally reported issues. It is just the 2nd time I am reading about that naming clash with having 2m+ users already using SwiftyBeaver.

**Comment by nikhilpandey4** [comment]
Its hard to say that  most developers do not use the mathematical logarithm function in their projects as almost all algorithm from image search to filtering to anything will use natural logarithm and the developer may have used 3rd party library, where the conflict will arise.

**Comment by nikhilpandey4** [comment]
Ok,
Then as a developer I am curious that given the situation and pitfalls ahead (lot of unknown unknowns) doesn't it make sense to follow apple's earlier advice of having unique identifiers of size of 3 letters or more for each class or function. I agree with simplicity of having simple names but conflict with inbuilt methods may be a bigger issue.
