### ISSUE TITLE
Something weird in log message

### ISSUE THREAD

**Issue by chizcake** [SwiftyBeaver/SwiftyBeaver#213]
![2017-04-21 20 39 44](https://cloud.githubusercontent.com/assets/8370459/25276205/f3bdfdf4-26d3-11e7-9047-f14e52654f20.png)

As the above image, there's an weird characters (\360\237\222) in log messages.
When this characters appear in some cases?

**Comment by skreutzberger** [comment]
Some other users also reported that broken output some months ago. It seems to appear without any pattern and is caused by a buggy rendering of Emojis in Xcode.
