### ISSUE TITLE
Colors don't work?

### ISSUE THREAD

**Issue by rlam3** [SwiftyBeaver/SwiftyBeaver#222]
Colors don't work?
I'm on 8.3.2 Xcode and Swift 3

**Comment by skreutzberger** [comment]
Since Xcode 8 colors in Xcode‘s own console do not work anymore. Apple did unfortunately remove that feature. Colors still do work if you log to a file using the file destination and your Mac’s Terminal.app

**Comment by rlam3** [comment]
@skreutzberger Thanks for letting me know. Do you think we should add it as a note into the repo README.md for others? How do I get it to work through my Mac Terminal? I'm having difficulty in locating the .log file. An example here would be much appreciated. Thank you!

**Comment by skreutzberger** [comment]
There is already a note in README about coloring and what to do under Xcode 8. 

For the file destination you select a file where you want to store your logs. In macOS Terminal.app you write `tail -f YOUR_LOG_FILE` to see the contents of the file once it has some log entries. 

You can also use the platform destination together with the SwiftyBeaver Mac App, that is the easiest way of doing it :)
