### ISSUE TITLE
Local logging with Mac App

### ISSUE THREAD

**Issue by yonaskolb** [SwiftyBeaver/SwiftyBeaver#223]
Is it possible to log locally, probably to a file, and for the Mac app to read it? If not that would be great. Having a high throughput of dev logs makes the filtering off the Mac app useful, but not necessarily for sending to the platform

**Comment by skreutzberger** [comment]
Currently that is not possible but it was already mentioned already multiple times as a great potential feature. Let me think it more through and maybe we can come up with something :)
