### ISSUE TITLE
Can not signup with Mac app

### ISSUE THREAD

**Issue by peterfennema** [SwiftyBeaver/SwiftyBeaver#226]
Tried to sign up with mac app using email of format xxx@yyy.nl
Error message: some fields are invalid  
(or something similar)

Tried using another email address of format zzz@gmail.com
Everything works fine.

In both cases I used the same password.

macOS Sierra 10.12.4 
SwiftyBeaver 1.1.0(1100)

For me the issue is solved, I'm fine with the gmail.com account.
Just thought I'd let you know.

**Comment by skreutzberger** [comment]
thanks, I put it on the list!
