### ISSUE TITLE
Custom log file url does not work.

### ISSUE THREAD

**Issue by haithngn** [SwiftyBeaver/SwiftyBeaver#227]
I want to write to log into the Documents/Logs directory so here are my implementation code:
`if let desFile = logFile {
            let documentsPath = NSSearchPathForDirectoriesInDomains(.documentDirectory, .userDomainMask, true)[0]
            let logDir = documentsPath.appending("/Logs")

            if FileManager.default.fileExists(atPath: logDir) == false {
                do {
                    try FileManager.default.createDirectory(atPath: logDir, withIntermediateDirectories: true,
                            attributes: nil)
                } catch let exception {
                    debugPrint("Cannot create Logs Directory")
                }
            }

            let filePath = logDir.appending("/swiftybeaver.log")
            debugPrint("filePath \(filePath)")

            let file: FileDestination = FileDestination()
            file.logFileURL = URL(string: filePath)
            file.minLevel = .verbose

            beaver.addDestination(file)
        }`

The directory was existing but SwiftyBeaver said
SwiftyBeaver File Destination could not write to file /Users/hainguyen/Library/Developer/CoreSimulator/Devices/4BEAB7C7-916E-447A-9F40-F617020D4147/data/Containers/Data/Appli ... aver.log.

**Comment by skreutzberger** [comment]
I recommend not changing the folders on the iPhone since iOS is very delicate with folders and permissions. Can you manually create a file in that folder as test?

**Comment by haithngn** [comment]
sure I created a folder "Logs" and put some files on it by using FileManager.

**Comment by skreutzberger** [comment]
I don’t see why it does not work. Here is the function where the destination tries to write to that folder: https://github.com/SwiftyBeaver/SwiftyBeaver/blob/master/Sources/FileDestination.swift#L87

**Comment by stami** [comment]
@haithngnbak Your file URL is wrong.

If you `print` the default `.logFileURL` and that your created url, you see that your url is missing `file://` from the beginning of it.

I managed to write the logs to _Documents_ directory with `FileManager` API like following:

``` swift
let file = FileDestination()

let url = try? FileManager.default.url(for: .documentDirectory,
                                       in: .userDomainMask,
                                       appropriateFor: nil,
                                       create: true)

let fileURL = url?.appendingPathComponent("debug.log")

file.logFileURL = fileURL

log.addDestination(file)
```

Hope this helps!

**Comment by i-schuetz** [comment]
@stami isn't that inconvenient? The path changes on every install...

**Comment by i-schuetz** [comment]
Is there a way to prevent the path changing on every install (because of the changing application folder)...?

**Comment by stami** [comment]
Why is that an issue? With using FileManager API, I can write the logs to Documents folder so that they can be retrieved through iTunes file sharing feature.

**Comment by i-schuetz** [comment]
I just want to show the contents of the file in a logger, for which I need the path... but this changes every time the app is re-started in the simulator. So basically each time the path has to be updated in the logger... not sure how what you're writing addresses this? Probably I'm missing something?
