### ISSUE TITLE
uninstall issues

### ISSUE THREAD

**Issue by kreativecoding** [SwiftyBeaver/SwiftyBeaver#228]
uninstalling the plugin from cocoapods gives me these issues.
How can i solve them?

thank you

![snip20170523_2](https://cloud.githubusercontent.com/assets/10559075/26375704/422029c8-400a-11e7-824f-ff852a70daee.png)

**Comment by skreutzberger** [comment]
It seems you also need to delete the files from the Xcode project and/or the build steps.

**Comment by kreativecoding** [comment]
i didn't find how to do that. all files are deleted from the project. i imagine i need to remove them from the build steps but can't seem to find how to do that....

**Comment by kreativecoding** [comment]
nevermind. i fixed it. thank you for the response
