### ISSUE TITLE
Any support for Swift 4 ?

### ISSUE THREAD

**Issue by XBeg9** [SwiftyBeaver/SwiftyBeaver#235]

**Comment by skreutzberger** [comment]
Actually it should already work out-of-the box with Swift 4 as far as I undestand the release process. Do we need to change something in the framework to make it ready for Swift 4 but still stay compatible to Swift 3?

**Comment by katunch** [comment]
SwiftyBeaver is not compatible to Swift 4 out of the box.. see this screenshot
![screen shot 2017-06-27 at 16 07 10](https://user-images.githubusercontent.com/1769636/27591702-c586d42a-5b52-11e7-83cf-10e0b393088d.png)

**Comment by skreutzberger** [comment]
I looked deeper into it and the multi-targeted, backward-compatible compilation of Swift 3 & 4 is really just possible in Xcode 9. So I think we should wait until Xcode 9 is officially released and then we can do add the support to Xcode 4. 

I want to avoid that we have again multiple branches supporting multiple Swift versions like we had from Swift 2 - 3. So when Xcode 9 is out SwiftyBeaver will automatically support Swift 3.1 & 4. Swift 2 will still be supported via a special version tag.

**Comment by jshier** [comment]
A hybrid approach is possible with the use of `#if swift(>3.2)` checks and such, as SwiftyBeaver currently compiles under Swift 3.2 just fine. However, if the hybridization would be too much work, I understand. I was easy to make Alamofire a hybrid, but it seems like you may have some more detailed work to do.

**Comment by tonyarnold** [comment]
> So when Xcode 9 is out SwiftyBeaver will automatically support Swift 3.1 & 4.

Please reconsider.

Plenty of us need to work with Xcode 9 _now_ so that we're ready for iOS 11 and macOS 10.13, not when it's officially out. 

Taking this approach will mean that we have to remove SwiftyBeaver from our projects.

**Comment by skreutzberger** [comment]
Any pull request is welcomed which adds support for Swift 4 already in advance. Please just make sure to keep backward compatibility to Swift 3.

**Comment by skreutzberger** [comment]
Guys, please check Laurent’s pull request which adds Swift 3 and 4 compatibility. It looks good from our side. Due to strong impact we give it one more week until it is merged into master and released as new major version. 

In the meantime, please test out Laurent’s pull request to see if it is working for you and please report back in the PR or here if it is working with your Swift 4 code or not.

Thanks @lgaches and all involved helping to test Swft 3.2 and 4 support 🙏

**Comment by tonyarnold** [comment]
The changes in @lgaches fork worked for me under Xcode 9.0 beta 5. Thanks!

**Comment by katunch** [comment]
Same here: Checked out @lgaches fork and worked for me as well under Xcode 9 beta 5. Many Thanks!
