### ISSUE TITLE
Is global variable 'log' a really nice practice?

### ISSUE THREAD

**Issue by psi-gh** [SwiftyBeaver/SwiftyBeaver#243]
In all examples you have
`let log = SwiftyBeaver.self`
in `AppDelegate`. But common practice is to avoid to have global variables in code because it ties program components and makes them not isolated.
Do you recommend use it this way?

**Comment by skreutzberger** [comment]
Yes it is recommended to use it in that way for the sake of simplicity. But if you are concerned or you actually need to use the logarithm functionality in your source code then feel free to either name the constant differently or/and have individual logging instances inside your classes.
