### ISSUE TITLE
Still getting errors in Swift 4

### ISSUE THREAD

**Issue by thankmelater23** [SwiftyBeaver/SwiftyBeaver#245]
Getting 18 errrors all from the "AES256CBC.swift" file.  Complexity errors and stuff.

**Comment by skreutzberger** [comment]
what is your `SwiftyBeaver.version`? CocoaPods is not serving 1.4.0

**Comment by serendipityapps** [comment]
I'm also seeing complexity errors in AES256CBC.swift - Xcode 9 Beta 5.  SwiftyBeaver version 1.3.0 as served by Cocoapods.  Compiling with swift 3.2.
<img width="1258" alt="screen shot 2017-08-14 at 13 01 35" src="https://user-images.githubusercontent.com/358528/29270936-f5e40430-80f0-11e7-9cca-5c512ce9e9c4.png">

**Comment by skreutzberger** [comment]
Please use Carthage or SPM to get access to the latest SwiftyBeaver 1.4.0 which is solving the issue.

**Comment by noremac** [comment]
I'm using this line in my `Podfile` which is fine but not ideal.

`pod 'SwiftyBeaver', :git => 'git@github.com:/SwiftyBeaver/SwiftyBeaver.git', :tag => '1.4.0'`

What's the reason behind not serving 1.4 through CocoaPods? Is there an issue right now, or some other decision at play?

**Comment by skreutzberger** [comment]
Currently CocoaPods is not working with Xcode 9 beta and also has issues with Swift 4. That's why we decided to stop supporting CocoaPods until these issues are resolved. In best case we completely stop supporting CocoaPods since it is really administratively complicated and error-prone.

**Comment by thankmelater23** [comment]
Ok so when could we expect it to work with cocoapods? Or can't tell until cocoapods issue is fixed?

**Comment by skreutzberger** [comment]
I am more than happy to announce that the issue with CocoaPods could be resolved (after some lost nerves and added grey hairs) and  SwiftyBeaver 1.4.0 is now also available at CocoaPods. Please try it out and report any issues. Thanks!


Good to know: CocoaPods is still subject to deprecation and a switch to our Carthage or SPM packages is recommended to stay on the safe side also for future updates.

**Comment by thankmelater23** [comment]
Hey up and running here.  Even the logger is workig fine.  Thanks!

**Comment by skreutzberger** [comment]
woohoo, thank for the feedback!
