### ISSUE TITLE
1.4 Broken in Swift 4.

### ISSUE THREAD

**Issue by Sajjon** [SwiftyBeaver/SwiftyBeaver#248]
Using version `1.4` with Xcode 9 and Swift does not work. 

Just clone master branch and change Swift version from `3.2` to `4.0` and you will get this error.

`Argument labels '(truncatingIfNeeded:)' do not match any available overloads` inside file `AES256CBC.swift`, line 567:
```swift
#if swift(>=4.0)
                p = p ^ (UInt8(truncatingIfNeeded: Int(p) << 1) ^ ((p & 0x80) == 0x80 ? 0x1B : 0))
```

and also error `Non-nominal type 'T' does not support explicit initialization` inside the same file, caused by line 785:
`return T(truncatingIfNeeded: UInt64(bytes[0]))`

<img width="828" alt="screen shot 2017-08-28 at 16 23 30" src="https://user-images.githubusercontent.com/864410/29777733-4c620d12-8c0d-11e7-8b9d-18458491c33f.png">

**Comment by Sajjon** [comment]
I actually got it working using tag `1.3.2`, so in my `Podfile` I use:
```ruby
  pod 'SwiftyBeaver', :git => 'https://github.com/SwiftyBeaver/SwiftyBeaver.git', :tag => '1.3.2'
```

In combination with this `post_install`:
```ruby
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
    	config.build_settings['SWIFT_VERSION'] = 3.2
    end
  end
end

```

**Comment by skreutzberger** [comment]
The version 1.4.0 should work under Xcode 9 beta 5 and beta 6. What Xcode 9 are you testing?

**Comment by Sajjon** [comment]
@skreutzberger my bad, I was using `Version 9.0 beta 4 (9M189t)`, sorry!

**Comment by Sajjon** [comment]
Closing issue now....

**Comment by skreutzberger** [comment]
Alright, I already thought we missed a small thing 😅
