### ISSUE TITLE
Log color is B&W and cannot write log to local file in XCode 9 beta 6. 

### ISSUE THREAD

**Issue by YoungxHelsinki** [SwiftyBeaver/SwiftyBeaver#250]
I'm building an iOS 11 beta app and debugging on a **physical** machine.

## Environment
Xcode 9 beta 6
SwiftyBeaver 1.4.0

## SwiftyBeaver setup
```swift
// AppDelegate.swift
import UIKit
import SwiftyBeaver
let log = SwiftyBeaver.self

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {

	var window: UIWindow?

	// Nothing to do here. See ViewController for primary app features.
    
    func applicationDidFinishLaunching(_ application: UIApplication) {
        // add log destinations. at least one is needed!
        let console = ConsoleDestination()  // log to Xcode Console
        let file = FileDestination()  // log to default swiftybeaver.log file
        file.logFileURL = URL(fileURLWithPath: "/tmp/swiftybeaver.log")
        file.minLevel = SwiftyBeaver.Level.verbose
        
        // use custom format and set console output to short time, log level & message
        console.format = "$DHH:mm:ss$d $L $M"
        // or use this for JSON output: console.format = "$J"
        
        // add the destinations to SwiftyBeaver
        log.addDestination(console)
        log.addDestination(file)
    }
}



```

## Problem
1. Console logs are B&W.
2. Logging to a Mac disk(/tmp/swiftybeaver.log) doesn't work
	- `SwiftyBeaver File Destination could not write to file file:///tmp/swiftybeaver.log.`

I assume `file:///tmp/swiftybeaver.log.` is not a Mac url?
Thanks.

**Comment by skreutzberger** [comment]
The console logs are black & white because Xcode does not support colored lines anymore since Xcode 8. The file destination does not really work if used on iOS or the iPhone Simulator with the inaccessible file systems for outside clients like Terminal App. 

The file destination fits better if you are buillding a macOS app or a server-side Swift app.

**Comment by YoungxHelsinki** [comment]
Isn't your [doc](http://docs.swiftybeaver.com/article/9-log-to-xcode-console) misleading about coloring then?

**Comment by skreutzberger** [comment]
You are right, we actually introduced the emojis as something like a fake color since the true color is not working anymore in newer Xcodes. I will think about a different, more precise wording 👍

**Comment by agordeev** [comment]
@skreutzberger I followed Install instructions, but I still can't see emojis on my Xcode output. The output is:

15:44:40 VERBOSE not so important
15:44:40 DEBUG something to debug
15:44:40 INFO a nice information
15:44:40 WARNING oh no, that won’t be good
15:44:40 ERROR ouch, an error did occur!

**Comment by skreutzberger** [comment]
What Xcode version and SwiftyBeaver version are you using?

**Comment by agordeev** [comment]
Latest. Fixed that by removing custom format by the way.

**Comment by Rachit150** [comment]
hiii , 
for Swifty Beaver , logs are not seen in console
