### ISSUE TITLE
Xcode 9 Beta 6 SwiftyBeaver Won't Compile

### ISSUE THREAD

**Issue by iJasonWade** [SwiftyBeaver/SwiftyBeaver#251]
When compiling against Xcode 9 Beta 6 I receive the following errors:

<img width="1440" alt="screen shot 2017-09-09 at 10 19 16 pm" src="https://user-images.githubusercontent.com/12824479/30245875-31c4cd60-95ad-11e7-9254-765eb187a547.png">

**Comment by lgaches** [comment]
@iJasonWade This issue is resolved in 1.4.0 version.

**Comment by iJasonWade** [comment]
@lgaches, I was using SBObjectiveCWrapper which apparently is using the old version of SwiftyBeaver, I have manually imported the SBObjectiveCWrapper classes and upgraded SwiftyBeaver through Cocoapods and it is working now.
