### ISSUE TITLE
Xcode9 build issue

### ISSUE THREAD

**Issue by crspybits** [SwiftyBeaver/SwiftyBeaver#253]
With Xcode9 GM Seed, when building one of my test cases for the simulator, I'm getting:

> Undefined symbols for architecture x86_64:
>   "__T012SwiftyBeaverAAC5debugyypyXK_S2SSi4lineypSg7contexttFZfA3_", referenced from:
>       __T016IntegrationTests22ServerAPIUpdateProfileC010testUpdateE21WorksWithOneJobTypeIdyyF in ServerAPIUpdateProfile.o
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

This is using the latest SwiftyBeaver as of today.

**Comment by crspybits** [comment]
Interesting. I had a simple Log usage:

    Log.error("...")

and this is what was causing the link failure. I was not doing an explicit `import SwiftyBeaver` with Xcode8 (I had just been importing the module which had the Log variable defined), but that seems needed now and resolved the above issue.

**Comment by skreutzberger** [comment]
Thanks for the info!
