### ISSUE TITLE
Xcode 9: "No such module 'SwiftyBeaver'

### ISSUE THREAD

**Issue by rlaferla** [SwiftyBeaver/SwiftyBeaver#256]
Using 1.4.1 via CocoaPods, my project no longer builds with Xcode 9.

```
pod install
Analyzing dependencies
Downloading dependencies
Installing SwiftyBeaver (1.4.1)
```

**Comment by skreutzberger** [comment]
Maybe that is helping? Other users who used the latest version of Xcode 9, Cocoapods and SwiftyBeaver reported in that all things are working, hmm.

https://twitter.com/johnsundell/status/910538432451170305
