### ISSUE TITLE
Memory leak on sendToServerAsync

### ISSUE THREAD

**Issue by drougojrom** [SwiftyBeaver/SwiftyBeaver#257]
Found a memory leak on sendToServerAsync method, swift 4, Xcode 9.

<img width="925" alt="screen shot 2017-09-25 at 2 43 14 pm" src="https://user-images.githubusercontent.com/16073082/30808852-02c54af8-a200-11e7-9740-0f5c3ab55efb.png">
<img width="597" alt="screen shot 2017-09-25 at 2 43 29 pm" src="https://user-images.githubusercontent.com/16073082/30808855-0631e232-a200-11e7-8e0c-28597a3daf4c.png">
<img width="1034" alt="screen shot 2017-09-25 at 2 43 46 pm" src="https://user-images.githubusercontent.com/16073082/30808861-0ab266ba-a200-11e7-8851-e2dd7c24c26a.png">

**Comment by skreutzberger** [comment]
Great catch! Do you know how to fix it?

**Comment by drougojrom** [comment]
According to [URLSession docs](https://developer.apple.com/documentation/foundation/urlsession), session keeps a strong reference to delegate until the app exists, so in order to prevent a leak you should call `session.finishTasksAndInvalidate()` after `task.resume()` .

Checked in my project, leak closed. I'll send a PR.

**Comment by skreutzberger** [comment]
The new release SwiftyBeaver 1.4.2 includes the pull request as fix. The memory leak should be closed.
