### ISSUE TITLE
Replace NSUUID with UUID

### ISSUE THREAD

**Issue by neoneye** [SwiftyBeaver/SwiftyBeaver#261]
When I'm deploying my server code to Heroku, then I'm getting an error about missing `uuid.h`.

```
remote: Compile LinuxBridge LinuxBridge.c
remote: Compile COpenSSL openssl.c
remote: Compile Swift Module 'SwiftyJSON' (2 sources)
remote: Compile Swift Module 'SwiftyBeaver' (9 sources)
remote: In file included from /tmp/build_a1e7028c6ea76e143cbd4767aa4291bd/.build/checkouts/Perfect-LinuxBridge.git--7502201521102328640/LinuxBridge/LinuxBridge.c:2:
remote: /tmp/build_a1e7028c6ea76e143cbd4767aa4291bd/.build/checkouts/Perfect-LinuxBridge.git--7502201521102328640/LinuxBridge/include/LinuxBridge.h:6:10: fatal error: 'uuid/uuid.h' file not found
remote: #include <uuid/uuid.h>
remote:          ^
remote: 1 error generated.
```

It may be an issue with [Perfect-LinuxBridge](https://github.com/PerfectlySoft/Perfect-LinuxBridge/blob/master/LinuxBridge/include/LinuxBridge.h)

I took a closer look at [SBPlatformDestination](https://github.com/SwiftyBeaver/SwiftyBeaver/blob/master/Sources/SBPlatformDestination.swift). Here `NSUUID` is used. I would expect `UUID` being used.

**Proposed solution**
Change from `NSUUID` to `UUID`.

**My setup**
- Xcode 9.0 (9A235)
- macOS Sierra 10.12.6 (16G29)
- SwiftyBeaver 1.4.2

Anyways this probably doesn't solve my issue.

**Comment by skreutzberger** [comment]
Does it solve your issue? We used NSUUID because some things were not ported correctly. The latest SwiftyBeaver is working fine with Kitura so maybe the issue is more on the Perfect side?

**Comment by neoneye** [comment]
yes, I don't think it has to do with SwiftyBeaver. Thank you for this great framework.

I think it has something to do with [Perfect running on Heroku](https://github.com/PerfectlySoft/Perfect-Heroku-Buildpack/blob/master/rage.txt).
Next weekend I will investigate deploying to AWS to see if uuid things compiles better.
