### ISSUE TITLE
Logging to the macOS app and cloud

### ISSUE THREAD

**Issue by maciekish** [SwiftyBeaver/SwiftyBeaver#264]
I just added SwiftyBeaver to my project and i can log to the console but the macOS app does absolutely nothing. The documentation is unclear about how to show logs in the macOS app and where to get my secret for cloud logging.

**Comment by skreutzberger** [comment]
Please download the app, create a free account and app credentials. Then you can use these app credentials in the platform destination of the framework. Please read here to learn more http://docs.swiftybeaver.com/article/11-log-to-swiftybeaver-platform
