### ISSUE TITLE
How to set log level for file?

### ISSUE THREAD

**Issue by psi-gh** [SwiftyBeaver/SwiftyBeaver#268]
For example, I want to see only "errors" from one of my classes. Can't figure out how to set up filters for this. Thanks.

**Comment by skreutzberger** [comment]
Did you see this page? http://docs.swiftybeaver.com/article/21-filters

**Comment by psi-gh** [comment]
Yes. I played with some variations of Filter.Path.excludes/contains and i can't achieve result with it. I'm either turning off all logs or turning on all logs. Maybe I'm doing something extremely wrong :)
For example, I have class NetworkWorker (in separate file). Which filter I had to create to show only 'error' messages within this class, and all level messages within other classes?

**Comment by skreutzberger** [comment]
how do the surrounding destination properties look?

**Comment by psi-gh** [comment]
Like this (changed names of classes due to simplicity )
`        console.minLevel = .debug
        SwiftyBeaver.addDestination(console)
        console.addFilter(Filters.Path.excludes("SomeLongClassName"))
        console.addFilter(Filters.Path.contains("NetworkWorker", minLevel: .error))
        console.addFilter(Filters.Path.excludes("AnotherLongClassName"))`

**Comment by skreutzberger** [comment]
closing it for now. we need to generally redesign filters to make them easier to use.

**Comment by psi-gh** [comment]
Okay, I will wait for it!
