### ISSUE TITLE
I can't print variables using context

### ISSUE THREAD

**Issue by junweimah** [SwiftyBeaver/SwiftyBeaver#278]
Hi, thanks for the library

I can successfully print message but the variable is not printing out

This is my code to log: 

```
        let asd = 123
        let qwe = "qwe"
        logging.error("this is error")
        logging.debug("this is debug: ", context: asd)
        logging.error("error: ", context: qwe)
        logging.debug("Message 3", context: " yeah!")
```

This is my console: 

![image](https://user-images.githubusercontent.com/21700014/35502565-56944492-0518-11e8-8dd0-bd390bfac594.png)

The variable I passed to context is not showing up in the console, what am I doing wrong?

Thanks

**Comment by skreutzberger** [comment]
sorry for the late reply. Please add the `$X` to the format. On default the context is not added to the output. Please see here to learn more about it: http://docs.swiftybeaver.com/article/20-custom-format

**Comment by junweimah** [comment]
That's it, thanks!
