### ISSUE TITLE
crash at destinations.removeAll()

### ISSUE THREAD

**Issue by krmao** [SwiftyBeaver/SwiftyBeaver#279]
### crashed at destinations.removeAll()
Thread 9: EXC_BAD_ACCESS (code=EXC_I386_GPFLT)
```
    /// if you need to start fresh
    open class func removeAllDestinations() {
        destinations.removeAll()
    }
```

### crashed at if destinations.contains(destination) 
Thread 9: EXC_BAD_ACCESS (code=EXC_I386_GPFLT)
```
    /// returns boolean about success
    @discardableResult
    open class func addDestination(_ destination: BaseDestination) -> Bool {
        if destinations.contains(destination) {
            return false
        }
        destinations.insert(destination)
        return true
    }
```

### crashed at f += "()"  
Thread 8: EXC_BAD_ACCESS (code=1, address=0xa)
```
    /// removes the parameters from a function because it looks weird with a single param
    class func stripParams(function: String) -> String {
        var f = function
        if let indexOfBrace = f.find("(") {
            #if swift(>=4.0)
            f = String(f[..<indexOfBrace])
            #else
            f = f.substring(to: indexOfBrace)
            #endif
        }
        f += "()"
        return f
    }
```

**Comment by skreutzberger** [comment]
What Xcode and Swift version are you using and on what device type does it crash? Can you maybe post some code to replicate it? It’s the first time I see that issue to be posted. Thanks!

**Comment by krmao** [comment]
hi @skreutzberger 
the crash desc is not clear, and no rule, while I rerun my application more than 3 times and crashed.
i think may be caused by muti threads ?

the code with crash is [CXLogUtil2](https://github.com/krmao/template/blob/master/apps/app-template/ios/arsenal/libraries/library-base/src/util/CXLogUtil2.swift)
and I change log to system print and application no crash now .[CXLogUtil](https://github.com/krmao/template/blob/master/apps/app-template/ios/arsenal/libraries/library-base/src/util/CXLogUtil.swift)

**Comment by skreutzberger** [comment]
Yes, it looks like a threading issue. SwiftyBeaver is running on its own low-prio background thread.
