### ISSUE TITLE
Why is log not printed before a fatal error but print() does?

### ISSUE THREAD

**Issue by junweimah** [SwiftyBeaver/SwiftyBeaver#280]
So I have a fatal error in my function and wanted to debug. This is my code : 

```
        logging.debug("this is index in pageboy : ", context: index)
        print("this is index in pagebou : \(index)")
        return self.viewControllers[index]
```
Screenshot of the fatal error : 

![image](https://user-images.githubusercontent.com/21700014/35955949-abed0e8a-0ccd-11e8-87f1-1edfef397697.png)

This is my log : 

![image](https://user-images.githubusercontent.com/21700014/35955964-c09244d6-0ccd-11e8-94db-b9d986790e25.png)

Note* : the debug message is from another vc

So as you can see the log, I get the message from print(), but not from logging.debug. What is causing this?

Thanks

**Comment by skreutzberger** [comment]
SwiftyBeaver is running on its own low-prio background thread to not be a drain on the app performance. `print` is running on the main main thread as your crashing viewController seems to run, too.

**Comment by junweimah** [comment]
So what if I want to use log just before any fatal error, or possible error, how should I do it?

**Comment by skreutzberger** [comment]
Logging something before a real crash (which should be rare in Swift) can be tricky in terms of timing.
