### ISSUE TITLE
Logs don't send to the macOS application

### ISSUE THREAD

**Issue by hamsternik** [SwiftyBeaver/SwiftyBeaver#281]
Hi development team,

today I get acquainted with the SwiftyBeaver project and decidedly add it to my small project to have an easy way to obtain all logs at the macOS app (as I read at the README it's should be quite easy). 

So I installed macOS app, entered my personal data and generated new credentials (literally from the app) to be able to send logs to the cloud. At once I add SwiftyBeaver as pod dependency to the iOS project and copypaste the code taken from the README page and run the project. Of course, I replaced the correct credentials generated from macOS app.

After logger set up, I called next lines of code at the end of application's `didFinishLaunchingWithOptions` method. 

```
log.debug("SwiftyBeaver has been successfully setuped")
log.verbose("SwiftyBeaver has been successfully setuped")
log.info("SwiftyBeaver has been successfully setuped")
```

As the result I should see this logs at the macOS app as a cloud logger I guess. But I don't see anything so. What the problem of this? What should I do to through logs to the cloud?

**Comment by skreutzberger** [comment]
Does logging to Xcode Console work with the ConsoleDestination? In that way you can be sure that your logger itself is properly set up.

**Comment by hamsternik** [comment]
@skreutzberger yes, I created `let console = ConsoleDestination()` instance and printing logs to Xcode console work properly. But I didn't receive any logs from the cloud.

Could you provide some sort of guide or article how to setup SwiftyBeaver with the cloud logging properly?
