### ISSUE TITLE
String vs StaticString

### ISSUE THREAD

**Issue by farzadshbfn** [SwiftyBeaver/SwiftyBeaver#282]
Why not use StaticString for #file, #line and things like that? wouldn't that be more optimized?

**Comment by skreutzberger** [comment]
Good idea and I know that from database libraries. But the general user would be confused I guess. Or what is the advantage over it besides maybe minimal performance improvements?

**Comment by farzadshbfn** [comment]
Well I kinda disagree on the confusing part. I Mean i never read about them, but the first time I saw `StaticString` i realized ok, it's different from `String`... and that word `Static` made me think "hmmm so maybe it's generated at compile time, hence code will be more optimized!".
I know it might sound like minimal performance improvement, but in my opinion it does not cause that "much" complexity to drop the optimization part.

Great Framework BTW 👍🏼. (specially the fact that each destination has it's own formatter, brilliant)
