### ISSUE TITLE
We should specify queue priority

### ISSUE THREAD

**Issue by Cyberbeni** [SwiftyBeaver/SwiftyBeaver#283]
BaseDestination.swift:
``` 
// each destination instance must have an own serial queue to ensure serial output
// GCD gives it a prioritization between User Initiated and Utility
var queue: DispatchQueue? //dispatch_queue_t?
var debugPrint = false // set to true to debug the internal filter logic of the class
public init() {
        let uuid = NSUUID().uuidString
        let queueLabel = "swiftybeaver-queue-" + uuid
        queue = DispatchQueue(label: queueLabel, target: queue)
}
```
I think we should set the QoS to utility to avoid slowing down any important work done on higher priority queues. Or at least have an open var that lets people set the priority as they want it.

**Comment by skreutzberger** [comment]
good point, unfortunately it would need to be put into every `init()` of all destinations which would them more and more confusing. Maybe there is another way of doing it?
