### ISSUE TITLE
Simple file rotation for mobile devices

### ISSUE THREAD

**Issue by Revue50** [SwiftyBeaver/SwiftyBeaver#284]
diff --git a/Pods/SwiftyBeaver/Sources/FileDestination.swift b/Pods/SwiftyBeaver/Sources/FileDestination.swift
index aaf216f..0f20354 100644
--- a/Pods/SwiftyBeaver/Sources/FileDestination.swift
+++ b/Pods/SwiftyBeaver/Sources/FileDestination.swift
@@ -16,6 +16,8 @@ public class FileDestination: BaseDestination {
     override public var defaultHashValue: Int {return 2}
     let fileManager = FileManager.default
     var fileHandle: FileHandle?
+    let maxLogFilesize = (5 * 1024 * 1024)  // 5MB
+    let noOfLogFiles = 2                   // Number of log files used in rotation
 
     public override init() {
         // platform-dependent logfile directory default
@@ -70,7 +72,7 @@ public class FileDestination: BaseDestination {
         let formattedString = super.send(level, msg: msg, thread: thread, file: file, function: function, line: line, context: context)
 
         if let str = formattedString {
-            _ = saveToFile(str: str)
+            _ = validateSaveFile(str: str)
         }
         return formattedString
     }
@@ -82,6 +84,58 @@ public class FileDestination: BaseDestination {
         }
     }
 
+    func validateSaveFile(str: String) -> Bool {
+        guard let url = logFileURL else { return false }
+        let filePath = url.path
+        
+        if FileManager.default.fileExists(atPath: filePath) == true {
+            do {
+                // Get file size
+                let attr = try FileManager.default.attributesOfItem(atPath: filePath)
+                let fileSize = attr[FileAttributeKey.size] as! UInt64
+                
+                // Do file rotation
+                if fileSize > maxLogFilesize {
+                    rotateFile(filePath)
+                }
+                
+            } catch {
+                print("validateSaveFile error: \(error)")
+            }
+        }
+        
+        return saveToFile(str: str)
+    }
+    
+    private func rotateFile(_ filePath: String) {
+        let lastIndex = (noOfLogFiles-1)
+        let firstIndex = 1
+        
+        do {
+            for index in stride(from: lastIndex, to: firstIndex, by: -1) {
+                let oldFile = String.init(format: "%@.%d", filePath, index)
+                
+                if FileManager.default.fileExists(atPath: oldFile) == true {
+                    if index == lastIndex {
+                        // Delete the last file
+                        try FileManager.default.removeItem(atPath: oldFile)
+                    } else {
+                        // Move the current file to next index
+                        let newFile = String.init(format: "%@.%d", filePath, index+1)
+                        try FileManager.default.moveItem(atPath: oldFile, toPath: newFile )
+                    }
+                }
+            }
+            
+            // Finally, move the current file
+            let newFile = String.init(format: "%@.d", filePath, firstIndex)
+            try FileManager.default.moveItem(atPath: filePath, toPath: newFile )
+            
+        } catch {
+            print("rotateFile error: \(error)")
+        }
+    }
+    
     /// appends a string as line to a file.
     /// returns boolean about success
     func saveToFile(str: String) -> Bool {

**Comment by skreutzberger** [comment]
👍 - has anyone any opinion about it?

**Comment by fmoraes74** [comment]
Any reason something like this was not added to the core package? It is extremely useful to have file rotation to keep log files in check. Otherwise, we have MB files that cannot be attached when asking for logs from users.

**Comment by mikeumus** [comment]
@skreutzberger @fmoraes74 ➕ 1️⃣

**Comment by IsaiahJTurner** [comment]
This project has been potentially breached and your app may be exposing private information. See issue #453

**Comment by skreutzberger** [comment]
@IsaiahJTurner What a troll. WTF is just wrong with you abusing the Github notification system? I have reported you to Github for spam. If you want to advertise for a company or project then please do it the normal way and leave the SwiftyBeaver contributors alone. SWIFTYBEAVER HAS NOT BEEN BREACHED. SwiftyBeaver is an open-source framework and its used encryption is public, known and trusted since several years. Feel free to contribute source code which makes it safer from your point of view and the contributors and I will consider merging it.
