### ISSUE TITLE
Memory usage too high

### ISSUE THREAD

**Issue by SimonRiis** [SwiftyBeaver/SwiftyBeaver#286]
Hi!
I´ve been using SwiftyBeaver in quite a few projects, the latest is going on AppStore soon. 
I have experiencing some strange memory usages, where the memory usage of the app raised to 900mb - 1.2gb in no time(1-2 secs) after starting the app. I have experienced this in two apps so far. 

First I thought I had some code running wild, but it turned out that if I commented out these lines that initialise SwiftyBeaver, then the memory usage would drop. 

`//        let platform = SBPlatformDestination(appID: "#", appSecret: "#", encryptionKey: "#")
//        log.addDestination(platform)`

After I commented these lines out, memory usage of the app dropped to 20-30mb. (Before the memory usage was between 900mb and 1.2gb)

I using the latest SDK, and my test device is running 11.2.6. The project is written in swift 4.1.

**Comment by skreutzberger** [comment]
I guess it is caused by a large buffered log file which somehow could not be sent to the server. Try to delete the buffered logfile and generally log less when logging to the platform destination. 

The server is rejecting log files which are larger than 10MB which is just happening if you really log a lot! After the server received a log file then it is automatically deleted on the mobile device.

The log file is called `sbplatform_entries.json` and is on iOS in the document directory https://github.com/SwiftyBeaver/SwiftyBeaver/blob/master/Sources/SBPlatformDestination.swift#L124

**Comment by leisurehound** [comment]
Is 'log less' really a satisfactory answer to this problem?  Logging infrastructure should be resilient to not being able to upload logs.  Shouldn't the end user experience have priority when the logs cannot be uploaded?  I experienced this problem last night where production apps that normally run at 34MB spin with 100% CPU and 1+GB of memory until the OS shuts down the app.  I can't ask my installed base to 'log less.'  Are there hooks in your API to even know how big the backlog is and adapt?  I'm not seeing anything.  

I've just removed SwiftyBeaver as I need a logging solution that does what its designed to when its working and fails gracefully when its not and not have a negative user experience of hot phones and out of memory crashes.

**Comment by skreutzberger** [comment]
Thanks for your suggestions and we will consider it.

**Comment by mvarie** [comment]
@skreutzberger I have just spent quite some time trying to understand why my app was skyrocketing to 500mb on launch and growing until terminated by iOS, as I assumed that I made a mistake somewhere. 

Regardless of whether it's sensible to accept larger logs, which is ultimately your decision, you could at least clarify that this is an issue, in your documentation - or at least output a clear error message or warning to the console.

**Comment by skreutzberger** [comment]
hello @mvarie logs are sent automatically to the cloud so a larger memory footprint should not occur. Also in one of our recent releases we introduced the concept of removing old unsent logs as far as I remember to avoid an overflow.
