### ISSUE TITLE
Request: Padding characters in format

### ISSUE THREAD

**Issue by htb** [SwiftyBeaver/SwiftyBeaver#294]
For readability, I would have liked to have an option to specify padding in the console outout.
For example "$-8L  [$-10X]  $M" with

```
log.info("Message 1", context: "context")
log.debug("Message 2", context: "server"
```

becoming

```
info      [context   ]  Message 1
debug     [server    ]  Message 2
```

**Comment by skreutzberger** [comment]
I think it should work already by adding tabs:
please try something like `$L\t $M"` - does it work?

**Comment by htb** [comment]
It helps somewhat, but only when we are lucky and the text does not pass another tab stop.
Example format: "$C$c __ $DHH:mm:ss$d  $L \t $M \t //$N"

```
💚  __ 15:53:30  DEBUG 	 Hello from app delegate         //AppDelegate
💙  __ 15:53:30  INFO 	 Hello from scanner      //BLELockScanner
```

Now add a third underscore and the column alignment breaks.

```
💚  ___ 15:54:50  DEBUG      Hello from app delegate 	 //AppDelegate
💙  ___ 15:54:50  INFO 	 Hello from scanner      //BLELockScanner
```

**Comment by skreutzberger** [comment]
I would say we leave it for now as it is with the `\t` as option. But I will keep my ears open for more users who want it and revisit later 👍 - closing it for now
