### ISSUE TITLE
Bug in console destination context format ($X)

### ISSUE THREAD

**Issue by htb** [SwiftyBeaver/SwiftyBeaver#295]
A format of "$L [$X]abcd$M" with missing context truncates the remaining text up to the $M if the context is missing: Eg, with context "AGENT":

`DEBUG [AGENT]abcdMy message`

but with missing context

`DEBUG [MyMessage
`

**Comment by skreutzberger** [comment]
Good catch! Can you fix it via pull request?

**Comment by htb** [comment]
Will do.

I also noticed that a format begining with a format character bugs out, e.g. "Linda $M" can become "VERBOSEinda My message". This is because the line is not parsed from the beginning, but separated using format.components(separatedBy: "$"). So "Linda $M" is interpreted the same way as "$Linda $M"

Will add a simple fix for this too.

**Comment by htb** [comment]
This is fixed in the proposed pull request #298.

**Comment by skreutzberger** [comment]
thanks, I will have a look.
