### ISSUE TITLE
Color in Xcode console is not work

### ISSUE THREAD

**Issue by archmagees** [SwiftyBeaver/SwiftyBeaver#301]
Xcode version is 9.4.1, pod version is `Using SwiftyBeaver (1.6.0)`.
My project is Objective-C, so I wrapped a new swift file, implementation is following:
```objc
//  Log.swift
import Foundation
import SwiftyBeaver

let log = SwiftyBeaver.self

@objc public class Log: NSObject {
    @objc public class func start() {
        let console = ConsoleDestination()
        console.asynchronously = false;
        console.useTerminalColors = true
        let file = FileDestination()
        log.addDestination(console)
        log.addDestination(file)
    }
    
    @objc public class func error(message: NSString) {
        log.error(message)
    }
}
```
Code in a view controller is like this:
```objc
- (void)viewDidLoad
{
    [Log start];
    
    [Log errorWithMessage:@"error string should has color"];
```
The output is:
![screenshot 2018-07-11 10 17 34](https://user-images.githubusercontent.com/7042522/42547234-a8487712-84f3-11e8-843c-00248f5d7ccd.png)

Why the output is not colored?

**Comment by nothing2lose** [comment]
Please check this link : https://gist.github.com/skreutzberger/7c396573796473ed1be2c6d15cafed34
