### ISSUE TITLE
Request: Make switching logs for different projects easier

### ISSUE THREAD

**Issue by jyounus** [SwiftyBeaver/SwiftyBeaver#302]
Hey there,

At the moment, if I want to switch between different projects, I need to manually enter the app id, app secret and encryption key. If you have multiple projects, this is annoying and time consuming. 

Could you please add an easier way to manage/switch between different projects in the mac app? 

Maybe a new icon in the left sidebar, which allows you to save all your different project configs and easily switch between them by clicking a single button? 
Or even replace the existing functionality of the "Settings" icon to allow it to remember and switch between multiple projects.

That would make it much better for me, and would be super useful for apps that use different credentials for different build types (dev/staging/qa/production).

What do you reckon?

**Comment by skreutzberger** [comment]
Sorry for the late reply, somehow that issue totally slipped through. 

Actually you can already now monitor multiple projects at the same time. Each project (consisting of app id and app secret) is stored in a file with the suffix `.beaver`. 

Like in Apple Pages or Microsoft Word you can have multiple documents open at the same time. 

Behind the scenes the SwiftyBeaver Mac App is using the standard macOS DocumentViewController which makes all that possible. Maybe have a look at our Mac App's menu (I mean the one at the top of your desktop). You will see common things like "Open New File", etc.

**Comment by katsumoto** [comment]
Hi,

thats one way to do it. But if it would work like e.g. with Slack, where you have on the side additionally different "Slack-Projects" where you can easily ans swiftly switch between...
