### ISSUE TITLE
Not logging to Mac App

### ISSUE THREAD

**Issue by anuranBarman** [SwiftyBeaver/SwiftyBeaver#304]
I installed it via cocoapods and set it up as you said in the doc. Where as debugging to XCode Console is working but logging to SwiftyBeaver platform which I am accessing via your mac app is not working. The logs are not coming out. I have set it up properly with right credentials

**Comment by skreutzberger** [comment]
Maybe try logging some errors, sometimes logs are buffered and not sent if they are not important enough.
