### ISSUE TITLE
Search by user name is not reliable in Mac app

### ISSUE THREAD

**Issue by vitalii-tym** [SwiftyBeaver/SwiftyBeaver#305]
App Version: `Version 1.1.0 (1100)` ("Check for Updates..." says its the latest one)

For some names it works, but I can't be sure it shows all records. 

For example, clicking on user name here seems to be working (not sure all messages are shown though, user's name is unknown so its just a UDID):

<img width="1116" alt="screenshot 2018-09-07 16 01 17" src="https://user-images.githubusercontent.com/5410835/45220769-fee54e00-b2b7-11e8-8c18-ee25313ec528.png">

But for most of names it yields no results. When I know for sure that there are records for "Vitaliy T17" for example:

<img width="1107" alt="screenshot 2018-09-07 16 02 22" src="https://user-images.githubusercontent.com/5410835/45220895-6c917a00-b2b8-11e8-9745-81f10d703c3d.png">

after I click on the name "Vitaliy T17", text "by: Vitaliy T17" is added into search field and this results in an empty list for some reason:
 
<img width="1107" alt="screenshot 2018-09-07 16 02 32" src="https://user-images.githubusercontent.com/5410835/45220855-44a21680-b2b8-11e8-92e1-188514f0c169.png">

If I delete "by: " from the search text some records will appear, but not all of them:

<img width="1107" alt="screenshot 2018-09-07 16 03 53" src="https://user-images.githubusercontent.com/5410835/45220957-9d71af00-b2b8-11e8-8b66-53778e112bd4.png">

I can't rely on the search functionality at all.

**Comment by skreutzberger** [comment]
Hey, thanks for the info. did you try using apostrophes? You can also directly access to local SQLite database where the logs are stored in by right-clicking the .beaver document and selecting Show Package Contents in Finder.

**Comment by vitalii-tym** [comment]
Apostrophes doesn't help.
I don't see anything that would look like an SQLite file inside the app bundle. But even if it was there, I don't understand how it could help me to see all user's logs in the app's UI by clicking on his name in a log.
Did you close it because it is already fixed an update coming soon?

**Comment by skreutzberger** [comment]
I closed it because it does not relate to the SwiftyBeaver framework but to our commercial product. I added the bug report to our internal tool 👍
