### ISSUE TITLE
There was an eight-hour delay on the Linux system

### ISSUE THREAD

**Issue by iphone5s** [SwiftyBeaver/SwiftyBeaver#313]
➜  SwiftyBeaver git:(master) date
Fri Jan 11 11:56:15 CST 2019

03:56:11.106 💚 DEBUG SwiftyBeaverTests.testDestinationIntegration():160 - a debug hello from 2 different consoles!
03:56:11.107 💜 VERBOSE SwiftyBeaverTests.testDestinationIntegration():167 - default file msg 1
03:56:11.107 💜 VERBOSE SwiftyBeaverTests.testDestinationIntegration():168 - default file msg 2
03:56:11.108 💜 VERBOSE SwiftyBeaverTests.testDestinationIntegration():169 - default file msg 3

There was an eight-hour delay on the Linux system
Fri Jan 11 11:56:15 CST 2019
03:56:11.107

**Comment by skreutzberger** [comment]
Is it maybe caused by a different timezone on the server?
