### ISSUE TITLE
No Console Output while connected to CarPlay

### ISSUE THREAD

**Issue by ChristianSteffens** [SwiftyBeaver/SwiftyBeaver#314]
I noticed - and that's technically not a SwiftyBeaver-only issue - that there's no Console Output while an iPhone or Simulator is connected to CarPlay. The console output remains completely empty. No logging statements appears in the console destination - but interestingly enough the file destination works perfectly fine.

Furthermore: If I connect the device or simulator to CarPlay after (!) the debug session has been started, the console output is printed without any problems.

I would certainly spent one of our Apple Developer TSIs on this issue, but besides waiting a long time for an answer probably not really helpful, I'm hopping for an idea here.

You could recreate the problem even without a CarPlay Entitlement from Apple and / or the necessary hardware. Everything can be reproduced using the simulator. I'm happy to provide a demo project if this might be necessary.

**Comment by skreutzberger** [comment]
Thanks for the info, we actually never tested it with CarPlay and it is good that at least the file destination is working.

**Comment by ChristianSteffens** [comment]
I'm confused - are you not interested in solving this bug?

There might be a fix or workaround to make it work anyhow, even if it's not a specific SwiftyBeaver issue - it would certainly benefit from a potential solution.
