### ISSUE TITLE
Save last X number of logs / log expiration?

### ISSUE THREAD

**Issue by MaxHasADHD** [SwiftyBeaver/SwiftyBeaver#319]
I would like to have the file destination log to start cleaning up after a date expiration, or even just keep up to a maximum number of lines and then start deleting off the top of the file. I've received some logs over 20mb because users have been using the app for so long. I could incorporate a time based clearing of the entire cache but sometimes there could be important information needed in the log. Would this be possible to implement into the framework?

**Comment by skreutzberger** [comment]
We kept the file destination as simple and flexible as possible because there are many ways of doing expiration. Feel free to use the file destination as base for a more detailed implementation.
