### ISSUE TITLE
Swift 5: firstIndex vs index

### ISSUE THREAD

**Issue by stephenfeather** [SwiftyBeaver/SwiftyBeaver#325]
I was looking at some of the changes, and in Extensions.swift, you guys now have:

`
/// cross-Swift-compatible index
    
func find(_ char: Character) ->  Index? {
  #if swift(>=5)
     return self.firstIndex(of: char)
  #else
     return self.index(of: char)
  #endif
}
`

index vs firstIndex isnt a swift level change but an ios sdk level change (ios 10+)
Xcode's swift 5 converter actually takes your code, flags it and suggests that both returns be firstIndex.

The same goes for the changes in BaseDestination in the removeFilter function.

**Comment by lgaches** [comment]
https://github.com/apple/swift/blob/6972f8345ef538aa352a72f98335b81b302316e6/stdlib/public/core/MigrationSupport.swift#L562

**Comment by skreutzberger** [comment]
Thanks Laurent for sending the link, super helpful 👍. Stephen, you are correct, it works the same and the purpose was to stay future-proof and to avoid deprecation warnings.
