### ISSUE TITLE
flush() in BaseDestination is marked as deprecated with no replacement

### ISSUE THREAD

**Issue by Fallen-Zen** [SwiftyBeaver/SwiftyBeaver#326]
My app has a logic of sending few last lines from the log file to our server whenever app detects for example 404 or 500 response from server.
Unfortunately at the time the file is read not everything has been flushed to it and we end up with incomplete log (missing last line or two with the error message). Unfortunately flush() function has been commented out and marked as deprecated with no replacement.

Any ETA on that? Thank you!

**Comment by skreutzberger** [comment]
So far we have no ETA since it has a low priority. It would be great if you could contribute a modern, working flushing as pull request 😊. In the meantime I am closing the issue.
