### ISSUE TITLE
log in deinit{} function will cause crash sometimes

### ISSUE THREAD

**Issue by libern** [SwiftyBeaver/SwiftyBeaver#331]
![image](https://user-images.githubusercontent.com/1830640/57567882-786aa880-7412-11e9-929f-b038bccd421b.png)

See:
![image](https://user-images.githubusercontent.com/1830640/57567898-a223cf80-7412-11e9-8e56-6f3682e185aa.png)

![image](https://user-images.githubusercontent.com/1830640/57567915-d39c9b00-7412-11e9-897c-5b6b0b787750.png)

**Comment by skreutzberger** [comment]
Sorry for the late reply, totally missed that issue. What iOS, Xcode and SwiftyBeaver version do you use?

**Comment by libern** [comment]
All are Latest by the time
