### ISSUE TITLE
Unified Logging destination?

### ISSUE THREAD

**Issue by basememara** [SwiftyBeaver/SwiftyBeaver#332]
I'd like logs to be sent to the App Store. I think the Unified Logging API's has to be used for this. Is there a logging destination that can be used for this, or a better way to do this?

**Comment by skreutzberger** [comment]
Unfortunately there is currently not but feel free to contribute it! Our destination design is pretty straight forward with old school inheritance to be really easy to understand. Do you want to give it a try?

**Comment by basememara** [comment]
Thx I found this: https://medium.com/back-market-engineering/discovering-using-oslog-output-console-with-swiftybeaver-on-ios-54d7bfbe3b97
