### ISSUE TITLE
INFO: Xcode 11 / iOS 13 Beta? -> Use "xcode11-beta" branch 🎉

### ISSUE THREAD

**Issue by skreutzberger** [SwiftyBeaver/SwiftyBeaver#334]
As the title says: if you want to use SwiftyBeaver with the pre-release Xcode 11 and iOS 13 betas then please use the `xcode11-branch`. 

If you run into any troubles then please write them down here as reply or post them on our Slack. 

Thanks!

**Comment by AlexRWT** [comment]
When import SwiftyBeaver via swift package, EXC_BAD_ACCESS happened on calling `ConsoleDestination()`
see [link](https://cdn1.imggmi.com/uploads/2019/6/25/0e4785a187a705691d1281006d308d65-full.png)

**Comment by AlexHsieh** [comment]
When import SwiftyBeaver via swift package, EXC_BAD_ACCESS happened on calling `ConsoleDestination()`
see [link](https://cdn1.imggmi.com/uploads/2019/6/25/0e4785a187a705691d1281006d308d65-full.png)

**Comment by skreutzberger** [comment]
does it have the same issue if you set-up the logger as described in the docs? I mean without the `LoggerServiceType` wrapper? https://docs.swiftybeaver.com/article/6-basic-setup

**Comment by AlexHsieh** [comment]
It works fine in xcode Beta 3. Probably xcode issue.

**Comment by skreutzberger** [comment]
On Friday, September 27 we will merge content of the `xcode11-beta` branch into the `master` branch and release a new version. Thanks @lgaches for your help on adding support for Xcode 11 and iOS 13 🙏
