### ISSUE TITLE
Global log level does not work with non-required filters

### ISSUE THREAD

**Issue by FelixII** [SwiftyBeaver/SwiftyBeaver#339]
I'm running into an issue where a destination's global log level is no longer respected when one or multiple non-required filters are set.

Consider the following example:

    let log = SwiftyBeaver.self
    let console = ConsoleDestination()
    console.minLevel = .debug
    log.addDestination(console)

    log.debug("Hello")
    log.verbose("World")

The debug message is shown as expected.

As soon as I add a path filter that does **not** match my current file, e.g.

    let log = SwiftyBeaver.self
    let console = ConsoleDestination()
    console.minLevel = .debug

    console.addFilter(Filters.Path.contains("myPathFilter", minLevel: .verbose))

    log.addDestination(console)

    log.debug("Hello")
    log.verbose("World")

the debug message is no longer shown in the console log.

I suspect this code block:
https://github.com/SwiftyBeaver/SwiftyBeaver/blob/3f6815ca53840ac8373e872bc313add1c6983098/Sources/BaseDestination.swift#L460-L475

When there are no non-required filters, the destination should check the global log level instead of returning 'false'.

Can anyone confirm this issue? I would be happy to submit a pull request.

**Comment by skreutzberger** [comment]
Hmm, are you using the latest SwiftyBeaver version `1.7.0`? You see your version in line 15 of the file `Sources/SwiftyBeaver.swift`.

Please try to also add `required: true` to `Filters.Path.contains()` to see if you reach your expected behavior. Normally it should not but ¯\_(ツ)_/¯

**Comment by FelixII** [comment]
Yes, I have tested this issue in a new project with the latest SwiftyBeaver version 1.7.0.

When I add `required:true` to my filter, the debug message is also not displayed. The log call fails (as expected) in line 467:

https://github.com/SwiftyBeaver/SwiftyBeaver/blob/3f6815ca53840ac8373e872bc313add1c6983098/Sources/BaseDestination.swift#L465-L468

**Comment by skreutzberger** [comment]
Do you want to create a pull request which fixes the issue and still works with all existing unit tests? I would be more than happy to merge it into master since you really found an issue. Still, I don’t want to do it by myself because the whole filtering system was written by other contributors and my understanding is not deep enough.

**Comment by FelixII** [comment]
I've created a new PR #341. I decided to refactor parts of the filtering system, because the old 'count comparison' logic was not sufficient to cover all edge cases. I hope that is now also a little bit easier to read and understand.
