### ISSUE TITLE
What the heck is that?

### ISSUE THREAD

**Issue by beefon** [SwiftyBeaver/SwiftyBeaver#343]
https://github.com/SwiftyBeaver/SwiftyBeaver/blob/master/Tests/SwiftyBeaverTests/FileDestinationTests.swift#L46

**Comment by skreutzberger** [comment]
At that time it was not clear how to let a unit test wait a while on the main thread while SwiftyBeaver itself is doing its stuff on it's own background thread. 

A contribution to fix that ugly heck would be more than welcome.

**Comment by beefon** [comment]
Why is not a simple `sleep`?

**Comment by skreutzberger** [comment]
Sleep is not working in unit tests because a test is run in an own thread or so.
