### ISSUE TITLE
SwiftyBeaver 1.8.0 breaks Carthage support

### ISSUE THREAD

**Issue by Sidetalker** [SwiftyBeaver/SwiftyBeaver#353]
SwiftyBeaver 1.8.0 removed all .xcodeproj files which broke Carthage support.

**Comment by r-plus** [comment]
error output

```
*** Skipped building SwiftyBeaver due to the error:
Dependency "SwiftyBeaver" has no shared framework schemes for any of the platforms: iOS
```

**Comment by skreutzberger** [comment]
Oops, it seems we were depending too much on Carthage. Sorry!
I released a hotfix which brings back the `.xcodeproj` file and moved the `1.8.0` tag to the latest commit on master. All should be good then.

**Comment by Sidetalker** [comment]
Thanks @skreutzberger!
