### ISSUE TITLE
iOS version is higher in SPM than in CocoaPods

### ISSUE THREAD

**Issue by OlexandrStepanov** [SwiftyBeaver/SwiftyBeaver#361]
Hello,

I have noticed, that minimum iOS deployment version of the library is 11 in Package.swift, i.e. for SPM, and iOS 8 in podspec, i.e. for CocoaPods.
Is that on purpose? Can these versions be in sync?

With regards.

**Comment by skreutzberger** [comment]
Good point, actually it is not on purpose. Do you want to contribute a small fix as PR?

**Comment by OlexandrStepanov** [comment]
@skreutzberger , here you go https://github.com/SwiftyBeaver/SwiftyBeaver/pull/362

**Comment by skreutzberger** [comment]
It will be part of the next release
