### ISSUE TITLE
SPM 'SwiftyBeaver' requires minimum platform version 10.12 for macos platform

### ISSUE THREAD

**Issue by javier-byte** [SwiftyBeaver/SwiftyBeaver#364]
Hi,

First of all great logging lib.

I am compiling my project using SPM in Catalina 

`ProductName:	Mac OS X
ProductVersion:	10.15
BuildVersion:	19A602`

When I'm compiling using version 1.8.2, I get the message:

`error: the product 'SwiftyBeaver' requires minimum platform version 10.12 for macos platform`

This seems fix in the master branch. So basically I just wanted to know when the next release will be, so that I can pin the project to an specific version.

I'm not sure if I'm doing something wrong

Thanks

**Comment by skreutzberger** [comment]
I just released version 1.8.3 which includes the fix :)
