### ISSUE TITLE
Crash on latest version 1.8.3 with optionals

### ISSUE THREAD

**Issue by sachinvas** [SwiftyBeaver/SwiftyBeaver#368]
```
0  libswiftCore.dylib             0x1077f7198 specialized _fatalErrorMessage(_:_:file:line:flags:) + 363316
1  libswiftCore.dylib             0x107718240 __CocoaSet.Iterator.next() + 54320
2  SwiftyBeaver                   0x106333288 specialized static SwiftyBeaver.dispatch_send(level:message:thread:file:function:line:context:) + 149 (SwiftyBeaver.swift:149)
3  SwiftyBeaver                   0x1063304ec static SwiftyBeaver.verbose(_:_:_:line:context:) + 152
4  SwiftyBeaver                   0x106330448 static SwiftyBeaver.error(_:_:_:line:context:) + 48
```

Hi, we are facing a crash with SwiftyBeaver. I went through the code, couldn't find anything. Can you please tell me why I am getting `
Fatal error: Unexpectedly found nil while unwrapping an Optional value` here?

**Comment by skreutzberger** [comment]
Hi, did it happen while you tried to log an optional value.

**Comment by sachinvas** [comment]
@skreutzberger Checked the code, no we are not logging the force-unwrapped optional. However, we are trying to log asynchronously.  i.e calling verbose and info logs on our private aysnc queue. Do you think any data races are happening here?

**Comment by skreutzberger** [comment]
Ah yes, the async queue may be the issue. SwiftyBeaver is using its own thread and that may cause a race condition.

**Comment by skreutzberger** [comment]
I am closing the issue for now
