### ISSUE TITLE
Wrong iOS 11 minimum deployment target when building from xcodeproj/Carthage

### ISSUE THREAD

**Issue by MarkVillacampa** [SwiftyBeaver/SwiftyBeaver#369]
There is a discrepancy in the minimum iOS and tvOS minimum deployment target between the `.package` and the Xcodeproj:

https://github.com/SwiftyBeaver/SwiftyBeaver/blob/237561f5b1e970fa316553ecbd08ad62ca8feef5/Package.swift#L10

https://github.com/SwiftyBeaver/SwiftyBeaver/blob/237561f5b1e970fa316553ecbd08ad62ca8feef5/SwiftyBeaver.xcodeproj/project.pbxproj#L393

This causes Carthage to generate an artifact with iOS 11 minimum deployment target. 

I think the issue would be solved by re-generating the Xcodeproj via `swift package generate-xcodeproj`

**Comment by skreutzberger** [comment]
@lgaches 3 questions from my side:

1.  There was a reason why we chose iOS 11, right? 
2. So which file should be the single source of truth? Package.swift or the project file? 
3. What minimum OS versions do you generally recommend? We could then put these into all files which contain that stuff (project file, package.swift and the Cocoapods file)

**Comment by skreutzberger** [comment]
@lgaches Thanks a lot! So can we say that from now on these are the minimums:
```
 .macOS(.v10_10),
 .iOS(.v8),
 .tvOS(.v9),
  .watchOS(.v2)
```

I checked and it seems the SPM file is in sync with the Cocoapods file. So we just would need to manually adjust the Xcode project file. Would that be okay? If yes then I would manually adjust the Xcode project file.

**Comment by skreutzberger** [comment]
I added the unified OS requirements at https://github.com/SwiftyBeaver/SwiftyBeaver/commit/9a0739ddd7283783c8e7d9b3a89a5e4dfb6f8bfb - it will be part of the next release. Thanks to everyone involved!
