### ISSUE TITLE
Log message is always "(Function)"

### ISSUE THREAD

**Issue by joshuabell** [SwiftyBeaver/SwiftyBeaver#372]
A week or two ago I started noticing all SwiftyBeaver logs printing "(Function)" instead of the log message. I updated SwiftyBeaver to the latest but no dice. I tried joined the Slack community but the max invite limit prevented that. I upgraded my SwiftyBeaver account but that didn't fix it either. Any help is appreciated.

My logs in the Xcode console look like:
12:59:18.152 💜 VERBOSE PersonaRequests.fetchPersonas():37 - (Function)
12:59:18.175 💙 INFO NotificationTrailViewModel.checkForUnseenActivityNotifications():73 - (Function)
12:59:18.214 💜 VERBOSE LaunchScreenContinuationViewController.loadPinnedCurrentPersonas():27 - (Function)
12:59:18.480 💜 VERBOSE MainTabBarController.getNotificationSettings():291 - (Function)
12:59:18.526 💜 VERBOSE FeedRequests.newsFeed():46 - (Function)

My logs in the SwiftyBeaver mac app look like:
<img width="842" alt="SwiftyBeaver-issue" src="https://user-images.githubusercontent.com/1005629/68321370-fd6c0d00-0097-11ea-8971-eeb7ad472888.png">

**Comment by skreutzberger** [comment]
Did you do anything custom like the formatter or so? Can you please print here your logger setup and a typical logging call? Please do NOT add secrets.

Relating Slack: thanks for the info! It seems we reached a limit with our 2100 users now and I contacted Slack and asked for help.

**Comment by joshuabell** [comment]
No custom formatting for the logs. I installed Swifty Beaver the manual way, happy to try CocoaPods if you think that might help? 

My logger setup looks like with a typical logging call:
`let console = ConsoleDestination()  // log to Xcode Console
  let file = FileDestination()  // log to default swiftybeaver.log file
  let platform = SBPlatformDestination( appID: "***", appSecret: "***", encryptionKey: "***" )
  log.addDestination( console )
  log.addDestination( file )
  log.addDestination( platform 
  log.verbose( "SwiftyBeaver verbose log" )`

**Comment by skreutzberger** [comment]
What Swift version and iOS/tvOS/... version are you using? Also what is the value of `SwiftyBeaver.version`?

**Comment by joshuabell** [comment]
Thanks for the quick response! It's Swift 5, SwiftyBeaver.version is 1.6.0

**Comment by skreutzberger** [comment]
The SwiftyBeaver version could be the issue since we just added Swift 5 support in version `1.7.0`and we are now on version `1.8.3`. Please try to install it via Carthage, Cocoapods or SPM. Maybe that will fix the issue, I am keeping fingers crossed.

**Comment by joshuabell** [comment]
Thank you! Your intuition was spot on and fixed the issue. I thought I was testing with the latest but was on the wrong branch. I tested with 1.8.3 and get logs messages now, thanks again!
