### ISSUE TITLE
Beaver on Ubuntu - no log output to console

### ISSUE THREAD

**Issue by pkasson** [SwiftyBeaver/SwiftyBeaver#373]
hi,

setup bare bones sample - from this site:
https://medium.com/back-market-engineering/discovering-using-oslog-output-console-with-swiftybeaver-on-ios-54d7bfbe3b97

All that appears is:

Hello, world!
after logging

It appears the the Console may be the issue - the code looks like it checks all OS types, and Ubuntu is Linux, so should be on stdout.

**Comment by skreutzberger** [comment]
The issue with server-side Swift apps is that they often are too short lived to actually write something on stdout. SwiftyBeaver is running in its own thread which has a low priority to be not a drag on your app’s performance. So maybe try some longer running server-side Swift code. It should work.

**Comment by pkasson** [comment]
Yep .. put a few sleep calls in and got output - thanks for the suggestion.
