### ISSUE TITLE
nil while unwrapping an Optional in ios 13

### ISSUE THREAD

**Issue by fjsevilla** [SwiftyBeaver/SwiftyBeaver#375]
Hi, i'm having an issue with the version 1.8.3 with xcode 11.2 and ios 13. When the app starts it crashes with error: Fatal error: Unexpectedly found nil while unwrapping an Optional value on line 161. How can i solve it?
sorry for my bad english..

**Comment by skreutzberger** [comment]
Can you please post your initialization code (without the secrets?). It sounds to me like a "faster" thread which wants to use the logger but it was not initialized, yet.

SwiftyBeaver is running on its own thread and it is a low-prio one to be not a drag on your app’s performance.

**Comment by fjsevilla** [comment]
`import SwiftyBeaver
let log = SwiftyBeaver.self

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {
    
    var window: UIWindow?
    // Functions
    @available (iOS 9.0, *) 
    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
        // add log destinations. at least one is needed!
        let console = ConsoleDestination()  // log to Xcode Console
        let file = FileDestination()  // log to default swiftybeaver.log file
        let platform = SBPlatformDestination(appID: "", appSecret: "", encryptionKey: "")

        file.format = "$DHH:mm:ss$d $C$L$c: $M"  // hour, minute, second, colored log level and message

        var baseURL:URL?
        let fileManager = FileManager.default
        if let url = fileManager.urls(for: .cachesDirectory, in: .userDomainMask).first {
            baseURL = url
        }
        file.logFileURL = baseURL?.appendingPathComponent("oscomMovil.log", isDirectory: false)

        log.addDestination(platform)
        log.addDestination(console)
        log.addDestination(file)`

on ios 9 and 11 this works fine

**Comment by fjsevilla** [comment]
I have found the problem.
When initializing the Fabric sdk, it threw the error, so force to print a message in the log first.
then the error occurred when I printed the country value, since it was nil, so use the String (describing :)

  log.addDestination(platform)
        log.addDestination(console)
        log.addDestination(file)
        
        FirebaseApp.configure()
        //Fabric.with([Crashlytics.self])
        log.info("Log intialized")
        Fabric.sharedSDK().debug = true
        // Override point for customization after application launch.
        
        // Get country.
        let locale = Locale.current
        let country = (locale as NSLocale).object(forKey: NSLocale.Key.countryCode) as? String
        log.info("Country: \(String(describing: country))")

thanks for helping

**Comment by skreutzberger** [comment]
I am happy that you could find the issue. Happy Logging!
