### ISSUE TITLE
Provide more human readable thread name information

### ISSUE THREAD

**Issue by robowen5mac** [SwiftyBeaver/SwiftyBeaver#376]
As things currently work when you add the thread to the log format, you get the thread's address, e.g. 0x600000000000 when the log message is sent in a DispatchQueue. It would be nice to have a more human readable name. I am happy to do a pull request but wanted to discuss options:

1) Change the threadName method to use something like __dispatch_queue_get_label(nil) which when converted to a string will give you com.apple.root.userinitiated-qos. If we wanted to shorten, we could just take the last element.

2) Expose a new parameter on the log methods that allow a custom thread name to be passed into the function. If is is present it is used instead of the result of threadName()

Option one is the most direct, but I don't want to change the behaviour for anyone that expecting the current naming convention.

Thoughts?

**Comment by skreutzberger** [comment]
Thanks for the info! I actually expected it to still behave in the way it did 2 years ago where you could actually see a thread's name instead of the thread address.

So every solution which makes a thread name human-readable is good. I tend towards option 1. What would be the default value for the main thread? AFAIR in the past we had "main" or "" and that value at least should stay as it is.

**Comment by robowen5mac** [comment]
In that case. I would suggest something like the following, which I based off of here:

https://gist.github.com/thexande/5afe278545bef38c78a27897b4a56061

```swift
class func threadName() -> String {

        #if os(Linux)
            // on 9/30/2016 not yet implemented in server-side Swift:
            // > import Foundation
            // > Thread.isMainThread
            return ""
        #else
            if Thread.isMainThread {
                return ""
            } else {
               let name = __dispatch_queue_get_label(nil)
               return String(cString: name, encoding: .utf8) ?? Thread.current.description
            }
        #endif
    }

```

This will keep the main thread the same, but will give the more readable name, eg:

```swift
func testGetCorrectThread() {
        let log = SwiftyBeaver.self
        let mock = MockDestination()
        // set info level on default
        mock.minLevel = .verbose
        mock.asynchronously = false

        log.addDestination(mock)

        //main thread
        log.verbose("Hi")
        XCTAssertEqual(mock.didSendToThread, "")
        log.debug("Hi")
        XCTAssertEqual(mock.didSendToThread, "")
        log.info("Hi")
        XCTAssertEqual(mock.didSendToThread, "")
        log.warning("Hi")
        XCTAssertEqual(mock.didSendToThread, "")
        log.error("Hi")
        XCTAssertEqual(mock.didSendToThread, "")

        let expectation = XCTestExpectation(description: "thread check")

        DispatchQueue.global(qos: .background).async {
            log.verbose("Hi")
            XCTAssertEqual(mock.didSendToThread, "com.apple.root.background-qos")
            log.debug("Hi")
            XCTAssertEqual(mock.didSendToThread, "com.apple.root.background-qos")
            log.info("Hi")
            XCTAssertEqual(mock.didSendToThread, "com.apple.root.background-qos")
            log.warning("Hi")
            XCTAssertEqual(mock.didSendToThread, "com.apple.root.background-qos")
            log.error("Hi")
            XCTAssertEqual(mock.didSendToThread, "com.apple.root.background-qos")
            expectation.fulfill()
        }

        self.wait(for: [expectation], timeout: 2)

    }

```

**Comment by skreutzberger** [comment]
It looks good. Can you maybe also add a test which uses `DispatchQueue(label: "MyTestLabel", ...)` and then checks if the `MyTestLabel ` value is returned as thread?

**Comment by robowen5mac** [comment]
Good point...have added and will send the pull request.

**Comment by skreutzberger** [comment]
Was fixed by the PR and will be part of the next released. Thanks a lot for the contribution!
