### ISSUE TITLE
Question about @autoclosure

### ISSUE THREAD

**Issue by c0diq** [SwiftyBeaver/SwiftyBeaver#378]
Looking at the codebase, line 158 of SwiftyBeaver.swift in `dispatch_send`, it appears that the autoclosure is being exercised even if the message is not to be logged if the destination has filters.
Would it be better to not exercise the closure until after `shouldLevelBeLogged` returns true?

Without this, the code may execute side effects or excessive string formatting when log level would strip those logs otherwise.

**Comment by skreutzberger** [comment]
You mean the code which sets `resolvedMessage` at  https://github.com/SwiftyBeaver/SwiftyBeaver/blob/master/Sources/SwiftyBeaver.swift#L154 right?

I actually try to wrap my head around the code and it looks pretty ugly. Anyway, it was contributed and covered with unit tests and it seems to work fine. But  I get your point of potentially optimizing it. Feel free to submit a PR and as long all tests stay green and things still work then you are good to go :)

**Comment by c0diq** [comment]
shouldLevelBeLogged should only be passed the level.

**Comment by skreutzberger** [comment]
let's just leave it as it is for now
