### ISSUE TITLE
I need to use SwiftyBeaver with XCUITest to log the test results in a file

### ISSUE THREAD

**Issue by moatazeldebsy** [SwiftyBeaver/SwiftyBeaver#383]
I need to log with `SwiftyBeaver` the `failure assertion error`, `Test Case name`, and` Test Suite` in the log file, how can I do this

**Comment by skreutzberger** [comment]
That is not supported. Xcode also uses a very protected / isolated test system so even managing multiple threads is very hard. SwiftyBeaver is for example running on an own thread.

**Comment by IsaiahJTurner** [comment]
This project has been potentially breached and your app may be exposing private information. See issue #453

**Comment by skreutzberger** [comment]
@IsaiahJTurner WTF is just wrong with you abusing the Github notification system? I have reported you to Github for spam. If you want to advertise for any company please do it the normal way.
