### ISSUE TITLE
stripParams for function is unnecessary

### ISSUE THREAD

**Issue by TickTickBird** [SwiftyBeaver/SwiftyBeaver#384]
As titled, I  think stripParams is unnecessary. And in some cases it's even troubling like some delegate methods which has the same prefix will be logged as the same as each other. Just remove the stripping or make it configurable?

**Comment by skreutzberger** [comment]
thank you for the comment, we will do some experiments and see if we can get rid of them

**Comment by ratkins** [comment]
I'm seeing this too, trying to debug log `CBCentralManagerDelegate` callbacks, whose first half is always the same so I can't distinguish `centralManager(central:didConnect:)` from `centralManager(central:didDisconnectPeripheral:error:)`. Just to check: that this shows `CentralManagerDelegate.centralManager()` for both is the current, intended behaviour yes?

**Comment by IsaiahJTurner** [comment]
This project has been potentially breached and your app may be exposing private information. See issue #453

**Comment by skreutzberger** [comment]
@IsaiahJTurner WTF is just wrong with you abusing the Github notification system? I have reported you to Github for spam. If you want to advertise for a company or project then please do it the normal way and leave the SwiftyBeaver contributors alone. NOTHING HAS BEEN BREACHED.
