### ISSUE TITLE
Signup doesn't work

### ISSUE THREAD

**Issue by artem-shmatkov** [SwiftyBeaver/SwiftyBeaver#385]
Hi! I'm trying to start work with SwiftyBeaver platform, but can't get an account and app credentials.
App stuck after I tap "Signup" button, it shows loader infinitely.

**Comment by skreutzberger** [comment]
Hi, please contact our support in case the problem was not solved, yet

**Comment by IsaiahJTurner** [comment]
This project has been potentially breached and your app may be exposing private information. See issue #453

**Comment by skreutzberger** [comment]
@IsaiahJTurner WTF is just wrong with you abusing the Github notification system? I have reported you to Github for spam. If you want to advertise for a company or project then please do it the normal way and leave the SwiftyBeaver contributors alone.
