### ISSUE TITLE
Xcode 11.4 Undefined symbol

### ISSUE THREAD

**Issue by possen** [SwiftyBeaver/SwiftyBeaver#386]
I just upgraded to Xcode 11.4, and now, using Carthage, I am getting this symbol missing when I launch my app.

    s12SwiftyBeaverAAC5LevelO5debugyA2DmFWC

which demangles to 

    $s12SwiftyBeaverAAC5LevelO5debugyA2DmFWC ---> enum case for SwiftyBeaver.SwiftyBeaver.Level.debug(SwiftyBeaver.SwiftyBeaver.Level.Type) -> SwiftyBeaver.SwiftyBeaver.Level

when I had built it with 11.3 the symbol was in there. I am not sure what is going on but it appears to be something caused by the upgrade. 

Message when launching:

     dyld: Symbol not found: _$s12SwiftyBeaverAAC5LevelO5debugyA2DmFWC
     Referenced from: /Users/paulossenbruggen/Library/Developer/CoreSimulator/Devices/30CBF81D-6FE2-43BA-BB20-765106000FDC/data/Containers/Bundle/Application/6F6A34C8-2A31-4424-BEBE-9D7DD9C6E516/DemoProject.app/Frameworks/SystemCore.framework/SystemCore
       Expected in: /Users/paulossenbruggen/Library/Developer/CoreSimulator/Devices/30CBF81D-6FE2-43BA-BB20-765106000FDC/data/Containers/Bundle/Application/6F6A34C8-2A31-4424-BEBE-9D7DD9C6E516/DemoProject.app/Frameworks/SwiftyBeaver.framework/SwiftyBeaver
     in /Users/paulossenbruggen/Library/Developer/CoreSimulator/Devices/30CBF81D-6FE2-43BA-BB20-765106000FDC/data/Containers/Bundle/Application/6F6A34C8-2A31-4424-BEBE-9D7DD9C6E516/DemoProject.app/Frameworks/SystemCore.framework/SystemCore

**Comment by skreutzberger** [comment]
Can you reproduce it with a new app?

**Comment by possen** [comment]
Thanks, yeah I created a small app with just logging and it works so likely something in the build chain.

**Comment by possen** [comment]
I closed this, but there is something definitely up with 11.4. I was unable to reproduce with a small project, but if I use 11.3 it works. There is something with the way dynamic library resolution is happening. Where an embedded library that refers to another dynamic library it, does not find the symbol.

**Comment by IsaiahJTurner** [comment]
This project has been potentially breached and your app may be exposing private information. See issue #453

**Comment by skreutzberger** [comment]
@IsaiahJTurner WTF is just wrong with you abusing the Github notification system? I have reported you to Github for spam. If you want to advertise for a company or project then please do it the normal way and leave the SwiftyBeaver contributors alone. NOTHING HAS BEEN BREACHED.
