### ISSUE TITLE
1.9.0 - Log format only applies to the first ever log in an app launch

### ISSUE THREAD

**Issue by MeteC** [SwiftyBeaver/SwiftyBeaver#389]
Installed SwiftyBeaver v1.9.0 using Swift Packages.

Just copy pasted the SwiftyBeaver [setup notes](https://github.com/SwiftyBeaver/SwiftyBeaver#usage) to see it run, and only the very first log call I make has the nice default formatting with the datestamp and coloured heart.

My log looks like this:
```
11:44:49.690 💜 VERBOSE AppDelegate.setupBeaverLogging():44 - not so important
DEBUG: something to debug
INFO: a nice information
WARNING: oh no, that won’t be good
ERROR: ouch, an error did occur!
VERBOSE: 123
INFO: -123.45678
WARNING: 2020-04-02 09:44:49 +0000
ERROR: ["I", "like", "logs!"]
ERROR: ["address": "7 Beaver Lodge", "name": "Mr Beaver"]
DEBUG: age 123
INFO: my data [1, "a", 2]
```

AppDelegate looks like this:
```
    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        
        setupBeaverLogging()
        
        return true
    }
    
    private func setupBeaverLogging() {
        // add log destinations. at least one is needed!
        let console = ConsoleDestination()  // log to Xcode Console
        let file = FileDestination()  // log to default swiftybeaver.log file
        let cloud = SBPlatformDestination(appID: "foo", appSecret: "bar", encryptionKey: "123") // to cloud
        
        // add the destinations to SwiftyBeaver
        log.addDestination(console)
        
        // Now let’s log!
        log.verbose("not so important")  // prio 1, VERBOSE in silver
        log.debug("something to debug")  // prio 2, DEBUG in green
        log.info("a nice information")   // prio 3, INFO in blue
        log.warning("oh no, that won’t be good")  // prio 4, WARNING in yellow
        log.error("ouch, an error did occur!")  // prio 5, ERROR in red
        
        // log anything!
        log.verbose(123)
        log.info(-123.45678)
        log.warning(Date())
        log.error(["I", "like", "logs!"])
        log.error(["name": "Mr Beaver", "address": "7 Beaver Lodge"])
        
        // optionally add context to a log message
        console.format = "$L: $M $X"
        log.debug("age \(123)")  // "DEBUG: age 123"
        log.info("my data", context: [1, "a", 2]) // "INFO: my data [1, \"a\", 2]"
    }
```

As a side-note - from the setup notes, the line `log.debug("age", 123)` has compilation error `"Cannot convert value of type 'Int' to expected argument type 'String'"`, so I changed it to `debug("age \(123)")` as above. (Could open this as a separate issue...)

**Comment by skreutzberger** [comment]
The one with the hearts I could not reproduce. All our tests relating that are still working and I also tried it now with the 1.9.0 and the latest Xcode. Is it  happening for you with the latest Xcode, too?

Relating the syntax error: good catch! The example should show the use of the `context` parameter but it was forgotten to be added. I fixed the `README` and now it is in. Thank you!

**Comment by MeteC** [comment]
Yes Xcode 11.4.

I'm bringing SwiftyBeaver into an existing project. I'll do a quick sanity check and make a new project and try it there too.. 

Oh incidentally my project supports back to iOS 12.2, don't know if that would make a difference (the device I'm testing it on has iOS 13.3)

**Comment by MeteC** [comment]
Experiencing the same behaviour in a brand new project :-(
Got the same behaviour with SwiftyBeaver 1.8.4 as well.
Tried running on device with iOS 13.3, also on Simulator with iOS 13.4 - same results

Here's a link to that xcode project, I wonder if you get the same results as me...
https://github.com/MeteC/failing_beaver_format

If there's any more info I can give you, let me know!

**Comment by skreutzberger** [comment]
Thanks for the example. I found the issue, it is the line `console.format = "$L: $M $X"` which is executed before all former log messages reached output. That line also changes the format of the output to not include colored hearts anymore.

SwiftyBeaver is running on a low-prio thread so the output of logs is asynchronous and may "fall behind" your sequential code which is running on the main thread.

To get color back into the custom log output you could replace the line `console.format = "$L: $M $X"` with ` console.format = "$C$L$c: $M $X"`.

Please have a look at https://docs.swiftybeaver.com/article/20-custom-format if you are interested in custom formatting.

**Comment by MeteC** [comment]
Ah great! Thanks, I noticed while poking around that the console.format setting was asynchronous, but missed the fact that my code was setting that value later in the setup! Ironically if I'd just removed all the sample code it would've worked perfectly. 👍

**Comment by IsaiahJTurner** [comment]
This project has been potentially breached and your app may be exposing private information. See issue #453

**Comment by skreutzberger** [comment]
@IsaiahJTurner WTF is just wrong with you abusing the Github notification system? I have reported you to Github for spam. If you want to advertise for a company or project then please do it the normal way and leave the SwiftyBeaver contributors alone. NOTHING HAS BEEN BREACHED.
