### ISSUE TITLE
Logical error  in PKCS7.add()

### ISSUE THREAD

**Issue by ladeiko** [SwiftyBeaver/SwiftyBeaver#390]
`
private struct PKCS7 {

    func add(bytes: [UInt8], blockSize: Int) -> [UInt8] {
        let padding = UInt8(blockSize - (bytes.count % blockSize))
        var withPadding = bytes
        if padding == 0 { 
            // If the original data is a multiple of N bytes, then an extra block of bytes with value N is added.
            for _ in 0..<blockSize {
                withPadding.append(contentsOf: [UInt8(blockSize)])
            }
        } else {
            // The value of each added byte is the number of bytes that are added
            for _ in 0..<padding {
                withPadding.append(contentsOf: [UInt8(padding)])
            }
        }
        return withPadding
    }
`

padding will never be 0... therefore 'if padding == 0' will never be executed.

For zero-length input additional block will be added

**Comment by skreutzberger** [comment]
good catch! Do you want fix it yourself by opening a PR?

**Comment by ladeiko** [comment]
> good catch! Do you want fix it yourself by opening a PR?

I think it's possible but, main question is: for zero-length input still add padding with blockSize?

**Comment by skreutzberger** [comment]
what is the most secure solution?

**Comment by ladeiko** [comment]
> what is the most secure solution?

Logically, there is no need to add padding for zero-length, but....

**Comment by skreutzberger** [comment]
but?

**Comment by ladeiko** [comment]
Checked... Padding should exist even for empty data...

**Comment by ladeiko** [comment]
Final version should be:

`func add(bytes: [UInt8], blockSize: Int) -> [UInt8] {
    let padding = UInt8(blockSize - (bytes.count % blockSize))
    var withPadding = bytes
    // The value of each added byte is the number of bytes that are added
    for _ in 0..<padding {
        withPadding.append(contentsOf: [UInt8(padding)])
    }
    return withPadding
}`

Will you apply changes? Or should i make the PR?

**Comment by skreutzberger** [comment]
Please create a PR to have you as contributor :) - thank you!

**Comment by IsaiahJTurner** [comment]
This project has been potentially breached and your app may be exposing private information. See issue #453

**Comment by skreutzberger** [comment]
@IsaiahJTurner WTF is just wrong with you abusing the Github notification system? I have reported you to Github for spam. If you want to advertise for a company or project then please do it the normal way and leave the SwiftyBeaver contributors alone. NOTHING HAS BEEN BREACHED.
