### ISSUE TITLE
Log memory adresse 

### ISSUE THREAD

**Issue by gregoireLem** [SwiftyBeaver/SwiftyBeaver#393]
Why sometimes memory adresse are log and sometimes not ?
020-03-25 19:10:24.500 **_0x2829d6c40_** INFO:

Thanks

**Comment by skreutzberger** [comment]
the position of `0x2829d6c40`  looks like a thread. Sometimes a thread has no name and SwiftyBeaver uses the memory address instead.

Here is the line where it is done:
https://github.com/SwiftyBeaver/SwiftyBeaver/blob/master/Sources/SwiftyBeaver.swift#L75

**Comment by gregoireLem** [comment]
Thanks a lot

**Comment by IsaiahJTurner** [comment]
This project has been potentially breached and your app may be exposing private information. See issue #453

**Comment by skreutzberger** [comment]
@IsaiahJTurner WTF is just wrong with you abusing the Github notification system? I have reported you to Github for spam. If you want to advertise for a company or project then please do it the normal way and leave the SwiftyBeaver contributors alone. NOTHING HAS BEEN BREACHED.
