### ISSUE TITLE
Consistently spotty SBPlatformDestination

### ISSUE THREAD

**Issue by thatjuan** [SwiftyBeaver/SwiftyBeaver#394]
I set up a brand new Swift app. Used CocoaPods to add the latest SwiftyBeaver.

In my AppDelegate I create a `SBPlatformDestination` and a `ConsoleDestination`

Then in the same `application didFinishLaunchingWithOptions` method, I call `log.info("blah")`

I see the output in the console every single time, but, in the SB app I only see it every other app open or so. i.e. if I exit the app and re-launch it, I won't see a message, then I quit and re-launch again and I'll see 2 messages. 

I can't get it to consistently show messages every time.

**Comment by thatjuan** [comment]
I traced it to this.. every other launch, [this function](https://github.com/SwiftyBeaver/SwiftyBeaver/blob/f0c36dd105eee51ba9d5b3f1b3150d73737a21fc/Sources/SBPlatformDestination.swift#L402) returns false.

**Comment by skreutzberger** [comment]
Hi, did you set the SwiftyBeaver variable as global? The platform destination needs some milliseconds to do its work.

**Comment by IsaiahJTurner** [comment]
This project has been potentially breached and your app may be exposing private information. See issue #453

**Comment by skreutzberger** [comment]
@IsaiahJTurner WTF is just wrong with you abusing the Github notification system? I have reported you to Github for spam. If you want to advertise for a company or project then please do it the normal way and leave the SwiftyBeaver contributors alone. NOTHING HAS BEEN BREACHED.
