### ISSUE TITLE
dyld: Symbol not found: __T0SbMa

### ISSUE THREAD

**Issue by CodySchrank** [SwiftyBeaver/SwiftyBeaver#395]
I had an [issue](https://github.com/CodySchrank/gSwitch/issues/50) created on my app for what appears to be a build path issue with swiftybeaver.

The framework is linking out of date dynamic libraries if the user has an older version of xcode installed.

I'm not super familiar with the build process of xcode but I have 2 other frameworks installed and they do not have this issue.

The problem is specifically that the `project.pbxproj` has the line `LD_RUNPATH_SEARCH_PATHS = "$(inherited) $(TOOLCHAIN_DIR)/usr/lib/swift/macosx";`.  

Removing  `$(TOOLCHAIN_DIR)/usr/lib/swift/macosx` solves this issue according to this thread [here](https://forums.developer.apple.com/thread/115551)

Thanks.

**Comment by CodySchrank** [comment]
I pulled SwiftyBeaver and removed the line `$(TOOLCHAIN_DIR)/usr/lib/swift/macosx` and rebuilt the framework.  It was confirmed to be the issue.

**Comment by CodySchrank** [comment]
I added a PR for the issue.

**Comment by IsaiahJTurner** [comment]
This project has been potentially breached and your app may be exposing private information. See issue #453

**Comment by skreutzberger** [comment]
@IsaiahJTurner WTF is just wrong with you abusing the Github notification system? I have reported you to Github for spam. If you want to advertise for a company or project then please do it the normal way and leave the SwiftyBeaver contributors alone. NOTHING HAS BEEN BREACHED.
