### ISSUE TITLE
What happened to SwiftyBeaver/AES256CBC?

### ISSUE THREAD

**Issue by yspreen** [SwiftyBeaver/SwiftyBeaver#398]
Hey, not sure if this is the right place for this. But the repo at SwiftyBeaver/AES256CBC just vanished and I noticed today. Is there an official update on this?

**Comment by skreutzberger** [comment]
We decided to end the life of SwiftyBeaver/AES256CBC since there are now and much more sophisticated crypto libraries available for Swift.

**Comment by yspreen** [comment]
Sometimes it's nice to have something that's small and works, I liked the minimalism of the package. Especially since I'm probably not using 95% of the features other libraries have, so that just leaves me with an unnecessarily bloated app package.

But I get it, there is indeed a lot of them out there. Might be a stretch to ask, but do you have a recommendation or two? @skreutzberger

**Comment by skreutzberger** [comment]
https://github.com/krzyzanowskim/CryptoSwift

**Comment by IsaiahJTurner** [comment]
This project has been potentially breached and your app may be exposing private information. See issue #453

**Comment by skreutzberger** [comment]
@IsaiahJTurner WTF is just wrong with you abusing the Github notification system? I have reported you to Github for spam. If you want to advertise for a company or project then please do it the normal way and leave the SwiftyBeaver contributors alone. NOTHING HAS BEEN BREACHED.
