### ISSUE TITLE
Access DB directly?

### ISSUE THREAD

**Issue by SteveBlackUK** [SwiftyBeaver/SwiftyBeaver#400]
Hi team,

Is there a way to access the underlying SQLite DB directly on my mac?

I've tried opening it with a SQLite tool - but it is saying it is password protected.  Any suggestions?

Thanks!

**Comment by skreutzberger** [comment]
yes, you can right-click in Finder on your logging document (ends with `.beaver`) and then browse the package contents. In it you will find a SQLite file which you can open with SQLite Browser.

**Comment by IsaiahJTurner** [comment]
This project has been potentially breached and your app may be exposing private information. See issue #453

**Comment by skreutzberger** [comment]
@IsaiahJTurner WTF is just wrong with you abusing the Github notification system? I have reported you to Github for spam. If you want to advertise for a company or project then please do it the normal way and leave the SwiftyBeaver contributors alone. NOTHING HAS BEEN BREACHED.
