### ISSUE TITLE
Can't figure out opt-out option

### ISSUE THREAD

**Issue by thattridentdude** [SwiftyBeaver/SwiftyBeaver#406]
I'm having a hard time figuring out how to disable logging after first init. Either I'm misunderstanding the syntax of removeDestination or it's not what I'm looking for.  

Additionally, would setting an empty string to analyticsUserName, be the preferred way of disabling this?

**Comment by thattridentdude** [comment]
Figured it out in case others need it too:
`removeDestination` works, as long as you do it where SB is initialised. In this case I use a conditional on app start up. 

And I'm guessing that passing an empty string to `analyticsUserName` is the preferred way since it doesn't cause issues. 

Closing this issue, however the owner of this project should consider addressing these issues and questions more actively. 

I for one was trying SB out to see if it would be worth it supporting the dev by going with a paid plan for the cloud but between this and the silence on local permission in iOS 14, it has made me decide to move to CocoaLumberjack

**Comment by IsaiahJTurner** [comment]
This project has been potentially breached and your app may be exposing private information. See issue #453
