### ISSUE TITLE
Change file URL

### ISSUE THREAD

**Issue by gregoireLem** [SwiftyBeaver/SwiftyBeaver#407]
Is it possible to rename the log file path after its initialization ?

I try to rename it with :

fileSwiftBeaver = FileDestination(logFileURL : myNewURL)

but this this not working, the first URL is still used. Even if fileSwiftBeaver.logFileURL shows the new URL, it is still the initial one that is used.

thanks

**Comment by TorchedPoseidon** [comment]
You can change it as follows, assuming you've got it set up in a basic way as per the instructions:  
In `AppDelegate` after `func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {` :

`let file = FileDestination() `
`file.logFileURL = FileManager.default.urls(for: .cachesDirectory, in: .userDomainMask).first?.appendingPathComponent("/MyPreferredLogDirectory/MyPreferredLogName.log", isDirectory: false)`


Or in your example it would be: 
`FileDestination().logFileURL = myNewURL`

**Comment by gregoireLem** [comment]
Ok it works thanks

**Comment by mikeumus** [comment]
This hasn't worked for me. Even `fileSwiftBeaver = FileDestination()` doesn't work for me:

``` swift 

import SwiftyBeaver


@NSApplicationMain
class AppDelegate: NSObject, NSApplicationDelegate {
  
  let log = SwiftyBeaver.self
  let swiftyBeaver_platform = SBPlatformDestination(appID: Secrets.Platform.appID, appSecret: Secrets.Platform.appSecret, encryptionKey: Secrets.Platform.encryptionKey)
  let swiftyBeaver_file = FileDestination()

  func applicationWillFinishLaunching(_ notification: Notification) {
    
    swiftyBeaver_file.logFileURL = FileManager.default.urls(for: .cachesDirectory, in: .userDomainMask).first?.appendingPathComponent("/SwiftyBeaver.log", isDirectory: false)

    log.addDestination(swiftyBeaver_file)


...
```

I tried creating an empty `SwiftyBeaver.log` file for it ahead of time but that didn't help.

**Comment by IsaiahJTurner** [comment]
This project has been potentially breached and your app may be exposing private information. See issue #453
