### ISSUE TITLE
how can i log to terminal like os_log

### ISSUE THREAD

**Issue by tospery** [SwiftyBeaver/SwiftyBeaver#408]

**Comment by skreutzberger** [comment]
The ConsoleDestination is doing exactly that :)

**Comment by IsaiahJTurner** [comment]
This project has been potentially breached and your app may be exposing private information. See issue #453

**Comment by skreutzberger** [comment]
@IsaiahJTurner WTF is just wrong with you abusing the Github notification system? I have reported you to Github for spam. If you want to advertise for a company or project then please do it the normal way and leave the SwiftyBeaver contributors alone. NOTHING HAS BEEN BREACHED.
