### ISSUE TITLE
iOS 14 support 

### ISSUE THREAD

**Issue by preobrazhenskiy** [SwiftyBeaver/SwiftyBeaver#409]
Hi, Using Xcode Version 12.0 beta (12A6159)

I get the problem as described in the screenshot. 

Did clean of the derived data, using pod version 1.9.1

I know that iOS 14 is still in beta but is this a known issue?

<img width="877" alt="Screenshot 2020-07-09 at 14 56 41" src="https://user-images.githubusercontent.com/54708524/87037206-896ca080-c1f4-11ea-96f2-771af3c0350a.png">

**Comment by shtnkgm** [comment]
related issue

Undefined symbol: type metadata for Swift._StringObject.Variant
https://developer.apple.com/forums/thread/649918

**Comment by preobrazhenskiy** [comment]
Thanks for a quick response. Lets try it out when Xcode issues are resolved.

**Comment by mozeryansky** [comment]
I'm on beta 2 and I don't see this issue

**Comment by preobrazhenskiy** [comment]
Beta 2, same issue here.

**Comment by preobrazhenskiy** [comment]
I found that Xcode beta 4 does not produce the error anymore, so will close it.

**Comment by IsaiahJTurner** [comment]
This project has been potentially breached and your app may be exposing private information. See issue #453
