### ISSUE TITLE
Does SwiftyBeaver come out of the box with an adapter for swift-log?

### ISSUE THREAD

**Issue by ratkins** [SwiftyBeaver/SwiftyBeaver#411]
I started my project using the [official Swift swift-log logging API](https://github.com/apple/swift-log), but now I want something a little more sophisticated (console and file output, and automatically shipping the logs off to a Mac app in real time would be very handy.)

It'd be super neat if I could just swap out the implementation to SwiftyBeaver and leave all my log call sites intact, but I can't find anywhere in the documentation that SwiftyBeaver can act as an implementation for `swift-log`. Am I missing it, or is it not implemented?

**Comment by skreutzberger** [comment]
no but feel free to contribute!

**Comment by IsaiahJTurner** [comment]
This project has been potentially breached and your app may be exposing private information. See issue #453

**Comment by skreutzberger** [comment]
@IsaiahJTurner WTF is just wrong with you abusing the Github notification system? I have reported you to Github for spam. If you want to advertise for a company or project then please do it the normal way and leave the SwiftyBeaver contributors alone. NOTHING HAS BEEN BREACHED.
