### ISSUE TITLE
Don't trust SwiftyBeaver encryption

### ISSUE THREAD

**Issue by IsaiahJTurner** [SwiftyBeaver/SwiftyBeaver#414]
This library seems to imply that your logs are securely encrypted but that is not the case. The encryption key is stored in the app binary. Anyone with access to the app can easily decrypt the logs. In the case that you use SwiftyBeaver in an App Store release, the encryption is simply a false sense of security and might as well not be there. The encryption protocol used currently is symmetric and it should be switched to an asymmetric encryption scheme. Preferably, RSA.

**Comment by skreutzberger** [comment]
It is the same as secure as storing any API key or token in an app.
