### ISSUE TITLE
How to Use GoogleCloudDestination

### ISSUE THREAD

**Issue by xanderdunn** [SwiftyBeaver/SwiftyBeaver#417]
First, what should `serviceName` be set to? Is this just an arbitrary string used to identify the source of the log by GCP?

Beyond this, I haven't been able to get any of my logs to show up on GCP Cloud Logging. The instance is running on GCP and has Logging permissions. I don't see the `GoogleCloudDestination` gathering service account credentials or establishing a connection with GCP. How is it expected to transmit the logs to GCP?

I see it cluttering up my stdout with the json strings from [this](https://github.com/SwiftyBeaver/SwiftyBeaver/blob/master/Sources/GoogleCloudDestination.swift#L64) print call, but otherwise I don't see how it's expected to be picked up by GCP Cloud Logging.

**Comment by skreutzberger** [comment]
The printed JSON should be compatible with Stackdriver's JSON format. If that is not the case then we may need to update the format.

**Comment by xanderdunn** [comment]
Thanks @skreutzberger.  I don't know that there's anything wrong with the JSON, I don't understand how it's meant to upload to Google Cloud Logging. The only output I see is the `print()` statement, I don't see any kind of network requests. Is there an excepted behavior where a GCP instance automatically uploads any stdout that is in the right JSON format to Cloud Logging? Based on the README's "automatic server-side Swift logging when hosted on Google Cloud Platform," I was expecting it to actually deliver the logs across the network (GCP instance) -> (GCP Logging)?

**Comment by skreutzberger** [comment]
GCP Logging is a more fancy word for "read JSON from stdout and put it into Stackdriver" :D

**Comment by xanderdunn** [comment]
@skreutzberger This has not been my experience running the `GoogleCloudDestination` on several GCP instances that have Google Cloud Logging enabled, nor is it my experience with Python logging libraries that have successfully logged to GCP Cloud Logging. Do you have any documentation links on how sending the JSON to stdout is expected to work with Cloud Logging? [Stackdriver is a deprecated name](https://cloud.google.com/products/operations).

I believe [this](https://cloud.google.com/run/docs/logging#container-logs) is the reference. I haven't been able to get the stdout logging to show up in Cloud Logging, but let's assume it's possible. As it stands it's unusable. At least have it log to a destination like `/var/log/`? Cluttering up stdout with JSON is unreadable.

**Comment by xanderdunn** [comment]
The link I sent above is specific to [Cloud Run](https://cloud.google.com/run), which is for containerized runs like Docker.

The SwiftyBeaver implementation of GCP Cloud Logging is not working as expected, or the README should be specific that it only applies to containerized GCP runs. `GoogleCloudDestination` has no effect when not running inside a Docker container, unlike the [Logging client libraries in other languages](https://cloud.google.com/logging/docs/reference/libraries).

**Comment by IsaiahJTurner** [comment]
This project has been potentially breached and your app may be exposing private information. See issue #453

**Comment by skreutzberger** [comment]
@IsaiahJTurner What a troll. WTF is just wrong with you abusing the Github notification system? I have reported you to Github for spam. If you want to advertise for a company or project then please do it the normal way and leave the SwiftyBeaver contributors alone. SWIFTYBEAVER HAS NOT BEEN BREACHED. SwiftyBeaver is an open-source framework and its used encryption is public, known and trusted since several years. Feel free to contribute source code which makes it safer from your point of view and the contributors and I will consider merging it.
