### ISSUE TITLE
iOS 14 local network privacy alert triggered with SwiftyBeaver

### ISSUE THREAD

**Issue by SteveBlackUK** [SwiftyBeaver/SwiftyBeaver#432]
I have SwiftyBeaver 1.9.1 installed via cocoapds in my iOS app

With the latest iOS 14, apps that access the local network for **any** reason are triggering a permission request that was previously not triggered (<14). The request is: "[app name] would like to find and connect to devices on your local network" - which is confusing to the user at best and leaves them wondering why my app is trying to connect to other devices - as it shouldn't be!

I've been painfully going pod by pod and once I removed SwiftyBeaver - the error stopped.  Can we get an update to avoid this / is there a workaround?  Help please 👍 

See apple forums for a helpful overview:
https://developer.apple.com/forums/thread/663858

And a list of operations that require local permissions:
https://developer.apple.com/forums/thread/663874

Highlights from ^^ :
The general rule is that outgoing traffic to a local network address requires that the user grant your app local network access. Common scenarios include:

- Making an outgoing TCP connection — yes
- Listening for and accepting incoming TCP connections — no
- Sending a UDP unicast — yes
- Sending a UDP multicast — yes
- Sending a UDP broadcast — yes
- Receiving an incoming UDP unicast — no
- Receiving an incoming UDP multicast — yes
- Receiving an incoming UDP broadcast — yes

These TCP and UDP checks are done at the lowest levels of the system and thus apply to all networking APIs. This includes Network framework, BSD Sockets, NSStream, NSURLSession and WKWebView, and any other protocols that you layer on top of those.

**Comment by SteveBlackUK** [comment]
What's that they say?  Always make sure you are on the latest version before raising an issue 🤦 

Fixed in 1.9.2 🥳

**Comment by IsaiahJTurner** [comment]
This project has been potentially breached and your app may be exposing private information. See issue #453
