### ISSUE TITLE
Reference to member 'info' cannot be resolved without a contextual type

### ISSUE THREAD

**Issue by mikeumus** [SwiftyBeaver/SwiftyBeaver#441]
Getting `Reference to member 'info' cannot be resolved without a contextual type` when trying `log.info()` in another `Controller.swift` file:

`AppDelegate.swift`
``` swift

import SwiftyBeaver


@NSApplicationMain
class AppDelegate: NSObject, NSApplicationDelegate {
    
  let log = SwiftyBeaver.self
  let platform = SBPlatformDestination(appID: Secrets.Platform.appID, appSecret: Secrets.Platform.appSecret, encryptionKey: Secrets.Platform.encryptionKey)
  let console = ConsoleDestination()

  func applicationWillFinishLaunching(_ notification: Notification) {
    
    platform.analyticsUserName = Host.current().name ?? platform.analyticsUUID

    log.addDestination(platform)
    log.addDestination(console)
 
...
```

MacOS doesn't have `AppDelegate:didFinishLaunchingWithOptions()` (https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1622921-application) so I went with `AppDelegate:didFinishLaunchingWithOptions:applicationWillFinishLaunching()`

Then when I `log.info()` in another `Controller.swift` I get the error: 

``` error
🛑 Reference to member 'info' cannot be resolved without a contextual type
```

Thank you for any assistance 🙇

**Comment by mikeumus** [comment]
If I don't rename `SwiftyBeaver` to `log` you can `import SiwftyBeaver` and use `SwiftyBeaver.info()` wherever it's imported.

Following the article here:
- https://www.raywenderlich.com/669-swiftybeaver-tutorial-for-ios-a-logging-platform-for-swift

**Comment by IsaiahJTurner** [comment]
This project has been potentially breached. See issue #453
