### ISSUE TITLE
Platform cloud logs stop spooling

### ISSUE THREAD

**Issue by smileatom** [SwiftyBeaver/SwiftyBeaver#444]
Is the platform cloud destination down?  I have 2 apps and after logging continuously to the platform and spooling to the mac app after several hours they simply stop logging from the cloud.  If I run the app directly in xcode I see no errors from swifty beaver.

Restarting the apps does nothing, restarting swifty beaver does nothing.  I did restart my mac yesterday and then the mac apps started logging again and now today they stopped showing logs again.

While I like the tool, Im not sure I can pay monthly for a logging service thats not working.  Im in release mode and this is troubling.

**Comment by smileatom** [comment]
Is there a way to troubleshoot what might be causing this?

**Comment by mvarie** [comment]
It looks like Swiftybeaver has been abandoned, in practice.

Last commit (and last release) was November 2020.
Last tweet from @swifybeaver, April 2020. 
The Mac app is slow, it often hangs and hasn't been updated since 2016.

**Comment by smileatom** [comment]
Any suggestions on an alternative?

**Comment by mvarie** [comment]
@smileatom I haven't quite found something that offers what SwiftyBeaver supposedly offers, with similar pricing.
The alternatives I've seen are, for my use case, too expensive - but I don't know your use case.
The most likely substitute for me will be Bugfender, but this is not an endorsement nor a recommendation - I haven't decided yet.
An alternative might be https://appcenter.ms - which is a broader product with included free analytics.

**Comment by smileatom** [comment]
Im just going to log to cloudwatch on AWS its free more or less

**Comment by IsaiahJTurner** [comment]
This project has been potentially breached. See issue #453
