### ISSUE TITLE
Log file maximun size

### ISSUE THREAD

**Issue by siempay** [SwiftyBeaver/SwiftyBeaver#447]
Hi, Thanks for this very helpful tool. 
I only have one issue that is I have to upload the log files myself to our servers. And the server has a limit to the uploaded file size (1 Mb).

So is there a way that I can do to limit the file size so it just creates another file and so on ?

**Comment by skreutzberger** [comment]
there is currently a pull request in the works which is implementing that functionality

**Comment by siempay** [comment]
Ok, if not, I would make a pull request for it, cause I already fixed it on my side.
Thannk you

**Comment by skreutzberger** [comment]
please have a look at https://github.com/SwiftyBeaver/SwiftyBeaver/pull/442 - maybe you want to contribute to that PR?

**Comment by siempay** [comment]
I looked into it, and it is not what I was looking for.

I want to keep all log files on local but every file has a max size. so what I did is removing the `var fileURL: URL`  and replace it with a function that the user should implement to return the appropriate URL. (i.e `func getLogURL(currentURL: URL?) -> URL`)

And the user will then check on the current URL if it reached the max size or any other condition before returning a new URL or just the same current URL.

I did this because I need to upload log files to my server if I want to, using APN, for debugging perposes. 

If this feature is needed alongside the one in #442.
I can prepare my PR. let me know. thank you

**Comment by skreutzberger** [comment]
it could be risky to never delete a file so I would advise not to go that route. I mean we could add as value to #442  which says `noOfLogFiles = -1` or so which means no limit but then we really need to educate the developer to be careful with it.

**Comment by siempay** [comment]
Ok, for me, I keep references for files and I delete them myself. So I see that would be a problem because not everyone will want to do that. 
I'll looking into #442 to see how we can combine this with that in a less error prone way

**Comment by skreutzberger** [comment]
super. in the meantime I am closing this issue so that we can continue the discussion on 442

**Comment by IsaiahJTurner** [comment]
This project has been potentially breached. See issue #453

**Comment by skreutzberger** [comment]
@IsaiahJTurner What a troll. WTF is just wrong with you abusing the Github notification system? I have reported you to Github for spam. If you want to advertise for a company or project then please do it the normal way and leave the SwiftyBeaver contributors alone. SWIFTYBEAVER HAS NOT BEEN BREACHED. SwiftyBeaver is an open-source framework and its used encryption is public, known and trusted since several years. Feel free to contribute source code which makes it safer from your point of view and the contributors and I will consider merging it.
