### ISSUE TITLE
dyld: dependent dylib '@rpath/SwiftyBeaver.framework/SwiftyBeaver' not found

### ISSUE THREAD

**Issue by pfcstyle** [SwiftyBeaver/SwiftyBeaver#448]
I try to use SwiftyBeaver in my custom framework by cocoapods:

```
target 'sparklib' do
  use_frameworks!
  project 'sparklib/sparklib.xcodeproj'
  # Write sparklib dependencies here
  pod 'SwiftyBeaver'
  target 'sparklibTests' do
  end
end
```

sparklib is a custom framework,  when i embed it into a app and run the app, it crashed:

dyld: dependent dylib '@rpath/SwiftyBeaver.framework/SwiftyBeaver' not found for '/private/var/containers/Bundle/Application/DC32C0B7-A752-4055-82D7-F83DCEBA4EE5/spark.app/Frameworks/sparklib.framework/sparklib', tried but didn't find: '/private/var/containers/Bundle/Application/DC32C0B7-A752-4055-82D7-F83DCEBA4EE5/spark.app/Frameworks/SwiftyBeaver.framework/SwiftyBeaver' '/private/var/containers/Bundle/Application/DC32C0B7-A752-4055-82D7-F83DCEBA4EE5/spark.app/Frameworks/sparklib.framework/Frameworks/SwiftyBeaver.framework/SwiftyBeaver' '/private/var/containers/Bundle/Application/DC32C0B7-A752-4055-82D7-F83DCEBA4EE5/spark.app/../../Frameworks/SwiftyBeaver.framework/SwiftyBeaver' '@rpath/SwiftyBeaver.framework/SwiftyBeaver' '/System/Library/Frameworks/SwiftyBeaver.framework/SwiftyBeaver'

**Comment by pfcstyle** [comment]
Sorry, it's my fault. I should put the SwiftyBeaver pod into the app's target, too.  Because the dynamic library don't contain third dependencies.

**Comment by IsaiahJTurner** [comment]
This project has been potentially breached. See issue #453
