### ISSUE TITLE
Check if still works under Carthage & Cocoapods

### ISSUE THREAD

**Issue by skreutzberger** [SwiftyBeaver/SwiftyBeaver#45]
@davidrothera I changed the repo sources in 92052b263b51

Can you please check if it still works flawlessly under Cocoapods and Carthage? The README I updated, too.

Thank you!

**Comment by davidrothera** [comment]
# Checked
* Carthage :white_check_mark: 
* CocoaPods :white_check_mark:
* Swift PM :white_check_mark:

**Comment by skreutzberger** [comment]
Thank you!

close #45
