### ISSUE TITLE
SwiftyBeaver encryption vulnerability 

### ISSUE THREAD

**Issue by IsaiahJTurner** [SwiftyBeaver/SwiftyBeaver#452]
This library seems to imply that your logs are securely encrypted but that is not the case. The encryption key is stored in the app binary. Anyone with access to the app can easily decrypt the logs. In the case that you use SwiftyBeaver in an App Store release, the encryption is simply a false sense of security and might as well not be there. The encryption protocol used currently is symmetric and it should be switched to an asymmetric encryption scheme. Preferably, RSA.

Storing an encryption key within an app binary is not the same as storing an API key within an app binary. An analogy would be HTTPS. While every web browser views websites using HTTPS, you NEVER expose your SSL certificate to the client. Since SwiftyBeaver encryption relies on publicizing your encryption key, it provides no additional security. Similar to how if an SSL certificate is compromised, HTTPS provides no additional security. You should cease use of SwiftyBeaver immediately if your app may be transmitting sensitive information.

**Comment by IsaiahJTurner** [comment]
If the pull request #451 is not merged (as is or appropriately modified), the Swifty Beaver team is accepting liability for willfully knowing of a vulnerability and failing to resolve it or provide disclosure notices to those affected. This is unlawful in many jurisdictions and I will individually notify each GitHub account of those who have filed issues on this repository so that as many people can be made aware of this risk as possible. Many people may be transmitting sensitive information under a false sense of security in production on the App Store. This could be giving the Swifty Beaver team direct access to HIPPA controlled information, security credentials, and more.

**Comment by IsaiahJTurner** [comment]
Since it appears this company is based in Berlin, this may be considered a data breach under the GDPR.

**Comment by skreutzberger** [comment]
Like any other tool, it is up to the developer to ensure that keys are securely stored inside an application or are downloaded from a trusted source during runtime. Also that all has nothing to do with GDPR. Changing the encryption to asymmetric does not make sense since the developer wants to decrypt the logs. There are many other logging frameworks out there in the market so feel free to pick one which fits you better.
