### ISSUE TITLE
Xcode 12.5

### ISSUE THREAD

**Issue by advatar** [SwiftyBeaver/SwiftyBeaver#455]
Failure on 

public open class FileDestination: BaseDestination {

with 'Duplicate modifier'

I guess open would be enough

**Comment by skreutzberger** [comment]
@advatar can you please create a PR? thanks!

**Comment by gabors** [comment]
@skreutzberger  @advatar PR here https://github.com/SwiftyBeaver/SwiftyBeaver/pull/457

**Comment by skreutzberger** [comment]
fixed and released with today's released version 1.9.4
