### ISSUE TITLE
Xcode 12.5 - Using 'class' keyword for protocol inheritance is deprecated; use 'AnyObject' instead

### ISSUE THREAD

**Issue by gabors** [SwiftyBeaver/SwiftyBeaver#456]
SwiftyBeaver/Sources/Filter.swift:20:30: 

Using 'class' keyword for protocol inheritance is deprecated; use 'AnyObject' instead

**Comment by gabors** [comment]
@skreutzberger ping

**Comment by skreutzberger** [comment]
@gabors do you want to open a PR?

**Comment by gabors** [comment]
@skreutzberger 

https://github.com/SwiftyBeaver/SwiftyBeaver/pull/457

**Comment by skreutzberger** [comment]
included in today's released version 1.9.4
