### ISSUE TITLE
Is it possible to send logs to a HTTP endpoint?

### ISSUE THREAD

**Issue by Ewg777** [SwiftyBeaver/SwiftyBeaver#458]
Thank you for the awesome library @skreutzberger 
Is it possible to send logs to a HTTP endpoint?

**Comment by skreutzberger** [comment]
Yes, you could send logs via POST to `https://api.swiftybeaver.com/api/entries/` but these logs would need to be in a certain format and would need to be end-to-end encrypted using AES256CBC encryption. In this file you find what is sent to that endpoint: https://github.com/SwiftyBeaver/SwiftyBeaver/blob/master/Sources/SBPlatformDestination.swift
