### ISSUE TITLE
Colors not showing in Xcode console

### ISSUE THREAD

**Issue by benjaminhorner** [SwiftyBeaver/SwiftyBeaver#46]
Not that this is actually bothering me as I much rather use the tail method in iTerm, but this is still a bug:
as stated in the title, colors are not showing in the Xcode console. Instead I get the following:

```[2015-12-16 10:25:20.787] AppDelegate.application(_:didFinishLaunchingWithOptions:):103 [fg0,0,255;DEBUG[;: something to debug
[2015-12-16 10:25:20.790] AppDelegate.application(_:didFinishLaunchingWithOptions:):104 [fg0,255,0;INFO[;: a nice information
[2015-12-16 10:25:20.791] AppDelegate.application(_:didFinishLaunchingWithOptions:):105 [fg255,255,0;WARNING[;: oh no, that won’t be good
[2015-12-16 10:25:20.791] AppDelegate.application(_:didFinishLaunchingWithOptions:):106 [fg255,0,0;ERROR[;: ouch, an error did occur!
[2015-12-16 10:25:20.792] AppDelegate.application(_:didFinishLaunchingWithOptions:):109 [fg200,200,200;VERBOSE[;: 123
[2015-12-16 10:25:20.792] AppDelegate.application(_:didFinishLaunchingWithOptions:):110 [fg0,255,0;INFO[;: -123.45678
[2015-12-16 10:25:20.792] AppDelegate.application(_:didFinishLaunchingWithOptions:):111 [fg255,255,0;WARNING[;: 2015-12-16 09:25:20 +0000
[2015-12-16 10:25:20.792] AppDelegate.application(_:didFinishLaunchingWithOptions:):112 [fg255,0,0;ERROR[;: ["I", "like", "logs!"]
[2015-12-16 10:25:20.835] AppDelegate.application(_:didFinishLaunchingWithOptions:):113 [fg255,0,0;ERROR[;: ["address": "7 Beaver Lodge", "name": "Mr Beaver"]```


OSX version: el Capitan
XCode version: 7.2

And thanks for a wonderful tool that rocks my world!

**Comment by davidrothera** [comment]
Reinstall XcodeColors (plugin) and you should be good to go, with updating Xcode plug-ins get screwed up sometimes, it may also be that you have an old version of the plugin enabled.

If you don't want colors at all then you can set the `colored = False` property and you won't have the artefacts from the color codes

**Comment by skreutzberger** [comment]
We updated the XcodeColors plugin some days ago to work also under Xcode 7.2

Please do the following:

1. close Xcode
1. move the XcodeColors plugin from "~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/" to somewhere else because you will download a new one
1. Download our latest built [XcodeColors.xcplugin.zip](https://github.com/SwiftyBeaver/SwiftyBeaver/raw/master/Assets/XcodeColors.xcplugin.zip)
1. Unzip it to "~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/"
1. Restart Xcode (you may need to restart it several times) until a plugin permission dialog appears
1. allow the plugin at Xcode’s permission dialog

Now it should work :)

**Comment by skreutzberger** [comment]
@davidrothera :smile: :+1:

**Comment by benjaminhorner** [comment]
@skreutzberger, @davidrothera: thanks for the (super) quick response. However, I am sorry to say I have tried both your suggestions and none seem to work.
FYI: I did have the latest versions of both the plugin and SwiftyBeaver.

**Comment by davidrothera** [comment]
Plugins can be *very* temperamental, I would check that the plugin is actually being loaded and isn't silently being ignore by Xcode.

If you don't want to disable colors altogether you can try something like the answer [here](http://stackoverflow.com/a/30366096)

**Comment by benjaminhorner** [comment]
@davidrothera: thanks. I actually prefer NOT TO use the XCode console and trail the logs from file :-)
I was mainly reporting the bug for other users who may want to use it.

I will keep you posted if I ever get the colored logs in the console. Thanks for the help.

**Comment by skreutzberger** [comment]
Yeah, long live Terminal app's `tail -f` during development. I share your preference of not using Xcode Console because it is super annoying. I went so extreme and actually deactivated it as output setting in Xcode and am just using it when running SwiftyBeaver tests (to test the Xcode Console output itself).

I normally split my screen’s width 4/5 for Xcode and 1/5 for Terminal app.

Thanks for reporting anyway, please keep us informed about feedback & good luck in making the console :rainbow:

**Comment by davidrothera** [comment]
Sorry I thought you were not getting colors inside Xcode...

We should probably add something to the README about the fact that the colors are only for inside Xcode and that if you want to use the logs outside of Xcode you need to disable them when initialising the class.

**Comment by skreutzberger** [comment]
@davidrothera Maybe I misunderstand you but colors are working in Terminal app, too. The XcodeColors plugin is just necessary for a colored Xcode console. The colors for terminal/shell output automagically work if the shell supports colors (which they do on default I think).

**Comment by davidrothera** [comment]
I was meaning for things where you want to view them as raw text or if you are using a non-color compatible terminal.

**Comment by skreutzberger** [comment]
:+1: Yes, for that case just set `console.colored = false`. It is documented but maybe it is not clear enough?

**Comment by benjaminhorner** [comment]
@both: It is indeed in the XCODE console I do not get the colors. No biggy for me as I totally ignore the Xcode console like @skreutzberger :-)

**Comment by skreutzberger** [comment]
I am just closing it for now because no one else reported the issue since Xcode 7.2 release. Feel free to re-open when needed.

**Comment by LeonardBonfils** [comment]
This issue is still not working for me, even after having done everything that was advised.

**Comment by skreutzberger** [comment]
What Xcode version do you have?

**Comment by LeonardBonfils** [comment]
Xcode 7.3 Beta

**Comment by skreutzberger** [comment]
Thanks! Did it ever work on an older XCode version? And do you use the precompiled version from the SwiftyBeaver repo?

**Comment by LeonardBonfils** [comment]
I just imported it through Cocoapods, didn't do anything else.

**Comment by davidrothera** [comment]
@LeonardBonfils did you install the colors plugin though?

**Comment by LeonardBonfils** [comment]
yup I installed the plug-in from robbiehanson and restart Xcode until it asked to "Load Bundles", which I did. And it still displays the RGB values instead of the actual colours.

**Comment by davidrothera** [comment]
Xcode plugins can be a pain to get working sometimes.

If you Google for an article on Xcode plugins not working there are some steps to help, I am guessing that the plugin is not being loaded.

There is no easy way to see this in the Xcode UI and you have to dig into plist files etc :-1:

**Comment by skreutzberger** [comment]
Yes, Xcode plugin management really sucks. For me it is still not clear how exactly you installed it and from what source.

In case you did not use our prebuilt package, yet please read here:
[https://github.com/SwiftyBeaver/SwiftyBeaver#no-colors](https://github.com/SwiftyBeaver/SwiftyBeaver#no-colors)

**Comment by LeonardBonfils** [comment]
Yeah I checked out that paragraph. Still didn't help unfortunately. I'll just forget this library for now, maybe later :)

**Comment by davidrothera** [comment]
You can always disable colors, which is what I do actually as I don't like colors in my terminal.

```swift
        let console = ConsoleDestination()
        console.colored = false
```

**Comment by LeonardBonfils** [comment]
Yeah I thought about doing that... but as a complete console noob, I was kind of excited about having a nicer UI in my console (with colours)...
