### ISSUE TITLE
How is the SBPlatformDestination supposed to be used?

### ISSUE THREAD

**Issue by dhgelling** [SwiftyBeaver/SwiftyBeaver#460]
Hi,

I'm looking into using the cloud logging for an app, and would like to make sure users can't access each others' log files.
However, in order to actually instantiate the destination, I need to supply the user with my key and secret somehow -- either embedded in the app, or supplied from elsewhere. But this data can be used to get access to all the logs uploaded to the platform from this app, including from other users, so I'm just handing the users the ability to read all logs when I do.

I'm having a hard time figuring out how to do this in a secure way, could you point me in the right direction?

**Comment by skreutzberger** [comment]
Each of your applications should have its own set of app credentials. It consists of an App ID and App Secret. To download the logs you will need to have these app credentials connected to your user account or to a user which is part of your organization (if you have an organization account). Normally you have 1 SwiftyBeaver user which is "owning" the app credentials.
