### ISSUE TITLE
Please fix this warning

### ISSUE THREAD

**Issue by ruiaureliano** [SwiftyBeaver/SwiftyBeaver#462]
Using 'class' keyword for protocol inheritance is deprecated; use 'AnyObject' instead

<img width="533" alt="CleanShot 2021-06-15 at 11 33 16@2x" src="https://user-images.githubusercontent.com/435699/122038475-88ad9880-cdcd-11eb-87e3-7855120d0268.png">

**Comment by skreutzberger** [comment]
Thanks for reporting. What SwiftyBeaver framework version and Xcode Version do you use?

**Comment by FleetPhil** [comment]
I'm getting this warning on my ubuntu build with Swift version 5.5 (Swift version 5.5 (swift-5.5-RELEASE) Target: aarch64-unknown-linux-gnu) and SwiftyBeaver 1.9.3
