### ISSUE TITLE
No file output on Ubuntu

### ISSUE THREAD

**Issue by FleetPhil** [SwiftyBeaver/SwiftyBeaver#470]
I can't get SB to log to a file from a program on Ubuntu - the console output works fine but if I try and log to a file no output file is created. I've created a simple test program to try and isolate the problem with a couple of alternatives, one using the default and one a named file...

Test code:
```swift
import Foundation
import SwiftyBeaver

let log = SwiftyBeaver.self

let logFormat = "$Dyyyy-MM-dd HH:mm:ss $d $N.$F:$l $L: $M"
let console = ConsoleDestination()
console.format = logFormat
log.addDestination(console)
log.info("Console complete")

let file1 = FileDestination()
file1.format = logFormat
file1.syncAfterEachWrite = true
file1.asynchronously = false
print("File 1: \(file1.logFileURL!)")
log.addDestination(file1)
log.info("File 1 complete")

let file2 = FileDestination(logFileURL: URL(fileURLWithPath: "debug.log"))
file2.syncAfterEachWrite = true
file2.format = "$d $N.$F:$l $L: $M"
file2.asynchronously = false
print("File 2: \(file2.logFileURL!)")
log.addDestination(file2)
log.info("File 2 Complete")
```

Output from program run:
```
ubuntu@ubuntu:~/Swift/SwiftyTest$ swift run
[0/0] Build complete!
File 1: file:///var/cache/swiftybeaver.log
2021-09-17 15:18:40  main.SwiftyTest():11 INFO: Console complete
File 2: debug.log -- file:///home/ubuntu/Swift/SwiftyTest/
2021-09-17 15:18:40  main.SwiftyTest():20 INFO: File 1 complete
2021-09-17 15:18:40  main.SwiftyTest():29 INFO: File 2 Complete
ubuntu@ubuntu:~/Swift/SwiftyTest$ pwd
/home/ubuntu/Swift/SwiftyTest
ubuntu@ubuntu:~/Swift/SwiftyTest$ ls -l /var/cache | grep *.log
ubuntu@ubuntu:~/Swift/SwiftyTest$ ls -l | grep *.log
ubuntu@ubuntu:~/Swift/SwiftyTest$ 
```

I'm running ubuntu 20.10 and swift version 5.4.1. Packaget dependency is `.package(url: "https://github.com/SwiftyBeaver/SwiftyBeaver.git", .upToNextMajor(from: "1.9.0")),
`

I can't find any reference to this not working and it's pretty basic stuff so I can only assume I'm making some kind of simple error....?

**Comment by itcohorts** [comment]
@FleetPhil Did you ever resolve this? I'm having the same issue on Ubuntu 18.04 with SwiftyBeaver from 1.9.5 
I know that the app can write to /var/log since the app is using a different mechanism to store stats in /var/log.

**Comment by FleetPhil** [comment]
Yes I did resolve it, and for me it was a permission issue
