### ISSUE TITLE
*** -[NSConcreteFileHandle writeData:]: No space left on device

### ISSUE THREAD

**Issue by lixiang1994** [SwiftyBeaver/SwiftyBeaver#475]
<img width="1131" alt="image" src="https://user-images.githubusercontent.com/13112992/142838296-ccc423c4-90d1-4430-8966-9578ee14692f.png">

**Comment by tangzzz-fan** [comment]
This issue still reproduced after version 1.9.6.

**Comment by lixiang1994** [comment]
yes

**Comment by tangzzz-fan** [comment]
Did you upgrade to 1.9.6?
Code base has chaged.
![image](https://user-images.githubusercontent.com/13283499/189060131-d884449b-d822-4a17-bb12-d29cc8b70561.png)

**Comment by lixiang1994** [comment]
1.9.6  iOS 13.4+

**Comment by tangzzz-fan** [comment]
> 
I solve the issue by upgrading the version. You can take a try.

**Comment by lixiang1994** [comment]
The minimum version of my project is IOS 11, 1.9.6 requires the minimum version of ios13.4, I can't use 1.9.6.

**Comment by lixiang1994** [comment]
I don't quite understand why the iOS version should be restricted.
