### ISSUE TITLE
Improvements to filtering in Mac App

### ISSUE THREAD

**Issue by SleekDiamond41** [SwiftyBeaver/SwiftyBeaver#476]
Would it be possible to add date/time filtering to the Mac App associated with this framework? Maybe it's not a big deal for production apps, but while developing applications I think it would be super useful to filter by "date:today" or "after:11am."

Or maybe it would be more ergonomic to just add a field separate from the search bar, with a Date Picker? Then the user could select a date/time or even a range, without having to worry about string interpretations... just asking!

Either way it might be helpful to have a button to "clear logs" even if it just filters out all previous items, rather than deleting anything.

It would also be nice to have some documentation on valid search terms, like "os:" and "from:". Am I missing some document that has that? The closest thing I could find is [this documentation](https://docs.swiftybeaver.com/article/21-filters) about consuming the framework in this repo.

Let me know if this isn't the right place for this question.

Thanks for everything!

**Comment by mvarie** [comment]
@SleekDiamond41 the Mac App has been last updated in 2016, still a legacy Intel binary.
