### ISSUE TITLE
SBPlatformDestination.sendToServerAsync

### ISSUE THREAD

**Issue by BarragaoA** [SwiftyBeaver/SwiftyBeaver#480]
Hello,

I m in the last version of the sdk (1.9.5) and I have the following issue :
![Capture d’écran 2022-01-21 à 10 41 31](https://user-images.githubusercontent.com/86778557/150504289-12879213-38b8-45a5-a77a-e9bfb663947e.png)

Unfortunately I do not know how to reproduce.
Sometimes it is written "Fatal Exception: NSMallocException - Failed to grow buffer" if it can help.

Thanks for your help.
Arnaud

**Comment by BarragaoA** [comment]
Any update ?

**Comment by raomlgh** [comment]
<img width="1033" alt="image" src="https://user-images.githubusercontent.com/11312039/153139492-d5648038-79b3-4a5a-80ac-e2544cbba69a.png">

Can you help me？

**Comment by BarragaoA** [comment]
Actually, I did not success to reproduce. It happens on 8 users on our production app but it happens very often (238 times during the last 30days). I do not find recent logs from these users on SB application. 
All I have to help you is maybe this screen but I dont not think it give you more detail.
![Capture d’écran 2022-02-15 à 09 16 31](https://user-images.githubusercontent.com/86778557/154020766-6ef72ef8-9be2-47c8-bb5a-54c8dc2c21af.png)

**Comment by skreutzberger** [comment]
Yeah, unfortunately not. Let me close it for now and I keep an eye out for similar issues
