### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by advatar** [SwiftyBeaver/SwiftyBeaver#483]
![image](https://user-images.githubusercontent.com/28670/159668424-219526ee-a6d6-4f31-8227-9a8d0af15b8e.png)

This just after a normal 

`Log.debug("QRCode: Routing handled with success \(success) and error \(String(describing: error))")
`
in a closure.

**Comment by advatar** [comment]
Don't know if this helps?

`message	()	0x0000000102e64a48 Svipe iD`partial apply forwarder for implicit closure #1 () -> Any in static SwiftyBeaver.SwiftyBeaver.custom(level: SwiftyBeaver.SwiftyBeaver.Level, message: @autoclosure () -> Any, file: Swift.String, function: Swift.String, line: Swift.Int, context: Swift.Optional<Any>) -> () at <compiler-generated>`

**Comment by advatar** [comment]
This func

```
 /// internal helper which dispatches send to dedicated queue if minLevel is ok
    class func dispatch_send(level: SwiftyBeaver.Level, message: @autoclosure () -> Any,
        thread: String, file: String, function: String, line: Int, context: Any?) {
        var resolvedMessage: String?
        for dest in destinations {

            guard let queue = dest.queue else {
                continue
            }

            resolvedMessage = resolvedMessage == nil && dest.hasMessageFilters() ? "\(message())" : resolvedMessage
            if dest.shouldLevelBeLogged(level, path: file, function: function, message: resolvedMessage) {
                // try to convert msg object to String and put it on queue
                let msgStr = resolvedMessage == nil ? "\(message())" : resolvedMessage!
                let f = stripParams(function: function)

                if dest.asynchronously {
                    queue.async {
                        _ = dest.send(level, msg: msgStr, thread: thread, file: file, function: f, line: line, context: context)
                    }
                } else {
                    queue.sync {
                        _ = dest.send(level, msg: msgStr, thread: thread, file: file, function: f, line: line, context: context)
                    }
                }
            }
        }
    }
```

**Comment by skreutzberger** [comment]
What destinations are you using? `SBPlatformDestination`? And if yes, does your phone have an internet connection?

**Comment by advatar** [comment]
```
Log.addDestination(cloud) 
Log.addDestination(console)
Log.addDestination(file)
```

However, I get the same crash using print(). Something with `error` returned in the closure. So, some other problem - unless you can somehow avoid the crash.

**Comment by pvroosendaal** [comment]
How did you solve this issue @advatar?

**Comment by lordzsolt** [comment]
@pvroosendaal I assume either `\(success)` or `\(String(describing: error))` failed, considering he said they are failing even in a simple `print()` call.

The line where the crash is, is where the logged string is evaluated for the first time. And EXC_BAD_ACCESS usually means something is `nil` when it shouldn't have.
