### ISSUE TITLE
Allow 12 / 24 hour time formatting

### ISSUE THREAD

**Issue by IAmMichellis** [SwiftyBeaver/SwiftyBeaver#487]
I'm configuring the logger as follows, and getting 12 hour timestamps in spite of the 24 hour format string:

```
 let consoleDestination = ConsoleDestination()
 consoleDestination.format = "$Zyyyy-MM-dd HH:mm:ss.SSS$z $C$L: $M"
```

I played with `DateFormatter` outside SwiftyBeaver and realized I had to also set the locale of the formatter:

```
        let formatter = DateFormatter()
        formatter.timeZone = TimeZone(abbreviation: "UTC")
        formatter.dateFormat = "yyyy-MM-dd HH:mm:ss"
        formatter.locale = Locale(identifier: "en_US_POSIX") // <-- without this line, we print 12 hours. With it, 24.
        let dateStr = formatter.string(from: Date())
        
        MXLog.debug("hallooo \(dateStr)")
```

Would be good to be able to configure the formatter locale. Something as simple as:
```
 consoleDestination.locale = Locale(identifier: "en_US_POSIX")
```
Where the setting sets the locale on the stored formatter. Without this, I have 12 hour timestamps, and I'd like 24.

**Comment by skreutzberger** [comment]
Can you contribute it? Feel free to open a pull request.

**Comment by alexbird** [comment]
This is a major omission. I'm getting logs with dates and times in arabic, because the user of the device has that set as their locale!

**Comment by lordzsolt** [comment]
I looked at the issues @IAmMichellis and @alexbird mentioned, but I cannot reproduce it.

24 hour format:
![Screenshot 2022-12-24 at 22 40 27](https://user-images.githubusercontent.com/8976891/209451625-7841c7ee-aa84-47f6-a6a1-c541ffc2c3b3.png)
![Screenshot 2022-12-24 at 22 40 17](https://user-images.githubusercontent.com/8976891/209451633-caa2aa7d-1f57-4ab9-a114-ccb991094d46.png)

12 hour format:
![Screenshot 2022-12-24 at 22 40 48](https://user-images.githubusercontent.com/8976891/209451639-08109057-41c8-4bdb-bba5-ba87186aa563.png)
![Screenshot 2022-12-24 at 22 40 53](https://user-images.githubusercontent.com/8976891/209451642-1e930221-2400-416e-88c4-589393ba185a.png)

I also tried both with Simulator, and Physical device set to Arabic, the format that I set still gets respected.

**Comment by skreutzberger** [comment]
thank you @lordzsolt
