### ISSUE TITLE
Potential crash under macOS Ventura Beta 5

### ISSUE THREAD

**Issue by ModeSevenIndustrialSolutions** [SwiftyBeaver/SwiftyBeaver#489]
Hi,

It seems function calls to Thread.current are problematic in upcoming changes to Swift.

With the latest macOS Beta release, I am now seeing a crash here:

Sources -> SwiftyBeaver -> Line 75

With this call:

**return String(cString: name, encoding: .utf8) ?? Thread.current.description**

Have you tested SwiftyBeaver with the upcoming macOS release yet?

Thanks in advance,

- Matt

**Comment by ModeSevenIndustrialSolutions** [comment]
<img width="1718" alt="Screenshot 2022-08-14 at 14 20 25" src="https://user-images.githubusercontent.com/93649628/184538995-b2a19a39-6ada-4696-9262-377822322421.png">

**Comment by skreutzberger** [comment]
That has not been reported, yet. Do you know a fix? If yes, do you want to contribute it via pull request?

**Comment by ModeSevenIndustrialSolutions** [comment]
I've now seen this happen in other apps and Swift packages (under macOS 13 Ventura betas). I'm open to submitting a pull request at some point, but it will probably be closer to the time of the OS release. Right now, this is only showing up when I enable a debugging flag in my app. Let's perhaps keep this bug open for the time being and review the situation again at the start of October? There's not been enough discussion on some of the changes in the new release and I'm hoping more discussion and documentation will drop in the coming weeks.

**Comment by skreutzberger** [comment]
Good point, thanks!

**Comment by skreutzberger** [comment]
Since no one else commented on this issue I am closing it now.
