### ISSUE TITLE
Objective-C Wrapper and KZLinkedConsole

### ISSUE THREAD

**Issue by reesemclean** [SwiftyBeaver/SwiftyBeaver#49]
Hey,

We just started using SwiftyBeaver as our logging library — thanks!

We have a bunch of Objective-C code that we aren't going to rewrite anytime soon but would like to be able to add some logging to.

I don't think this project needs to have an Objective-C wrapper included but it would be beneficial as a separate project that someone could add if they needed.

I have a basic wrapper and macros here: [SwiftyBeaverObjectiveC](https://github.com/reesemclean/SwiftyBeaverObjectiveC)

The only thing I am having an issue with is formatting the Objective-C functions to work with KZLinkedConsole.

Here is the output using the standard \__FUNCTION\__ string:

`[2015-12-19 17:21:05.910] ViewController.-[ViewController logInfo:]:28 [fg0,255,0;INFO[;: This is an info message.`

So I'm not sure how the formatting could be modified so that hit would work with the Objective-C style method names? I could do some extra work to make the Objective-C method names print out like the swift style but that seems like a bad idea. Do you see anyway that the formatting could be changed so that it is more agnostic about the language the function is in?

**Comment by skreutzberger** [comment]
Hi @reesemclean - can you please contact me via Twitter DM?

**Comment by skreutzberger** [comment]
For the records: 
Reese is working now on the Objective C Wrapper project directly at the SwiftyBeaver organization account for a wider exposure and ongoing support of SwiftyBeaver’s roadmap.

The new repository is at [https://github.com/SwiftyBeaver/SBObjectiveCWrapper](https://github.com/SwiftyBeaver/SBObjectiveCWrapper - more documentation and information follows soon and contributions are more than welcome!

@reesemclean Thanks again - let's make Swift logging awesome! Especially for grown Objective-C projects which are bit by bit migrating to Swift  :rainbow: :+1:
