### ISSUE TITLE
Different way of initializing the logger

### ISSUE THREAD

**Issue by lordzsolt** [SwiftyBeaver/SwiftyBeaver#494]
What do you think about updating the documentation, recommending users to setup their logger like this instead:

```swift
let log: SwiftyBeaver.Type = {
    let log = SwiftyBeaver.self

	// add log destinations. at least one is needed!
	let console = ConsoleDestination()  // log to Xcode Console
	let file = FileDestination()  // log to default swiftybeaver.log file
	let cloud = SBPlatformDestination(appID: "foo", appSecret: "bar", encryptionKey: "123") // to cloud
	
	// use custom format and set console output to short time, log level & message
	console.format = "$DHH:mm:ss$d $L $M"
	// or use this for JSON output: console.format = "$J"
	
	// add the destinations to SwiftyBeaver
	log.addDestination(console)
	log.addDestination(file)
	log.addDestination(cloud)

    return log
}()
```

The first time `log` is used, the closure is called, setting up the logger.

This has the benefit that:
- It can be done without any AppDelegate
- There's no way to use the logger, without the destinations being added (ex using it in `willFinishLaunchingWithOptions`)

**Comment by skreutzberger** [comment]
good idea, thanks! I will update the docs.

**Comment by skreutzberger** [comment]
Do you want to update the README so that you count as contributor?

**Comment by lordzsolt** [comment]
@skreutzberger Gladly 😄
