### ISSUE TITLE
Concatenation of string parameters is no longer possible

### ISSUE THREAD

**Issue by VincentDurandChewbi** [SwiftyBeaver/SwiftyBeaver#498]
Hello,

Last commit in master removing _ before file and function parameters in SwiftyBeaver.swift, unable this kind of usage :

`log.error("an error occured", error.description)`

I have this error because the second parameter is a string and method definition consider it as the file parameter :

![image](https://user-images.githubusercontent.com/8911520/211054938-023d890f-c135-4885-aad2-1725ea74e929.png)

Is it a bad practice to concatenate strings this way ?

Regards,
Vincent

**Comment by skreutzberger** [comment]
hmm, good point. So maybe the last commit was not as good. Any opinions? BTW: it is not yet part of a version so it is not yet officially released.
