### ISSUE TITLE
Strange output

### ISSUE THREAD

**Issue by anatoliyv** [SwiftyBeaver/SwiftyBeaver#50]
Added SwiftyBeaver (v.0.3), but in output getting this:

    [19:26:54] [fg255,0,0;ERROR[;: Error

Source

    log.error("Error")

**Comment by davidrothera** [comment]
This looks like you either don't have XcodeColors installed or it is isn't working correctly. Check out [this](https://github.com/SwiftyBeaver/SwiftyBeaver#no-colors) section of the README for install instructions.
