### ISSUE TITLE
Too many logger threads are not exiting

### ISSUE THREAD

**Issue by aBusyAnt** [SwiftyBeaver/SwiftyBeaver#509]
![截屏2023-06-07 下午2 08 42](https://github.com/SwiftyBeaver/SwiftyBeaver/assets/1934088/8ed7d340-b9f2-4092-96e4-4b2a2e20d11f)

**Comment by skreutzberger** [comment]
I strongly recommend not to use the FileDestination for anything but the development of macOS apps. The filesystem of iPhones can behave strange due to limitations by Apple.
