### ISSUE TITLE
Hang Risk for flush() reported with iOS 17 beta 2 & Xcode 15

### ISSUE THREAD

**Issue by octopussy1** [SwiftyBeaver/SwiftyBeaver#511]
When running on isO 17 beta Simulator with Xcode 15 the following hangs risk is reported at some point:

Thread running at User-initiated quality-of-service class waiting on a lower QoS thread running at Default quality-of-service class. Investigate ways to avoid priority inversions

on 

Line 208:     return grp.wait(timeout: .now() + .seconds(Int(secondTimeout))) == .success

**Comment by skreutzberger** [comment]
what version of SwiftyBeaver are you using and in which destination file is it occuring?

**Comment by octopussy1** [comment]
I'm using SwiftyBeaver 2.0 destination file is the default FileDestination() and also ConsoleDestination()

**Comment by skreutzberger** [comment]
Hmm, thanks for reporting but it could be one of the beta warnings which may go away on release. So far the line has served well for the past years without any issues. Let's keep it open and see if more users report a similar issue after iOS 17 has been released.
