### ISSUE TITLE
Privacy Manifest

### ISSUE THREAD

**Issue by gabors** [SwiftyBeaver/SwiftyBeaver#522]
Hi, was wondering if/when you would be adding the privacy manifest to the SDK as per https://developer.apple.com/documentation/bundleresources/privacy_manifest_files

**Comment by lixiang1994** [comment]
+1

**Comment by skreutzberger** [comment]
working on it. I am waiting for some days if someone opens a PR and if not then will research it myself.

**Comment by skreutzberger** [comment]
it was released today in 2.0.1 - please see the discussion here https://github.com/SwiftyBeaver/SwiftyBeaver/issues/524 - thank you!

**Comment by SagarSDagdu** [comment]
Hi @skreutzberger , can you please release 2.0.1 to Cocoapods?
