### ISSUE TITLE
Can't get simple example to work

### ISSUE THREAD

**Issue by shakfu** [SwiftyBeaver/SwiftyBeaver#523]
Hi,

I must be doing something wrong as I can't seem to get any logging output from a simple test of `SwiftyBeaver`. 

I'm on a Macboo air M1 running Ventura and Swift version 5.9.2

Here's what I did:

```bash

mkdir logtest
cd logtest
swift package init --type executable
```

Added `SwiftyBeaver` to `Package.swift`:

```swift
// swift-tools-version: 5.9

import PackageDescription

let package = Package(
    name: "logtest",
    dependencies: [
        .package(url: "https://github.com/SwiftyBeaver/SwiftyBeaver.git", .upToNextMajor(from: "2.0.0")),
    ],
    targets: [
        .executableTarget(
            name: "logtest",
            dependencies: [
                .product(name: "SwiftyBeaver", package: "SwiftyBeaver"),
            ]
        ),
    ]
)
```

Modified `main.swift` as follows:

```swift
import Foundation
import SwiftyBeaver
let log = SwiftyBeaver.self

print("hello test")

let console = ConsoleDestination()
console.minLevel = .debug // Set the minimum log level
log.addDestination(console)

let file = FileDestination()
file.minLevel = .debug
file.logFileURL = URL(fileURLWithPath: "./log.txt")
log.addDestination(file)

log.info("this is info")
log.debug("debugging")
log.warning("o dear..")
log.error("bye")

print("bye test")
```

and then when I run using `swift run`:

```bash
Building for debugging...
Build complete! (0.16s)
hello test
bye test
```

I build it using `swift build` and ran the executable

```bash
% ./logtest
hello test
bye test
```

Am I missing something? There's no terminal output, there's no creation of a `log.txt` file as expected.. I checked the `console` app and there's nothing there. What am I doing wrong here?

**Comment by shakfu** [comment]
@skreutzberger 

I'm surprised this was closed without any comment. I took the time to provide a detailed issue report

**Comment by skreutzberger** [comment]
hey, sorry, I clicked too fast. your code looks correct. very weird. I have some pending PRs and messages and I guess they may fix it. please keep an eye on the repo. thanks!

**Comment by shakfu** [comment]
Thanks!
