### ISSUE TITLE
Privacy Manifest

### ISSUE THREAD

**Issue by sakshibala-halodoc** [SwiftyBeaver/SwiftyBeaver#524]
Subject: We need to incorporate the xcprivacy manifest into our app . Starting March 13, Apple will send notifications when uploading builds to the App Store, and this will become mandatory from May 1. All the SDKs used in our app needs to incorporate the xcprivacy manifest.
Reference: https://developer.apple.com/news/?id=3d8a9yyh

Actions needed: We need the compatible xcprivacy manifest version IOS SDK with xcprivacy manifest. We are expecting a seamless upgrade by upgrading to the latest version.

**Comment by lixiang1994** [comment]
+1

**Comment by lixiang1994** [comment]
@skreutzberger

**Comment by skreutzberger** [comment]
Is that something which can be added via PR? if yes then feel free to contribute 😊

**Comment by hikaruaohara** [comment]
SwiftyBeaver does not appear to require support for the privacy manifest. Only apps or SDKs that use required reasons API, collect data about the person using apps that include the third-party SDK, enable the app to collect data about people using the app, or contact tracking domains need to support it.

https://developer.apple.com/documentation/bundleresources/privacy_manifest_files

**Comment by skreutzberger** [comment]
Thank you! I checked the Apple docs and it is unclear to me if SwiftyBeaver needs that file. They also gave some example frameworks which require it and have from my understanding less logging than SwiftyBeaver. Therefore I added the privacy manifest but with a very mild setting (see screenshot).

I also released the new SwiftyBeaver version 2.0.1 containing it. I did not submit it to Cocoapods because there were a gazillion errors and I don't know if Cocoapods is actually still a thing so many years after introducing SPM. Please comment here if things work / don't work for you. Thank you!

<img width="601" alt="SCR-20240415-hoan" src="https://github.com/SwiftyBeaver/SwiftyBeaver/assets/564725/5132cf4d-8cc7-4236-b008-daa261b21c5e">

**Comment by SagarSDagdu** [comment]
> Thank you! I checked the Apple docs and it is unclear to me if SwiftyBeaver needs that file. They also gave some example frameworks which require it and have from my understanding less logging than SwiftyBeaver. Therefore I added the privacy manifest but with a very mild setting (see screenshot).
> 
> I also released the new **SwiftyBeaver version 2.0.1** containing it. I did not submit it to Cocoapods because there were a gazillion errors and I don't know if Cocoapods is actually still a thing so many years after introducing SPM. Please comment here if things work / don't work for you. Thank you!
> 
> <img alt="SCR-20240415-hoan" width="601" src="https://private-user-images.githubusercontent.com/564725/322367810-5132cf4d-8cc7-4236-b008-daa261b21c5e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNzE3OTUsIm5iZiI6MTcxMzE3MTQ5NSwicGF0aCI6Ii81NjQ3MjUvMzIyMzY3ODEwLTUxMzJjZjRkLThjYzctNDIzNi1iMDA4LWRhYTI2MWIyMWM1ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNVQwODU4MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMTI0YTkyMjFkOWNhZGEyMDVhOTFhY2MyOGNkMjdiNmU5N2U3NTI2YTg1MmE2OGE4MmNlYmJjZWJlYTQ2ZDk5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._YHZkML_5fyA6nCTRKfrDi08EDZ5T3vwIOjg8zqRe88">

Hello @skreutzberger , can you please post a screenshot of the errors you saw when you tried to publish it to Cocoapods? I can help you fix those, as I need the version 2.0.1 through Cocoapods.

**Comment by skreutzberger** [comment]
ah sorry, my bad, I just had an old cocoapods installed. after upgrading it worked 

<img width="420" alt="image" src="https://github.com/SwiftyBeaver/SwiftyBeaver/assets/564725/1f252828-fb7a-4459-992f-4de963db9550">

**Comment by lixiang1994** [comment]
@skreutzberger 
https://github.com/SwiftyBeaver/SwiftyBeaver/issues/528
