### ISSUE TITLE
Possible logic issue in rotateFile(_:) in FileDestination

### ISSUE THREAD

**Issue by chris-jarvi** [SwiftyBeaver/SwiftyBeaver#525]
I'm investigating an issue in our app where the log file size is a lot larger than expected.  I noticed your `private func rotateFile(_ filePath: String)` in `FileDestination` may have a logic error in calculating your indices.

Your last index, with your default value for `logFileAmount` will calculate to 0, leaving your stride going (0...1), by -1.  The closure contents, where the file gets rotated/removed, will never execute.

**Comment by skreutzberger** [comment]
thanks for reporting! can you write a test showing it and/or open a PR to fix it? thanks!

**Comment by skreutzberger** [comment]
closing in the meantime
