### ISSUE TITLE
FileDestination: "logFileAmount" should be "logFilesNumber"

### ISSUE THREAD

**Issue by richardtop** [SwiftyBeaver/SwiftyBeaver#526]
The correct noun is "number" in this case as it's a countable 
https://github.com/SwiftyBeaver/SwiftyBeaver/blob/master/Sources/FileDestination.swift#L46

https://dictionary.cambridge.org/grammar/british-grammar/amount-of-number-of-or-quantity-of

**Comment by skreutzberger** [comment]
Hi, you are right! Unfortunately this small change would have break existing implementations and therefore can not be implemented. In the future we will make sure to use the right grammar.

**Comment by richardtop** [comment]
Why not to just do the API deprecation notice and remove the older API after a while?

**Comment by skreutzberger** [comment]
it would affect millions of developers and I want to spare them the change. Still, I keep your change on my mind and when we do a major breaking release like 3.0 or so then we can do it there.

**Comment by richardtop** [comment]
No problem. I think it would be good to reopen then...  I'm happy to help with the change, if/when needed.
