### ISSUE TITLE
Q: Use in a concurrent environment

### ISSUE THREAD

**Issue by richardtop** [SwiftyBeaver/SwiftyBeaver#529]
Hi, I'm curious whether it's allowed to use SwiftyBeaver in a concurrent environment. Let's consider we have 2 targets: an iOS app and an app extension, both are sharing the storage via the [Shared Container](https://developer.apple.com/documentation/foundation/nsfilemanager/1412643-containerurlforsecurityapplicati).

Is there any limitation on whether we can log from both targets simultaneously? Should we implement the locking?

**Comment by skreutzberger** [comment]
Each destination has its own queue and SwiftyBeaver can be used in parallel environments.

**Comment by richardtop** [comment]
So they can write to the same file? No conflicts etc? Thanks.

**Comment by skreutzberger** [comment]
What file do you mean?

**Comment by richardtop** [comment]
i.e. using this: https://github.com/SwiftyBeaver/SwiftyBeaver/blob/master/Sources/FileDestination.swift
with a file url that is shared between an app target an an app extension, so that the `logFileURL` is pointing into a common container, https://developer.apple.com/documentation/foundation/nsfilemanager/1412643-containerurlforsecurityapplicati

**Comment by skreutzberger** [comment]
ah you are using the FileDestination. It was actually initially just meant to be used for local macOS development. So you are right, it may lead to conflicts.

**Comment by richardtop** [comment]
Ok, then could you reopen this, as there is a way to implement it with the help of concurrent file operations (this is supported by the OS).
