### ISSUE TITLE
Log messages not appearing in Xcode console after update to v2.1.0

### ISSUE THREAD

**Issue by gaw3** [SwiftyBeaver/SwiftyBeaver#532]
I have recently updated SwiftyBeaver from v1.9.5 to v2.1.0.

Building my app worked right off the bat, but now the log messages no longer appear in the Xcode console.  

Did anyone else experience this?  May I ask for some advice?

Apple M2 Pro, Sonoma 14.4.1,  Xcode 15.3, iOS 17.4

Thank you for the help.

**Comment by gaw3** [comment]
This is existing code.  Log msgs appear when using v1.9.5, stopped appearing after updating to 2.1.0


```
import SwiftyBeaver
let log = SwiftyBeaver.self

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {

    var window: UIWindow?

    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        initLogging()
        log.debug("this is a log message")

    }

}

private extension AppDelegate {

    enum Beaver {

        enum Console {
            static let format = "[$Dyyyy-MM-dd HH:mm:ss.SSS$d], $T, $C$L$c, $N.$F:$l, $M"
            static let minLevel: SwiftyBeaver.Level = .debug
        }

    }

    func initLogging() {
        let console = ConsoleDestination()

        console.format = Beaver.Console.format
        console.asynchronously = false
        console.minLevel = Beaver.Console.minLevel

        log.addDestination(console)
    }

}

```

**Comment by gaw3** [comment]
Little bit of my app (MyTVTracker) history that may be pertinent:  I first added SwiftyBeaver as a cocoapod, then eventually migrated it to the SPM.  Second, I don't have a SceneDelegate in MyTVTracker.  When SceneDelegate first arrived, I read an article that was basically "Don't want to mess with SceneDelegate right now?  Do this to keep with AppDelegate".  So, that's what I did, but for the life of me, I can't remember what all that was.  Third, I still have other cocoapods in MyTVTracker.

So, I created a fresh project (SwiftyBeaverThree), added the above code, removed SceneDelegate.swift from the project, and added SwiftyBeaver v1.9.5 via the SPM.  Ran the program, here is what appeared in the console:

```
Logging Error: Failed to initialize logging system. Log messages may be missing. If this issue persists, try setting IDEPreferLogStreaming=YES in the active scheme actions environment variables.
[2024-05-02 21:54:22.155], , 💙 INFO, AppDelegate.application():24, this is an info msg
[2024-05-02 21:54:22.157], , ❤️ ERROR, AppDelegate.application():25, this is an error msg
[2024-05-02 21:54:22.158], , ❤️ ERROR, AppDelegate.application():26, this is a warning msg
Info.plist configuration "(no name)" for UIWindowSceneSessionRoleApplication contained UISceneDelegateClassName key, but could not load class with name "SwiftyBeaverThree.SceneDelegate".
There is no scene delegate set. A scene delegate class must be specified to use a main storyboard file.

```
 Here it is with the associated metadata:

```
Logging Error: Failed to initialize logging system. Log messages may be missing. If this issue persists, try setting IDEPreferLogStreaming=YES in the active scheme actions environment variables.
Type: Fault

[2024-05-02 21:54:22.155], , 💙 INFO, AppDelegate.application():24, this is an info msg
[2024-05-02 21:54:22.157], , ❤️ ERROR, AppDelegate.application():25, this is an error msg
[2024-05-02 21:54:22.158], , ❤️ ERROR, AppDelegate.application():26, this is a warning msg
Type: stdio

Info.plist configuration "(no name)" for UIWindowSceneSessionRoleApplication contained UISceneDelegateClassName key, but could not load class with name "SwiftyBeaverThree.SceneDelegate".
Type: Error | Timestamp: 2024-05-02 21:54:22.158750-05:00 | Process: SwiftyBeaverThree | Library: UIKitCore | Subsystem: com.apple.UIKit | Category: SceneConfiguration | TID: 0xb1c79

There is no scene delegate set. A scene delegate class must be specified to use a main storyboard file.
Type: Error | Timestamp: 2024-05-02 21:54:22.162303-05:00 | Process: SwiftyBeaverThree | Library: UIKitCore | Subsystem: com.apple.UIKit | Category: WindowScene | TID: 0xb1c79 

```

I added SceneDelegate.swift back into SwiftyBeaverThree, and only the log messages appeared, no error messages appeared.  I took SceneDelegate.swift back out of SwiftyBeaverThree, and ran it again.  The log messages appeared, and the SceneDelegate errors reappeared, but the logging error did not reappear.

I have infrequently seen the logging error in the console when running MyTVTracker and using v1.9.5, but logging always occurs normally after that, so I blew it off as a simulator thing.  But after updating MyTVTracker to use 2.1.0, NOTHING appears in the console, no log msgs, no error msgs.  BLANK.  I set IDEPreferLogStreaming=YES as recommended in the text of the logging error, this did not help.  Still BLANK.  Revert MyTVTracker to 1.9.5, and logging starts working normally again.

Apologies for being so longwinded, I hope it helps.

**Comment by gaw3** [comment]
Found the issue. I had set the following environment variable in my scheme: OS_ACTIVITY_MODE=disable. Removing this from the environment fixed it.  I can now see log messages in the Xcode console using SwiftyBeaver 2.1.0.

Sorry about all that other blather, I have removed those posts.

**Comment by otymartin** [comment]
@gaw3 I mean removing `OS_ACTIVITY_MODE=disable` resolves the problem but that shouldnt be the case. I've always had `OS_ACTIVITY_MODE` and swiftybeaver worked alongside it. xcode console is now literred with system garbage.

Would probably be wise to reopen the issue until its resolved.

**Comment by gaw3** [comment]
@otymartin Well, I dont know what to say.  I removed that variable, and I get log messages with no system garbage.  I created a fresh project, latest ios/xcode/SwiftyBeaver.  I get the same results.  With `OS_ACTIVITY_MODE=disable` I get nothing in the console.  Removing the variable, or leaving it and setting it to `enable`, I get log messages with no system garbage.  I suspect this has something to do with SwiftyBeaver using OSLog to do log messaging.  Perhaps @skreutzberger can speak to this?

**Comment by otymartin** [comment]
@gaw3 I'm no longer getting the system garbage so I think it was something else, perhaps swiftybeaver itself. I downgraded to a previous release.

**Comment by WillSuo-Github** [comment]
Hi everyone,

I recently submitted a PR to adapt the system’s OSLog API for this repository, enabling colored output in Xcode. Additionally, I changed the default logging method to use the OSLog API for printing. However, setting OS_ACTIVITY_MODE=false does result in the log outputs not being visible.

You can switch the logging method to avoid using the OSLog API. For example:
`
let console = ConsoleDestination()
console.logPrintWay = .print
log.addDestination(console)
`

Thank you for considering this change. Best regards.

**Comment by skreutzberger** [comment]
@WillSuo-Github can you please create a PR which uses print as default? In that way SwiftyBeaver has its former "normal" behaviour and the user can opt-in for OSLog.

**Comment by WillSuo-Github** [comment]
@skreutzberger Of course, I have already submitted a PR. I apologize for not considering this scenario earlier. [https://github.com/SwiftyBeaver/SwiftyBeaver/pull/535](PR)

**Comment by skreutzberger** [comment]
Thank you for the quick update! All good, I will release a new version soon.
