### ISSUE TITLE
Idea: replace hearts emojis with squares

### ISSUE THREAD

**Issue by richardtop** [SwiftyBeaver/SwiftyBeaver#536]
Idea: replace hearts emojis with squares
Motivation: hearts don't look very professional.

If it's OK, I can make a PR with this change.

**Comment by skreutzberger** [comment]
hehe, good point. please make a PR if you find squares matching all colors.

**Comment by richardtop** [comment]
Fixed in PR https://github.com/SwiftyBeaver/SwiftyBeaver/pull/545
I've matched the colors with the text-only output style, so everything matches perfectly now.

**Comment by richardtop** [comment]
@skreutzberger  Please "release" new version of the SwiftyBeaver by adding a new "tag" to the repo.
