### ISSUE TITLE
Unable to subclass BaseDestination

### ISSUE THREAD

**Issue by irace** [SwiftyBeaver/SwiftyBeaver#54]
I am perhaps being dense, but how exactly can one subclass BaseDestination in order to override the requisite methods when those methods are not `public`?

**Comment by skreutzberger** [comment]
It should work as long as you place your subclass inside the SwiftyBeaver framework. While saying that I actually would not recommend doing it because it will make future upgrades of SwiftyBeaver framework itself very hard or even impossible.

AFAIR a framework just exposes public functions or classes so you should just overwrite these. I heard from other users who could create custom destinations by just overwriting the public functions of BaseDestination.

What is your detailed use case?

**Comment by irace** [comment]
> It should work as long as you place your subclass inside the SwiftyBeaver framework. While saying that I actually would not recommend doing it because it will make future upgrades of SwiftyBeaver framework itself very hard or even impossible. 

Sure – placing my subclass inside of the framework would work, but this would defeat the point of using a dependency manager. 

> And I am currently working on a major upgrade.

Should I bother opening a PR to add the ability to add custom logging destinations to the current version?

> AFAIR a framework just exposes public functions or classes so you should just overwrite these. 

Nope – functions and classes are `internal` by default in Swift. If specifically declared `public`, they can be overridden from an external module. If you look at `BaseDestination`, you’ll see that while some methods are public, `send` is not.

> I heard from other users who could create custom destinations by just overwriting the public functions of BaseDestination.

I’d love to know how – I’m assuming they must have solely copied SwiftyBeaver’s source files into their project directly, and are not building it as a separate framework that they then link against.

> What is your detailed use case?

I am basically just trying to do [this](https://gist.github.com/jimrutherford/45223f46befd0de96589) – add a custom destination for logging to Crashlytics – but that code doesn’t actually compile when linking against SwiftyBeaver.framework, since `send` is not `public` and therefore cannot be overridden.

**Comment by irace** [comment]
Opened one anyway: https://github.com/SwiftyBeaver/SwiftyBeaver/pull/55

**Comment by skreutzberger** [comment]
Yes, please open a PR to add the ability to add custom logging destinations even outside the framework. I thought it was working ... but I was always just building destinations INSIDE the framework :smile: 

Crashlytics support is great. Loggly and Slack would be great, too.

**Comment by irace** [comment]
@skreutzberger FWIW, here’s a rough sketch of how I think the custom logging API should look in the next version of SwiftBeaver. Allowing third-party developers to implement a protocol is a much more idiomatic interface than exposing a base class to be subclassed:

```swift
protocol Destination: HashCode {
    var hashValue: Int { get }

    // I don’t know if these all actually need to be customizable
    var detailOutput: Bool { get }
    var colored: Bool { get }
    var minLevel: SwiftyBeaver.Level { get }
    var dateFormat: String { get }
    var levelString: LevelString { get }

    func send(level: SwiftyBeaver.Level, message: String, thread: String, path: String, function: String, line: Int) -> String?
}

extension Destination {
    // Provide defaults
    var detailOutput: Bool { return true }
    var colored: Bool { return true }
    var minLevel: SwiftyBeaver.Level { return SwiftyBeaver.Level.Verbose }
    var dateFormat: String { return "yyyy-MM-dd HH:mm:ss.SSS" }
    var levelString: LevelString { return LevelString() }
}

final class CrashlyticsDestination {
    let colored = false

    func send(level: SwiftyBeaver.Level, message: String, thread: String, path: String, function: String, line: Int) -> String? {
        let formattedString = super.send(level, msg: msg, thread: thread, path: path, function: function, line: line)

        if let formattedString = formattedString {
            CLSLogv(formattedString, getVaList([]))
        }

        return formattedString
    }
}

log.addDestination(CrashlyticsDestination())
```

**Comment by skreutzberger** [comment]
Thanks. I chose the base class approach because most of the logic can be re-used. But I am not a big expert in protocol-based software design and I know that Swift is strong on that.

**Comment by irace** [comment]
@skreutzberger You can still use inheritance internally – I just think it’s best to have the framework’s _public_ interface be protocol-based. 

Here’s an example: a third-party developer conforms to a `Destination` protocol and then adds it to SwiftyBeaver. Internally, SwiftyBeaver wraps that custom object in a concrete subclass of your base class, that reuses whatever logic you need:

```swift
/// Public protocol – all third-party developers can do is conform to this
protocol Destination: HashCode {
    var hashValue: Int { get }
    var colored: Bool { get }

    func send(level: SwiftyBeaver.Level, message: String, thread: String, path: String, function: String, line: Int) -> String?
}

/// Internal subclass that reuses all of your base class’s logic but doesn’t leak into the public interface
internal CustomDestination {
    private let destination: Destination

    var hashValue: Int { return destination.hashValue }

    init(destination: Destination) {
        self.destination = destination
        self.colored = destination.colored
    }

    func send(level: SwiftyBeaver.Level, message: String, thread: String, path: String, function: String, line: Int) -> String? {
        return destination.send(level: level, message: message, thread: thread, path: path, function: function, line, line)
    }
}

/// Public interface that a third-party developer uses to add a custom logger
public func addDestination(destination: Destination) {
    addDestination(CustomDestination(destination: destination))
}

private func addDestination(baseDestination: BaseDestination) {
    // Whatever this already does today...
}
```

**Comment by skreutzberger** [comment]
Thank you! I will play around with adding a protocol.
