### ISSUE TITLE
Sporadic crashes with formatMessage(_) 

### ISSUE THREAD

**Issue by ArsalanG99** [SwiftyBeaver/SwiftyBeaver#543]
Hello, 
I am using SwiftyBeaver 2.0.0, and sometimes I am observing sporadic crashes
Do you know how can I resolve it?

This is the crashlogs:

Exception Type:  EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0x0000000000000001, 0x000000018fa3d0e8
Termination Reason: SIGNAL 5 Trace/BPT trap: 5
Terminating Process: exc handler [1110]

Triggered by Thread:  0

Thread 0 Crashed:
0   libswiftCore.dylib            	0x000000018fa3d0e8 closure #1 in closure #1 in closure #1 in _assertionFailure(_:_:file:line:flags:) + 228 (AssertCommon.swift:109)
1   libswiftCore.dylib            	0x000000018fa3cfc0 closure #1 in closure #1 in _assertionFailure(_:_:file:line:flags:) + 332 (AssertCommon.swift:102)
2   libswiftCore.dylib            	0x000000018fa3c94c _assertionFailure(_:_:file:line:flags:) + 184 (AssertCommon.swift:98)
3   libswiftCore.dylib            	0x000000018fa3f2a8 specialized BidirectionalCollection._index(_:offsetBy:) + 1352 (BidirectionalCollection.swift:0)
4   libswiftCore.dylib            	0x000000018fc26dc0 String.UTF16View._indexRange(for:from:) + 184 (StringUTF16View.swift:347)
5   libswiftCore.dylib            	0x000000018fc41dc0 __StringStorage.getCharacters(_:range:) + 112 (StringStorageBridge.swift:192)
6   libswiftCore.dylib            	0x000000018fc41ec4 @objc __StringStorage.getCharacters(_:range:) + 36 (<compiler-generated>:0)
7   CoreFoundation                	0x000000019148c07c doAccess + 608 (CFStringUText.c:201)
8   libicucore.A.dylib            	0x000000019b0581b8 utext_next32 + 56 (utext.cpp:286)
9   libicucore.A.dylib            	0x000000019b1603c0 icu::RegexMatcher::find(UErrorCode&) + 1372 (rematch.cpp:750)
10  Foundation                    	0x00000001900a2c14 -[NSRegularExpression(NSMatching) enumerateMatchesInString:options:range:usingBlock:] + 692 (NSRegularExpression.m:496)
11  Foundation                    	0x00000001900a1830 -[NSRegularExpression(NSMatching) matchesInString:options:range:] + 180 (NSRegularExpression.m:534)
12  Foundation                    	0x00000001900a15d0 -[NSRegularExpression(NSReplacement) stringByReplacingMatchesInString:options:range:withTemplate:] + 140 (NSRegularExpression.m:586)
13  Foundation                    	0x00000001908e40e0 -[NSString(NSRegularExpressionSupport) _stringByReplacingOccurrencesOfRegularExpressionPattern:withTemplate:options:range:] + 220 (NSStringRegex.m:60)
14  Foundation                    	0x0000000190126280 StringProtocol.replacingOccurrences<A, B>(of:with:options:range:) + 612 (NSStringAPI.swift:942)
15  SwiftyBeaver                  	0x00000001035825f4 BaseDestination.formatMessage(_:level:msg:thread:file:function:line:context:) + 2564 (BaseDestination.swift:250)
16  SwiftyBeaver                  	0x0000000103581744 BaseDestination.send(_:msg:thread:file:function:line:context:) + 212 (BaseDestination.swift:113)
17  XXXX                	0x000000010286ce38 closure #1 in MemoryDestination.send(_:msg:thread:file:function:line:context:) + 336 (MemoryDestination.swift:97)
18  XXXX                	0x000000010286da14 partial apply for closure #1 in MemoryDestination.send(_:msg:thread:file:function:line:context:) + 56 (<compiler-generated>:0)
19  XXXX                	0x00000001025675bc thunk for @escaping @callee_guaranteed () -> () + 28 (<compiler-generated>:0)
20  libdispatch.dylib             	0x0000000199130370 _dispatch_call_block_and_release + 32 (init.c:1549)
21  libdispatch.dylib             	0x00000001991320d0 _dispatch_client_callout + 20 (object.m:576)
22  libdispatch.dylib             	0x00000001991409e0 _dispatch_main_queue_drain + 980 (queue.c:8093)
23  libdispatch.dylib             	0x00000001991405fc _dispatch_main_queue_callback_4CF + 44 (queue.c:8253)
24  CoreFoundation                	0x0000000191430204 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16 (CFRunLoop.c:1793)
25  CoreFoundation                	0x000000019142d440 __CFRunLoopRun + 1996 (CFRunLoop.c:3163)
26  CoreFoundation                	0x000000019142c830 CFRunLoopRunSpecific + 588 (CFRunLoop.c:3434)
27  GraphicsServices              	0x00000001dd40c1c4 GSEventRunModal + 164 (GSEvent.c:2196)
28  UIKitCore                     	0x0000000193f92eb0 -[UIApplication _run] + 816 (UIApplication.m:3844)
29  UIKitCore                     	0x00000001940415b4 UIApplicationMain + 340 (UIApplication.m:5496)
30  UIKitCore                     	0x000000019437bfa8 UIApplicationMain(_:_:_:_:) + 104 (UIKit.swift:565)
31  XXXX                	0x00000001021e181c main + 116 (main.swift:20)
32  dyld                          	0x00000001b6e1aec8 start + 2724 (dyldMain.cpp:1334)

**Comment by skreutzberger** [comment]
I don't know and since no one else reported it I will close the ticket. please report back if it happens again. Thanks!
