### ISSUE TITLE
Linking against watchOS Target is not working

### ISSUE THREAD

**Issue by Narsail** [SwiftyBeaver/SwiftyBeaver#63]
Hey there, 

i integrate your awesome framework successfully into OSX and iOS Applications. But i have trouble running them on an iPhone while including a watch extension. It is working fine on the simulator but is crashing because of the following problem:

```
(null): Linking against dylib not safe for use in application extensions: /.../em_swift_ios/Carthage/Build/watchOS/SwiftyBeaver.framework/SwiftyBeaver
```

I first encountered it while linking your framework with my own framework (which also includes a watchOS target) where it was throwing a code signing error because of the dylib linking shown in the error above.

Maybe someone has a clue to solve this problem? I'm pretty new to the code signing stuff myself.

**Comment by skreutzberger** [comment]
@impossibleventures - you contributed the possibility to use SwiftyBeaver as an extension. Do you maybe know what causes that issue with the watch extension? Thanks!

**Comment by davidrothera** [comment]
You need to ensure that the "Require Only App-Extension-Safe API" is set to YES for the framework in question (yours)

**Comment by skreutzberger** [comment]
@davidrothera  :+1: :clap:

**Comment by Narsail** [comment]
Okay, thanks for the hint. I'll give you feedback after testing it.

**Comment by davidrothera** [comment]
Hey @Narsail did you get chance to test the fix?

**Comment by skreutzberger** [comment]
Seems it worked so I am closing the issue for now.

**Comment by Narsail** [comment]
Sry i didn't have time until now to test it. When activating "Require Only App-Extension-Safe API" i got the following warning within the framework build:
![screen shot 2016-03-01 at 20 17 09](https://cloud.githubusercontent.com/assets/7859096/13438763/bc7a86ea-dfea-11e5-8a1e-545a42daef33.png)

**Comment by skreutzberger** [comment]
reopening
