### ISSUE TITLE
Make threadName() method public

### ISSUE THREAD

**Issue by fvvliet** [SwiftyBeaver/SwiftyBeaver#73]
Hello Sebastian, 

you mind making threadName() method public ? I could use this method in my own code too.
you need a PR for this ?

Thanks
Frank

**Comment by skreutzberger** [comment]
It's just adding a single word, I do it right away. No PR necessary :)

**Comment by prenagha** [comment]
Not sure you want the logger to expose that. Although easy to do, it really isn't the job of the logger to be a utility class for getting the name of the current thread. Also keep in mind as soon as you make it public you now have to worry about other people who might use it, so it becomes hard to ever take away, or ever change what it does. What if someone uses it outside of the logger and now you want to change the format of the thread name?

**Comment by skreutzberger** [comment]
Good point, hmm. Maybe I should revert it and not let it go into the next version. Does anyone else have an opinion about it?

**Comment by davidrothera** [comment]
Perhaps @fvvliet can say how the change will be used before reverting?

**Comment by fvvliet** [comment]
I would use it in my code like for example:
print(SwiftyBeaver.threadName())

(but I have to admit to @prenagha that it's not the purpose of SwiftyBeaver to expose this specific functionality)

**Comment by davidrothera** [comment]
Hmm... but why are you wanting the name of the thread that SB is running in?

**Comment by fvvliet** [comment]
When I for example want to check in the closure of an async call (of some 3th-party framework) that I'm on the main thread. This could be important in case I want to show an alert on screen.

**Comment by skreutzberger** [comment]
@fvvliet thanks for the explanation! I know that threadName() is a very handy utility function which I actually use a lot, too. But I have put it (copy&paste) into a more general tool class which contains all my sweet little helpers which make my Swift life so much more convenient :)

In the context of SwiftyBeaver Logger that function just has internal purpose and does not initiate any logging, adjust a logging configuration or manages the logging destinations. Therefore it should not have be public-facing.

I will revert the "public" and recommend you to copy & paste the function and put it in a more general utility class which you can re-use on all your projects.

@prenagha Thank you so much for reminding me to keep things simple & future-proof!

Closing this one and I am already looking forward to some further interesting discussions about what to put in and what to leave out of the project :)
