### ISSUE TITLE
Change log output behavior from asynchronous to synchronous

### ISSUE THREAD

**Issue by kenjitayama** [SwiftyBeaver/SwiftyBeaver#76]
Asynchronous log output makes debugging difficult when using the debugger.
For example, set a breakpoint at a line where log is outputted, step over one line, and no log seen in the console.
If the implementation is changed to do synchronous output, it would be great help!

**Comment by davidrothera** [comment]
Playing devils advocate I would say async is better but perhaps give the option when setting up for it being synchronous, that way you could gate on whether you are in a prod build you can use async

**Comment by kenjitayama** [comment]
Yes, supporting an option would be best.
Production should be async, and file output should be too.
Sync would be great when using the debugger and watching the console.
Maybe add a configuration in `BaseDestination` ?

**Comment by skreutzberger** [comment]
A switch is an interesting idea if the default stays async. For better understanding: SwiftyBeaver logging calls would then always run at the calling thread or remain on main thread?

A pull request would help to better discuss that feature ;)

**Comment by kenjitayama** [comment]
A PR from a teammate :)

**Comment by skreutzberger** [comment]
implemented in #77
