### ISSUE TITLE
I can't build successful in iOS 8 and Xcode 7.2

### ISSUE THREAD

**Issue by a598799539** [SwiftyBeaver/SwiftyBeaver#80]
![image](https://cloud.githubusercontent.com/assets/2295970/13974180/718c20fc-f0e4-11e5-965d-ed615d753756.png)

![image](https://cloud.githubusercontent.com/assets/2295970/13974202/abb91974-f0e4-11e5-90b6-05758b6ce725.png)

**Comment by a598799539** [comment]
but i use `pod 'SwiftyBeaver', '0.4.0'` is ok

**Comment by yonaskolb** [comment]
SwiftyBeaver 0.4.2 and above requires Xcode 7.3

**Comment by a598799539** [comment]
@yonaskolb  thanks

**Comment by davidrothera** [comment]
Maybe it's worth changing the deployment target on these to require the new OS versions, that would give a clearer error message when trying to use the new version rather than simply not compiling?

**Comment by skreutzberger** [comment]
@davidrothera Can you please send a PR? I will then also update the README to reflect the Xcode 7.3+ as requirement.

**Comment by davidrothera** [comment]
After further thoughts locking to a platform version is not what we want, once Swift2.2 has been compiled it will run on any Swift supported platform so locking to iOS 9.3+ would be a mistake.

I think for now it just needs to be clear that Xcode7.3 is required for the new versions but include instructions on how they can pin to a specific version if needed.
