### ISSUE TITLE
It's not correct when logging function with one parameter

### ISSUE THREAD

**Issue by hstdt** [SwiftyBeaver/SwiftyBeaver#82]
SwiftyBeaver 0.4.2  Xcode 7.3

![image](https://cloud.githubusercontent.com/assets/10215098/14040356/72ef537e-f2a1-11e5-99ad-652c05e76587.png)

```
    func test(x:AnyObject?) {
        log.error("test1")
    }
    
    func test(x:AnyObject?,y:AnyObject?) {
        log.debug("test2")
    }
```

Should it be "AppDelegate.test(_:):16 "?

**Comment by skreutzberger** [comment]
That’s odd, I will investigate further or do you already have a fix with pull request in mind?

**Comment by skreutzberger** [comment]
I put it on the to-do list for a next release and close the issue for now.
