### ISSUE TITLE
"Do not have permission" Error when trying to save into /tmp (even after sudo chmod 777 /temp)

### ISSUE THREAD

**Issue by thisIsNotArchy** [SwiftyBeaver/SwiftyBeaver#84]
[Using Xcode 7.3]

So I wanted to write into temp:

```
file.logFileURL = NSURL(string: "file:///tmp/neko.log")!
```

But I got this error that I don't have the permission to do so:

```
SwiftyBeaver could not write to file file:///tmp/neko.log. Error Domain=NSCocoaErrorDomain Code=513 "You don’t have permission to save the file "neko.log” in the folder “tmp”." UserInfo={NSFilePath=/tmp/app_info.log, NSUnderlyingError=0x129877180 {Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted"}}
```

I even did  `sudo chmod 777 /temp` but it didn't help.

I was running the app on an iPad (due to some constraints the app isn't testable in a simulator). Can it be that it is trying to write into `/tmp` on the iPad instead? 

If that is the case, is there a way to get it to write into the `/tmp` on my El Capitan?

**Comment by thisIsNotArchy** [comment]
And when I try to write into a file that clearly exists on my El Captian I got the "No such file or directory" error.

**Comment by davidrothera** [comment]
Yes, it will be writing (or trying to) write to a file on the iPad as that is where the code is running.

Because of the sandbox nature of iOS you can't write to /tmp on there, you would just need to write to the directories you have access to (Documents)

**Comment by thisIsNotArchy** [comment]
@davidrothera I see. Thanks!
