### ISSUE TITLE
Setup using the instructions

### ISSUE THREAD

**Issue by stidston** [SwiftyBeaver/SwiftyBeaver#86]
![ce5yoc5w8aa55dh jpg-large](https://cloud.githubusercontent.com/assets/5347474/14212956/42b781ea-f82d-11e5-9fe4-b1aa48ac0e65.jpeg)
Having followed the documentation for manual install Xcode is flagging up the datatypes used in the code I copied from the instrcutions.

**Comment by skreutzberger** [comment]
What version of Xcode and SwiftyBeaver are you using?

**Comment by stidston** [comment]
Xcode 7.0.1
SwiftyBeaver from Thursday last week
Updating to 7.3 now!

**Comment by davidrothera** [comment]
Because of some Swift 2.2 changes Xcode 7.3 is required. Let us know if you still have issues after updating 😊

**Comment by stidston** [comment]
Thank you it's working great
