### ISSUE TITLE
All logs begin with untidy string "[0;37mV[0m:"

### ISSUE THREAD

**Issue by stidston** [SwiftyBeaver/SwiftyBeaver#87]
For example
`[0;37mV[0m: /Users/xxx/Documents/ add 1`

Setup
  ```
      let file = FileDestination()
        file.detailOutput = false
        file.levelString.Verbose = "V"
        file.dateFormat = ""
        file.logFileURL =  NSURL(fileURLWithPath: "/Users/x/Documents/x.log")
        Log.addDestination(file)
```

**Comment by skreutzberger** [comment]
That string are the escape characters for color support in modern terminals and CLI tools. You can either deactivate color support for your destination or use a modern terminal application which supports colors. For example Terminal.app for Mac OS X is supported.

**Comment by davidrothera** [comment]
This is because you have colors turned on but you don't have the XcodeColors plugin installed, check out https://github.com/SwiftyBeaver/SwiftyBeaver#no-colors

**Comment by davidrothera** [comment]
Ha, @skreutzberger beat me to it ;)

**Comment by skreutzberger** [comment]
Good to know: XcodeColors is just needed for the ConsoleDestination but not FileDestination which uses standard CLI coloring.
