### ISSUE TITLE
Introducing the SwiftyBeaver Logging Platform

### ISSUE THREAD

**Issue by skreutzberger** [SwiftyBeaver/SwiftyBeaver#88]
Fellow contributors & users,

I am more than happy to announce the **free private beta release** of the new [SwiftyBeaver Logging Platform](https://swiftybeaver.com). It adds all the missing pieces of a complete logging solution which can be used hassle-free during development and release.

True end-to-end **encryption**, a dedicated crypto cloud, a **Mac App**, native Swift 2 support and the  collection of new** analytics** data should help all of us getting more insights into how our apps perform and how our users are actually using it.

But read for yourself, I put the most important aspects into a [**short 2 minute article on Medium**](https://medium.com/swiftybeaver-blog/the-world-s-first-logging-platform-for-swift-25222bec387e#.r5gk9q8ab).

## A Note to All Contributors
I want to personally thank you for your help, ideas, discussions and time over the last months which made the transformation from a great logging framework (your work guys!) into a real venture with a solid value proposition for Swift developers just possible. You ignited and endorsed the idea of a logging platform for Swift and I am so happy to have it in a state to finally show it to you for input and feedback.

Of course, there are still many things to do but we can now build onto a mighty, growing platform and It would make me super happy if you all continue your efforts in making SwiftyBeaver into the best logging solution for all of us.

The next tasks are the finalizing of the new platform destination and especially your ideas how to make everything even better, adding more destinations and services, etc.

For that purpose will introduce an **invite-only Slack channel** where we can all discuss more efficiently. 

## Next Steps
Please put your email on the [**private beta waiting list**](https://swiftybeaver.com) and send me your email via Twitter DM [@skreutzb](https://twitter.com/skreutzb) so that I can prioritize your registration. I will send you then an invite to the Slack channel and information how to get your hands on the new platform destination and the Mac App.

I am very excited and am looking forward to a successful private beta.

Thank you all & Happy Logging!

**Comment by skreutzberger** [comment]
SwiftyBeaver contributors @prenagha @reesemclean @wvdk @irace @VDKA @fvvliet @manuelvanrijn @Narsail @r-peck @MariusCiocanel and @Pym - please read the announcement above. I would be honored to have you test-drive the new SwiftyBeaver Platform to get your input and feedback!  🙇 💯

**Comment by wvdk** [comment]
I'm not on twitter so I can't DM but I submitted to the waiting list under wesley@crat.es.

This sounds awesome man!

**Comment by fvvliet** [comment]
I don't use Twitter (DM) but have registered for the private beta. Thanks for the ability to join the beta of the SwiftyBeaver Logging Platform. It looks promising ;-)
Frank
