### ISSUE TITLE
Feedback, ideas or issues? Join our Slack Community!

### ISSUE THREAD

**Issue by skreutzberger** [SwiftyBeaver/SwiftyBeaver#91]
Hi,

join our [free Slack Community](https://slack.swiftybeaver.com) to discuss with fellow users and contributors how we can all make SwiftyBeaver even more awesome.

Thanks and CU on Slack!

**Comment by johndpope** [comment]
you guys need a Dotzu style in app logger. I'm just explaining - not complaining. 
https://github.com/remirobert/Dotzu

**Comment by johndpope** [comment]
Hi @skreutzberger - do you guys have any plans to do in app logging? like the link above? the dotzu memory leaks / performance is killing my app.

**Comment by skreutzberger** [comment]
@johndpope We do not plan to add something like that because it is better to have log browsing outside of your main app UI. You already mentioned the issues like a performance impact or interference with your app itself and its UI.

You can use the dedicated external SwiftyBeaver Mac App to browse the remote logs of your app on your users’ phones without any performance or UI issues for your users.

**Comment by johndpope** [comment]
This framework LumberjackConsole achieved in app logging without memory problems. https://github.com/PTEz/LumberjackConsole

Unfortunately - it couldn't support dynamic frameworks.
https://github.com/PTEz/LumberjackConsole/issues/2

There was this simpler hack that could get some mileage.
https://github.com/burczyk/UIForLumberjack

Also Apple's remote logging methods out of the box are pretty compelling
https://developer.apple.com/videos/play/wwdc2016/721/

I work at a corporate and for them to sign off on a paid logging app - consider in app logging is a must. Also - if you were to throw something up - software engineers may rally to help build it out.

**Comment by skreutzberger** [comment]
Thanks for the links, we put them under consideration. For new conversations please open a dedicated issue since this issue is just for official announcements.
